In [ ]:
import pandas as pd
import os

Получим имена всех собранных датасетов

In [ ]:
# https://sky.pro/wiki/media/rabota-s-fajlami-v-python-kak-poluchit-spisok-vseh-fajlov-v-direktorii/
kolesa_datasets = os.listdir('data/raw')

In [11]:
df_parsed = None
for filename in kolesa_datasets:
    if df_parsed is None:
        df_parsed = pd.read_csv('data/raw/' + filename)
        continue

    df_temp = pd.read_csv('data/raw/' + filename)
    df_parsed = pd.concat([df_parsed, df_temp], axis=0)

In [12]:
df_parsed

,kolesa_id,kolesa_url,parsed_at,brand,model,generation,year,city,body_type,fuel_type,...,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price,img_filename,img_url,found_img
0,220193990,https://kolesa.kz/a/show/220193990?search_id=4...,2026-06-06 01:23:01.328386+03:00,Toyota,Camry,2020 - н.в. XV70 рестайлинг (V75)\n,2021,"\n Сатпаев,...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n сере...,Да\n,6,11000000,220193990.webp,https://kolesa-photos.kcdn.online/webp/cb/cb13...,True
1,222243157,https://kolesa.kz/a/show/222243157?search_id=4...,2026-06-06 01:23:09.458448+03:00,Toyota,Camry,2009 - 2011 XV40 рестайлинг (V45)\n,2011,"\n Алматы, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n черн...,Да\n,5,5500000,222243157.webp,https://kolesa-photos.kcdn.online/webp/d7/d793...,True
2,222126406,https://kolesa.kz/a/show/222126406?search_id=4...,2026-06-06 01:23:16.941387+03:00,Toyota,Land Cruiser Prado,2002 - 2009 J120\n,2006,"\n Алматы, ...",Внедорожник\n,бензин,...,Автомат\n,Полный привод\n,Слева\n,\n белы...,Да\n,28,12900000,222126406.webp,https://kolesa-photos.kcdn.online/webp/b3/b3a4...,True
3,207561597,https://kolesa.kz/a/show/207561597?search_id=4...,2026-06-06 01:23:22.955538+03:00,Toyota,Camry,2004 - 2006 XV30 рестайлинг (V35)\n,2005,"\n Алматы, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n сере...,Да\n,7,4750000,207561597.webp,https://kolesa-photos.kcdn.online/webp/0b/0b7d...,True
4,222214559,https://kolesa.kz/a/show/222214559?search_id=4...,2026-06-06 01:23:35.089369+03:00,Toyota,Land Cruiser,2012 - 2015 J200 рестайлинг\n,2013,\n Кызылорд...,Внедорожник\n,бензин,...,Автомат\n,Полный привод\n,Слева\n,\n черн...,Да\n,6,21000000,222214559.webp,https://kolesa-photos.kcdn.online/webp/36/36ec...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,222362742,https://kolesa.kz/a/show/222362742?search_id=9...,2026-06-05 22:50:02.356644+03:00,Audi,A6,2011 - 2014 C7\n,2011,"\n Алматы, ...",Седан\n,бензин,...,Робот\n,Полный привод\n,Слева\n,NaN,Да\n,6,12400000,222362742.webp,https://kolesa-photos.kcdn.online/webp/ef/ef3b...,True
45,220504799,https://kolesa.kz/a/show/220504799?search_id=9...,2026-06-05 22:50:11.566301+03:00,Audi,100,1990 - 1994 4 поколение (C4)\n,1993,"\n Астана, ...",Седан\n,бензин,...,Механика\n,Передний привод\n,Слева\n,NaN,Да\n,14,2500000,220504799.webp,https://kolesa-photos.kcdn.online/webp/26/2670...,True
46,221883143,https://kolesa.kz/a/show/221883143?search_id=9...,2026-06-05 22:50:25.723227+03:00,Audi,A6,2004 - 2008 C6\n,2004,"\n Алматы, ...",Седан\n,бензин,...,Механика\n,Передний привод\n,Слева\n,\n фиол...,Да\n,12,4100000,221883143.webp,https://kolesa-photos.kcdn.online/webp/95/956c...,True
47,220605450,https://kolesa.kz/a/show/220605450?search_id=9...,2026-06-05 22:50:57.862094+03:00,Audi,A6,2001 - 2005 C5 рестайлинг\n,2001,\n Кокшетау...,Седан\n,бензин,...,Вариатор\n,Передний привод\n,Слева\n,\n борд...,Да\n,5,2000000,220605450.webp,https://kolesa-photos.kcdn.online/webp/10/109c...,True
48,180297138,https://kolesa.kz/a/show/180297138?search_id=9...,2026-06-05 22:51:07.313500+03:00,Audi,Q7,2015 - н.в. 2 поколение (4M)\n,2021,\n Петропав...,Кроссовер\n,бензин,...,Автомат\n,Полный привод\n,Слева\n,\n черн...,Да\n,19,45000000,180297138.webp,https://kolesa-photos.kcdn.online/webp/15/1521...,True

In [13]:
df_parsed.drop_duplicates('kolesa_id')

,kolesa_id,kolesa_url,parsed_at,brand,model,generation,year,city,body_type,fuel_type,...,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price,img_filename,img_url,found_img
0,220193990,https://kolesa.kz/a/show/220193990?search_id=4...,2026-06-06 01:23:01.328386+03:00,Toyota,Camry,2020 - н.в. XV70 рестайлинг (V75)\n,2021,"\n Сатпаев,...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n сере...,Да\n,6,11000000,220193990.webp,https://kolesa-photos.kcdn.online/webp/cb/cb13...,True
1,222243157,https://kolesa.kz/a/show/222243157?search_id=4...,2026-06-06 01:23:09.458448+03:00,Toyota,Camry,2009 - 2011 XV40 рестайлинг (V45)\n,2011,"\n Алматы, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n черн...,Да\n,5,5500000,222243157.webp,https://kolesa-photos.kcdn.online/webp/d7/d793...,True
2,222126406,https://kolesa.kz/a/show/222126406?search_id=4...,2026-06-06 01:23:16.941387+03:00,Toyota,Land Cruiser Prado,2002 - 2009 J120\n,2006,"\n Алматы, ...",Внедорожник\n,бензин,...,Автомат\n,Полный привод\n,Слева\n,\n белы...,Да\n,28,12900000,222126406.webp,https://kolesa-photos.kcdn.online/webp/b3/b3a4...,True
3,207561597,https://kolesa.kz/a/show/207561597?search_id=4...,2026-06-06 01:23:22.955538+03:00,Toyota,Camry,2004 - 2006 XV30 рестайлинг (V35)\n,2005,"\n Алматы, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n сере...,Да\n,7,4750000,207561597.webp,https://kolesa-photos.kcdn.online/webp/0b/0b7d...,True
4,222214559,https://kolesa.kz/a/show/222214559?search_id=4...,2026-06-06 01:23:35.089369+03:00,Toyota,Land Cruiser,2012 - 2015 J200 рестайлинг\n,2013,\n Кызылорд...,Внедорожник\n,бензин,...,Автомат\n,Полный привод\n,Слева\n,\n черн...,Да\n,6,21000000,222214559.webp,https://kolesa-photos.kcdn.online/webp/36/36ec...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,222362742,https://kolesa.kz/a/show/222362742?search_id=9...,2026-06-05 22:50:02.356644+03:00,Audi,A6,2011 - 2014 C7\n,2011,"\n Алматы, ...",Седан\n,бензин,...,Робот\n,Полный привод\n,Слева\n,NaN,Да\n,6,12400000,222362742.webp,https://kolesa-photos.kcdn.online/webp/ef/ef3b...,True
45,220504799,https://kolesa.kz/a/show/220504799?search_id=9...,2026-06-05 22:50:11.566301+03:00,Audi,100,1990 - 1994 4 поколение (C4)\n,1993,"\n Астана, ...",Седан\n,бензин,...,Механика\n,Передний привод\n,Слева\n,NaN,Да\n,14,2500000,220504799.webp,https://kolesa-photos.kcdn.online/webp/26/2670...,True
46,221883143,https://kolesa.kz/a/show/221883143?search_id=9...,2026-06-05 22:50:25.723227+03:00,Audi,A6,2004 - 2008 C6\n,2004,"\n Алматы, ...",Седан\n,бензин,...,Механика\n,Передний привод\n,Слева\n,\n фиол...,Да\n,12,4100000,221883143.webp,https://kolesa-photos.kcdn.online/webp/95/956c...,True
47,220605450,https://kolesa.kz/a/show/220605450?search_id=9...,2026-06-05 22:50:57.862094+03:00,Audi,A6,2001 - 2005 C5 рестайлинг\n,2001,\n Кокшетау...,Седан\n,бензин,...,Вариатор\n,Передний привод\n,Слева\n,\n борд...,Да\n,5,2000000,220605450.webp,https://kolesa-photos.kcdn.online/webp/10/109c...,True
48,180297138,https://kolesa.kz/a/show/180297138?search_id=9...,2026-06-05 22:51:07.313500+03:00,Audi,Q7,2015 - н.в. 2 поколение (4M)\n,2021,\n Петропав...,Кроссовер\n,бензин,...,Автомат\n,Полный привод\n,Слева\n,\n черн...,Да\n,19,45000000,180297138.webp,https://kolesa-photos.kcdn.online/webp/15/1521...,True

In [22]:
df_parsed.info()

<class 'pandas.DataFrame'>
Index: 1400 entries, 0 to 48
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kolesa_id        1400 non-null   int64
 1   kolesa_url       1400 non-null   str
 2   parsed_at        1400 non-null   str
 3   brand            1400 non-null   str
 4   model            1400 non-null   str
 5   generation       1400 non-null   str
 6   year             1400 non-null   int64
 7   city             1400 non-null   str
 8   body_type        1400 non-null   str
 9   fuel_type        1400 non-null   str
 10  engine_volume    1400 non-null   float64
 11  mileage          1400 non-null   int64
 12  transmission     1400 non-null   str
 13  drive_type       1400 non-null   str
 14  steering_wheel   1400 non-null   str
 15  color            1043 non-null   str
 16  kz_registration  1400 non-null   str
 17  imgs_count       1400 non-null   int64
 18  price            1400 non-null   int64
 19  img_filename     1396 non-null   str
 20  img_url          1396 non-null   str
 21  found_img        1400 non-null   bool
dtypes: bool(1), float64(1), int64(5), str(15)
memory usage: 242.0 KB

In [25]:
df_parsed[df_parsed['found_img'] == True].to_csv('first_df.csv', index=False)