In [1]:
import pandas as pd

## Описание признаков

- kolesa_id - уникальный id объявления со стороны сервиса
- kolesa_url - ссылка на объявление
- parsed_at - дата и время получения объявления
- brand - марка авто
- model - модель авто
- generation - поколение данного авто (этой марки)
- year - год выпуска авто
- city - город публикации объявление
- body_type - тип кузова авто
- fuel_type - тип топлива
- engine_volume - объем двигателя
- mileage - пробег в км
- transmission - тип коробки/трансмиссии
- drive_type - тип привода
- steering_wheel - расположение руля
- color - цвет авто    
- kz_registration - растаможен ли в Казахстане
- imgs_count - количество фотографий в объявлении
- price - цена продажи
- img_filename - название файла с главным фото объявления
- img_url - ссылка на на главное фото объявления
- found_img - нашли ли фото

Из них технические: kolesa_id, kolesa_url, parsed_at, img_filename, img_url, found_img

Все остальные могут быть рассмотрены для решения задачи DL на табличных данных

In [2]:
df = pd.read_csv('third_df.csv')
df

,kolesa_id,kolesa_url,parsed_at,brand,model,generation,year,city,body_type,fuel_type,...,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price,img_filename,img_url,found_img
0,221971452,https://kolesa.kz/a/show/221971452?search_id=4...,2026-06-08 10:31:39.616294+03:00,Kia,K5,2023 - н.в. 3 поколение рестайлинг\n,2025,"\n Астана, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n черн...,Да\n,13,14100000,221971452.webp,https://kolesa-photos.kcdn.online/webp/72/724f...,True
1,184557634,https://kolesa.kz/a/show/184557634?search_id=4...,2026-06-08 10:31:55.104766+03:00,Kia,Sorento,2017 - 2020 3 поколение рестайлинг (UM)\n,2020,"\n Астана, ...",Кроссовер\n,бензин,...,Автомат\n,Полный привод\n,Слева\n,\n кори...,Да\n,11,13500000,184557634.webp,https://kolesa-photos.kcdn.online/webp/3f/3f1b...,True
2,222310850,https://kolesa.kz/a/show/222310850?search_id=4...,2026-06-08 10:32:07.399668+03:00,Kia,K7,2012 - 2015 1 поколение рестайлинг\n,2014,"\n Алматы, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n черн...,Да\n,25,9500000,222310850.webp,https://kolesa-photos.kcdn.online/webp/13/136a...,True
3,206731143,https://kolesa.kz/a/show/206731143?search_id=4...,2026-06-08 10:32:37.197220+03:00,Kia,Soul,2013 - 2016 2 поколение (PS)\n,2014,\n Караганд...,Хэтчбек\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n крас...,Да\n,15,6300000,206731143.webp,https://kolesa-photos.kcdn.online/webp/95/95f3...,True
4,221564600,https://kolesa.kz/a/show/221564600?search_id=4...,2026-06-08 10:33:04.907473+03:00,Kia,Soul,2011 - 2014 1 поколение рестайлинг (AM)\n,2013,\n Панфилов...,Хэтчбек\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,\n беже...,Да\n,13,5600000,221564600.webp,https://kolesa-photos.kcdn.online/webp/d4/d458...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3712,222254836,https://kolesa.kz/a/show/222254836?search_id=3...,2026-06-06 20:48:05.146091+03:00,Kia,Sportage,2010 - 2014 3 поколение (SL)\n,2014,\n Мангиста...,Кроссовер\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,NaN,Да\n,7,7100000,222254836.webp,https://kolesa-photos.kcdn.online/webp/f0/f072...,True
3713,221970223,https://kolesa.kz/a/show/221970223?search_id=3...,2026-06-06 20:48:19.201839+03:00,Kia,Sorento,2002 - 2006 1 поколение (JC)\n,2004,\n Усть-Кам...,Внедорожник\n,газ-бензин,...,Автомат\n,Полный привод\n,Слева\n,\n сере...,Да\n,8,2900000,221970223.webp,https://kolesa-photos.kcdn.online/webp/ef/ef3e...,True
3714,220273619,https://kolesa.kz/a/show/220273619?search_id=3...,2026-06-06 20:48:34.185487+03:00,Kia,K5,2019 - н.в. 3 поколение\n,2022,"\n Алматы, ...",Седан\n,бензин,...,Автомат\n,Передний привод\n,Слева\n,NaN,Да\n,18,10800000,220273619.webp,https://kolesa-photos.kcdn.online/webp/c4/c497...,True
3715,209668596,https://kolesa.kz/a/show/209668596?search_id=3...,2026-06-06 20:49:03.080793+03:00,Kia,Sportage,2018 - н.в. 4 поколение рестайлинг\n,2021,"\n Алматы, ...",Кроссовер\n,бензин,...,Автомат\n,Полный привод\n,Слева\n,\n белы...,Да\n,26,11500000,209668596.webp,https://kolesa-photos.kcdn.online/webp/f0/f020...,True
3716,218447227,https://kolesa.kz/a/show/218447227?search_id=3...,2026-06-06 20:49:31.995428+03:00,Kia,Sorento,2020 - н.в. 4 поколение (MQ4/MQ4A)\n,2023,"\n Алматы, ...",Кроссовер\n,бензин,...,Автомат\n,Полный привод\n,Слева\n,\n черн...,Да\n,14,15000000,218447227.webp,https://kolesa-photos.kcdn.online/webp/4b/4b8e...,True

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3717 entries, 0 to 3716
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kolesa_id        3717 non-null   int64
 1   kolesa_url       3717 non-null   str
 2   parsed_at        3717 non-null   str
 3   brand            3717 non-null   str
 4   model            3717 non-null   str
 5   generation       3712 non-null   str
 6   year             3717 non-null   int64
 7   city             3717 non-null   str
 8   body_type        3717 non-null   str
 9   fuel_type        3717 non-null   str
 10  engine_volume    3717 non-null   float64
 11  mileage          3717 non-null   int64
 12  transmission     3717 non-null   str
 13  drive_type       3717 non-null   str
 14  steering_wheel   3717 non-null   str
 15  color            2751 non-null   str
 16  kz_registration  3717 non-null   str
 17  imgs_count       3717 non-null   int64
 18  price            3717 non-null   int64
 19  img_filename     3706 non-null   str
 20  img_url          3706 non-null   str
 21  found_img        3717 non-null   bool
dtypes: bool(1), float64(1), int64(5), str(15)
memory usage: 613.6 KB

## Подгтовим данные для дальнейшей работы

Общая проверка на пропуски

In [17]:
df.isna().sum()

kolesa_id            0
kolesa_url           0
parsed_at            0
brand                0
model                0
generation           5
year                 0
city                 0
body_type            0
fuel_type            0
engine_volume        0
mileage              0
transmission         0
drive_type           0
steering_wheel       0
color              966
kz_registration      0
imgs_count           0
price                0
img_filename        11
img_url             11
found_img            0
dtype: int64

Основная проблема - пропуски в color. Это было обнаружено еще в ходе парсинга. Заполним их значением 

Пропуски в img_filename и img_url мы будем отдельно обрабатывать позже

In [18]:
df['color'] = df['color'].fillna('unknown')

### City, body_type, transmission, drive_type, steering_wheel, color, kz_registration

In [14]:
df[['city', 'body_type', 'transmission', 'drive_type', 'steering_wheel', 'color', 'kz_registration']]

,city,body_type,transmission,drive_type,steering_wheel,color,kz_registration
0,"Астана, Акмолинская область",Седан,Автомат\n,Передний привод\n,Слева\n,\n черн...,Да\n
1,"Астана, Акмолинская область",Кроссовер,Автомат\n,Полный привод\n,Слева\n,\n кори...,Да\n
2,"Алматы, Алматинская область",Седан,Автомат\n,Передний привод\n,Слева\n,\n черн...,Да\n
3,"Караганда, Карагандинская область",Хэтчбек,Автомат\n,Передний привод\n,Слева\n,\n крас...,Да\n
4,"Панфилово (Талгарский р-н), Алматинская область",Хэтчбек,Автомат\n,Передний привод\n,Слева\n,\n беже...,Да\n
...,...,...,...,...,...,...,...
3712,"Мангистау, Мангистауская область",Кроссовер,Автомат\n,Передний привод\n,Слева\n,NaN,Да\n
3713,"Усть-Каменогорск, Восточно-Казахстанская область",Внедорожник,Автомат\n,Полный привод\n,Слева\n,\n сере...,Да\n
3714,"Алматы, Алматинская область",Седан,Автомат\n,Передний привод\n,Слева\n,NaN,Да\n
3715,"Алматы, Алматинская область",Кроссовер,Автомат\n,Полный привод\n,Слева\n,\n белы...,Да\n
3716,"Алматы, Алматинская область",Кроссовер,Автомат\n,Полный привод\n,Слева\n,\n черн...,Да\n

Все это признаки, содержащие текст

Заметим, что у нас не убраны символы переноса строк \n и, возможно, лишние пробелы

Уберем это у всех этих признаков

In [16]:
df['color'].value_counts()

color
\n                                        белый \n                                                      474
\n                                        черный металлик\n                                             399
\n                                        белый металлик\n                                              345
\n                                        черный \n                                                     290
\n                                        серебристый металлик\n                                        278
\n                                        серый металлик\n                                              201
\n                                        серый \n                                                      178
\n                                        синий металлик\n                                              120
\n                                        серебристый \n                                                111
\n                                        синий \n                                                       70
\n                                        зеленый металлик\n                                             40
\n                                        зеленый \n                                                     27
\n                                        коричневый металлик\n                                          22
\n                                        коричневый \n                                                  19
\n                                        бордовый металлик\n                                            16
\n                                        красный \n                                                     15
\n                                        золотистый металлик\n                                          14
\n                                        бордовый \n                                                    13
\n                                        вишня металлик\n                                               13
\n                                        золотистый \n                                                  11
\n                                        вишня \n                                                       10
\n                                        красный металлик\n                                              9
\n                                        бежевый металлик\n                                              9
\n                                        бронза металлик\n                                               9
\n                                        бежевый \n                                                      9
\n                                        хамелеон металлик\n                                             7
\n                                        жёлтый \n                                                       6
\n                                        голубой металлик\n                                              6
\n                                        бронза \n                                                       4
\n                                        жёлтый металлик\n                                               4
\n                                        голубой \n                                                      3
\n                                        оранжевый металлик\n                                            3
\n                                        бирюзовый металлик\n                                            3
\n                                        хамелеон \n                                                     3
\n                                        фиолетовый \n                                                   3
\n                                        оранжевый \n                                                    2
\n                                        фиолетовый металлик\n                                           2
\n                                        бирюзовый \n                                                    1
\n                                        сиреневый металлик\n                                            1
\n                                        сиреневый \n                                                    1
Name: count, dtype: int64

In [19]:
df['city'] = df['city'].apply(lambda x: x.replace('\n', '').strip())
df['body_type'] = df['body_type'].apply(lambda x: x.replace('\n', '').strip())
df['transmission'] = df['transmission'].apply(lambda x: x.replace('\n', '').strip())
df['drive_type'] = df['drive_type'].apply(lambda x: x.replace('\n', '').strip())
df['steering_wheel'] = df['steering_wheel'].apply(lambda x: x.replace('\n', '').strip())
df['color'] = df['color'].apply(lambda x: x.replace('\n', '').strip())
df['kz_registration'] = df['kz_registration'].apply(lambda x: x.replace('\n', '').strip())

In [20]:
df[['city', 'body_type', 'transmission', 'drive_type', 'steering_wheel', 'color', 'kz_registration']]

,city,body_type,transmission,drive_type,steering_wheel,color,kz_registration
0,"Астана, Акмолинская область",Седан,Автомат,Передний привод,Слева,черный металлик,Да
1,"Астана, Акмолинская область",Кроссовер,Автомат,Полный привод,Слева,коричневый,Да
2,"Алматы, Алматинская область",Седан,Автомат,Передний привод,Слева,черный металлик,Да
3,"Караганда, Карагандинская область",Хэтчбек,Автомат,Передний привод,Слева,красный металлик,Да
4,"Панфилово (Талгарский р-н), Алматинская область",Хэтчбек,Автомат,Передний привод,Слева,бежевый металлик,Да
...,...,...,...,...,...,...,...
3712,"Мангистау, Мангистауская область",Кроссовер,Автомат,Передний привод,Слева,unknown,Да
3713,"Усть-Каменогорск, Восточно-Казахстанская область",Внедорожник,Автомат,Полный привод,Слева,серебристый металлик,Да
3714,"Алматы, Алматинская область",Седан,Автомат,Передний привод,Слева,unknown,Да
3715,"Алматы, Алматинская область",Кроссовер,Автомат,Полный привод,Слева,белый металлик,Да
3716,"Алматы, Алматинская область",Кроссовер,Автомат,Полный привод,Слева,черный металлик,Да

In [21]:
df.to_csv('clean_df.csv', index=False)

In [22]:
df_table = df.copy()
df_table = df_table.drop(columns=['kolesa_id', 'kolesa_url', 'parsed_at', 'img_filename', 'img_url', 'found_img'])
df_table.info()

<class 'pandas.DataFrame'>
RangeIndex: 3717 entries, 0 to 3716
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            3717 non-null   str
 1   model            3717 non-null   str
 2   generation       3712 non-null   str
 3   year             3717 non-null   int64
 4   city             3717 non-null   str
 5   body_type        3717 non-null   str
 6   fuel_type        3717 non-null   str
 7   engine_volume    3717 non-null   float64
 8   mileage          3717 non-null   int64
 9   transmission     3717 non-null   str
 10  drive_type       3717 non-null   str
 11  steering_wheel   3717 non-null   str
 12  color            3717 non-null   str
 13  kz_registration  3717 non-null   str
 14  imgs_count       3717 non-null   int64
 15  price            3717 non-null   int64
dtypes: float64(1), int64(4), str(11)
memory usage: 464.8 KB