In [1]:
import os
import wandb

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

import numpy as np
import pandas as pd
import random
from tqdm import *

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets
import torchvision.transforms as transforms

try:
    from torchinfo import summary
except:
    print("[INFO] Couldn't find torchinfo... installing it.")
    !pip install -q torchinfo
    from torchinfo import summary

from PIL import Image

import matplotlib.pyplot as plt
%matplotlib inline

### Зафиксируем seed для воспроизводимости

In [2]:
def seed_everything(seed):
    random.seed(seed) # фиксируем генератор случайных чисел
    os.environ['PYTHONHASHSEED'] = str(seed) # фиксируем заполнения хешей
    np.random.seed(seed) # фиксируем генератор случайных чисел numpy
    torch.manual_seed(seed) # фиксируем генератор случайных чисел pytorch
    torch.cuda.manual_seed(seed) # фиксируем генератор случайных чисел для GPU
    torch.backends.cudnn.deterministic = True # выбираем только детерминированные алгоритмы (для сверток)
    torch.backends.cudnn.benchmark = False # фиксируем алгоритм вычисления сверток

### Задаем параметры (конфиг)

In [3]:
all_brands = ('Audi', 'BMW', 'Chevrolet', 'Hyundai', 'Kia', 'Lexus', 'Mercedes-Benz', 'Toyota')
all_body_types = ('sedan', 'SUV')

class CFG:
  api = ""
  project = "kolesa-cars"
  entity = "armntvs-d3v-student"
  num_epochs = 10
  train_batch_size = 32
  test_batch_size = 512
  num_workers = 0
  lr = 3e-4
  seed = 42
  classes = all_body_types
  wandb = True

In [ ]:
# вход в W&B (ключ спросит один раз, берём с https://wandb.ai/authorize)
wandb.login()

In [4]:
seed_everything(CFG.seed)

In [5]:
# Переведем наш класс с параметрами в словарь

def class2dict(f):
  return dict((name, getattr(f, name)) for name in dir(f) if not name.startswith('__'))

### Импортируем наш датасет с картинками

In [6]:
try:
  from google.colab import drive
  drive.mount('/content/drive')
  !cp -r /content/drive/MyDrive/gp5_images/data /content/data

  base_dir = '/content/data'
except:
  base_dir = '../data'

from pathlib import Path

base_dir = Path(base_dir)

In [7]:
df_bt = pd.read_csv(base_dir / 'prepared_df_images.csv')
df_bt

      kolesa_id    body_type    img_filename  target
0     220599328        Седан  220599328.webp       0
1     222486528        Седан  222486528.webp       0
2     218695550  Внедорожник  218695550.webp       1
3     214781208        Седан  214781208.webp       0
4     222346737        Седан  222346737.webp       0
...         ...          ...             ...     ...
4428  222478046        Седан  222478046.webp       0
4429  222704181        Седан  222704181.webp       0
4430  220000872        Седан  220000872.webp       0
4431  222542135        Седан  222542135.webp       0
4432  220019907    Кроссовер  220019907.webp       1

[4433 rows x 4 columns]

In [8]:
df_brand = pd.read_csv(base_dir / 'brand_df_images.csv')
df_brand

      kolesa_id      brand    body_type    img_filename  target
0     220599328  Chevrolet        Седан  220599328.webp       2
1     222486528  Chevrolet        Седан  222486528.webp       2
2     218695550  Chevrolet  Внедорожник  218695550.webp       2
3     214781208  Chevrolet        Седан  214781208.webp       2
4     222346737  Chevrolet        Седан  222346737.webp       2
...         ...        ...          ...             ...     ...
4428  222478046    Hyundai        Седан  222478046.webp       3
4429  222704181    Hyundai        Седан  222704181.webp       3
4430  220000872    Hyundai        Седан  220000872.webp       3
4431  222542135    Hyundai        Седан  222542135.webp       3
4432  220019907    Hyundai    Кроссовер  220019907.webp       3

[4433 rows x 5 columns]

In [9]:
train_df_bt, test_all_df_bt = train_test_split(df_bt, test_size=0.3, stratify=df_bt['target'], random_state=CFG.seed)
val_df_bt, test_df_bt = train_test_split(test_all_df_bt, test_size=0.5, stratify=test_all_df_bt['target'], random_state=CFG.seed)

train_df_brand, test_all_df_brand = train_test_split(df_brand, test_size=0.3, stratify=df_brand['target'], random_state=CFG.seed)
val_df_brand, test_df_brand = train_test_split(test_all_df_brand, test_size=0.5, stratify=test_all_df_brand['target'], random_state=CFG.seed)

In [10]:
# https://stackoverflow.com/questions/65231299/load-csv-and-image-dataset-in-pytorch

class KolesaDataset(torch.utils.data.Dataset):
    def __init__(self, df, images_folder = base_dir / 'images', transform = None):
        # т.к. после train_test_split индексы сохряняются из исходного датасета, то мы их сбрасываем и удаляем колонку со старыми индексами для корректной работы __getitem___
        self.df = df.reset_index().drop(columns=['index'])
        self.images_folder = images_folder
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, index):
        filename = self.df.loc[index, 'img_filename']
        label = self.df.loc[index, 'target']
        image = Image.open(os.path.join(self.images_folder, filename)).convert('RGB')

        if self.transform is not None:
            image = self.transform(image)

        return image, label

### Функции обучения и инференса

In [11]:
# функция обучения
def train(model, device, train_loader, optimizer, criterion, epoch, WANDB):
    model.train()
    train_loss = 0
    correct = 0

    n_ex = len(train_loader)

    for batch_idx, (data, target) in tqdm(enumerate(train_loader), total=n_ex):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad() # обнуляем градиенты
        output = model(data)
        pred = output.argmax(dim=1, keepdim=True)
        correct += pred.eq(target.view_as(pred)).sum().item()
        train_loss = criterion(output, target) # считаем лосс
        train_loss.backward() # обратный проход
        optimizer.step() # делаем шаг оптимизатором

    tqdm.write('\nTrain set: Average loss: {:.4f}, Accuracy: {:.2f}%'.format(
        train_loss, 100. * correct / len(train_loader.dataset)))

    # логируем функцию потерь и точность
    if WANDB:
        wandb.log({'train_loss': train_loss,
                   'train_accuracy': correct / len(train_loader.dataset)})

In [12]:
# функция инференса
def test(model, device, test_loader, criterion, WANDB):
    model.eval()
    test_loss = 0
    correct = 0

    preds = []
    targets = []
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss = criterion(output, target)
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

            # https://stackoverflow.com/questions/53467215/convert-pytorch-cuda-tensor-to-numpy-array
            preds.extend(pred.cpu().numpy())
            targets.extend(target.cpu().numpy())

    # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html
    report = classification_report(targets, preds, target_names=CFG.classes)

    tqdm.write('Test set: Average loss: {:.4f}, Accuracy: {:.2f}%'.format(
        test_loss, 100. * correct / len(test_loader.dataset)))

    tqdm.write('\nClassification report:\n' + report)

    if WANDB:
        wandb.log({'test_loss': test_loss,
                   'test_accuracy': correct / len(test_loader.dataset)})

# функция инференса
def val(model, device, val_loader, criterion, WANDB):
    model.eval()
    val_loss = 0
    correct = 0

    preds = []
    targets = []
    with torch.no_grad():
        for data, target in val_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            val_loss = criterion(output, target)
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

            preds.extend(pred.cpu().numpy())
            targets.extend(target.cpu().numpy())

    report = classification_report(targets, preds, target_names=CFG.classes)

    tqdm.write('Val set: Average loss: {:.4f}, Accuracy: {:.2f}%'.format(
        val_loss, 100. * correct / len(val_loader.dataset)))

    tqdm.write('\nClassification report:\n' + report)

    if WANDB:
        wandb.log({'val_loss': val_loss,
                   'val_accuracy': correct / len(val_loader.dataset)})

### Основная функция для прогона моделей

In [13]:
def main_kolesa(model, train_df, val_df):

    if CFG.wandb:
        wandb.init(project=CFG.project, entity=CFG.entity, reinit=True, config=class2dict(CFG))
        # логируем архитектуру модели
        # https://docs.wandb.ai/guides/track/config
        wandb.config.update({'model': str(model)})

    seed_everything(CFG.seed)
    # https://stackoverflow.com/questions/63423463/using-pytorch-cuda-on-macbook-pro
    # т.к. на macbook на их процессорах apple silicon нет cuda (только для карт nvidia), то используем альтеранативу, но если есть cuda - то используем ее
    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')

    kwargs = {'num_workers': CFG.num_workers, 'pin_memory': torch.cuda.is_available()}

    # наши картинки в исходном размере 750*470 + если домножить на число каналов (3), то получится около миллиарда параметра на вход.
    # Это довольно много так что пропорционально уменьшим размерность. У нас 750 к 470 это, можно сказать, 1.6 к 1. Уменьшим 750 до 160 => 470 -> 96.
    # будем использовать различные методы аугментации https://docs.pytorch.org/vision/0.13/transforms.html
    train_transform = transforms.Compose([
        transforms.Resize((96, 160)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.1),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    test_transform = transforms.Compose([
        transforms.Resize((96, 160)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    train_ds = KolesaDataset(train_df, transform=train_transform)
    val_ds = KolesaDataset(val_df, transform=test_transform)
    # test_ds = KolesaDataset(test_df, transform=test_transform)

    train_loader = torch.utils.data.DataLoader(train_ds, batch_size=CFG.train_batch_size, **kwargs)
    val_loader = torch.utils.data.DataLoader(val_ds, batch_size=CFG.test_batch_size, **kwargs)
    # test_loader = torch.utils.data.DataLoader(test_ds, batch_size=CFG.test_batch_size, **kwargs)

    model = model.to(device)

    if CFG.wandb:
        wandb.watch(model, log='all')

    optimizer = optim.Adam(model.parameters(),
                          lr=CFG.lr)

    criterion = nn.CrossEntropyLoss()

    for epoch in range(1, CFG.num_epochs + 1):
        print('\nEpoch:', epoch)
        train(model, device, train_loader, optimizer, criterion, epoch, CFG.wandb)
        val(model, device, val_loader, criterion, CFG.wandb)

    print('Training is ended!')

### Сохранение моделей

Чтобы у каждой модели сохранялся артефакт, добавим маленькую вспомогательную функцию. `main_kolesa` логирует loss/accuracy по эпохам в W&B сам, а эта функция дописывает в тот же запуск файл с весами.

In [14]:
def save_model_artifact(model, name):
    # сохранение модели как артефакт
    # https://docs.wandb.ai/guides/artifacts
    path = f'../data/models/{name}.pt' #путь к файлу в зависимости от имени модели (передаем в начале), .pt -расширение для объектов pytorch
    torch.save(model.state_dict(), path) #сохраняем параметры модели
    if CFG.wandb:
        wandb.run.name = name   # называем запуск как модель
        artifact = wandb.Artifact(name, type='model') #создаем артефакт-контейннер
        artifact.add_file(path) #добавляем в него файл с параметрами модели (брали выше)
        wandb.log_artifact(artifact) #загружаем артефакт и привящываем к текущему щапуску
        wandb.finish()  # закрываем текущий запуск
    print(f'[OK] модель сохранена: {path}')

In [ ]:
# логируем данные в W&B, чтобы запуск воспроизводился из неё
# https://docs.wandb.ai/guides/artifacts
# выполнить ОДИН раз
if CFG.wandb:
    wandb.init(project=CFG.project, entity=CFG.entity, reinit=True, name='dataset')
    art = wandb.Artifact('kolesa-data', type='dataset')
    art.add_file('../data/prepared_df_images.csv')
    art.add_file('../data/brand_df_images.csv')
    art.add_dir('../data/images', name='images')   # ~475 МБ, грузится долго
    wandb.log_artifact(art)
    wandb.finish()

## Fully Connected в качестве baseline

Возьмем для примера определение весов нормальным распределением

In [15]:
# определяем полносвязанную сеть
class FC_Net(nn.Module):
    def __init__(self, task='body_type'):
        super(FC_Net, self).__init__()

        self.task = task

        self.fc1 = nn.Linear(160*96*3, 1024)
        self.fc2 = nn.Linear(1024, 512)
        self.fc3 = nn.Linear(512, 128)
        if self.task == 'body_type':
            self.fc4 = nn.Linear(128, 2)
        elif self.task == 'brand':
            self.fc4 = nn.Linear(128, 8)

        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.normal_(m.weight)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        x = x.view(-1, 160*96*3)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return x

#### Задача на тип кузова

In [16]:
model_baseline_bt = FC_Net()

In [17]:
summary(model=model_baseline_bt,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
FC_Net                                   [32, 3, 96, 160]     [32, 2]              --                   True
├─Linear: 1-1                            [32, 46080]          [32, 1024]           47,186,944           True
├─Linear: 1-2                            [32, 1024]           [32, 512]            524,800              True
├─Linear: 1-3                            [32, 512]            [32, 128]            65,664               True
├─Linear: 1-4                            [32, 128]            [32, 2]              258                  True
========================================================================================================================
Total params: 47,777,666
Trainable params: 47,777,666
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 1.53
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 0.43
Params size (MB): 191.11
Estimated Total Size (MB): 197.44
========================================================================================================================

In [18]:
main_kolesa(model_baseline_bt, train_df = train_df_bt, val_df = val_df_bt)
save_model_artifact(model_baseline_bt, 'BaseLine_FC_body_type')

Epoch: 1

100%|██████████| 97/97 [00:13<00:00,  7.09it/s]

Train set: Average loss: 200857.7031, Accuracy: 54.04%
Val set: Average loss: 133297.0781, Accuracy: 54.74%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.58      0.62       418
         SUV       0.41      0.50      0.45       247

    accuracy                           0.55       665
   macro avg       0.54      0.54      0.53       665
weighted avg       0.57      0.55      0.55       665


Epoch: 2

100%|██████████| 97/97 [00:12<00:00,  7.49it/s]

Train set: Average loss: 100811.1328, Accuracy: 56.91%
Val set: Average loss: 111838.9688, Accuracy: 56.24%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.63      0.64       418
         SUV       0.42      0.45      0.43       247

    accuracy                           0.56       665
   macro avg       0.54      0.54      0.54       665
weighted avg       0.57      0.56      0.57       665


Epoch: 3

100%|██████████| 97/97 [00:12<00:00,  7.60it/s]

Train set: Average loss: 76960.2578, Accuracy: 59.10%
Val set: Average loss: 117247.1484, Accuracy: 53.98%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.56      0.60       418
         SUV       0.41      0.51      0.45       247

    accuracy                           0.54       665
   macro avg       0.53      0.53      0.53       665
weighted avg       0.56      0.54      0.55       665


Epoch: 4

100%|██████████| 97/97 [00:13<00:00,  7.24it/s]

Train set: Average loss: 72098.4844, Accuracy: 59.33%
Val set: Average loss: 99333.6172, Accuracy: 54.44%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.58      0.61       418
         SUV       0.41      0.49      0.44       247

    accuracy                           0.54       665
   macro avg       0.53      0.53      0.53       665
weighted avg       0.56      0.54      0.55       665


Epoch: 5

100%|██████████| 97/97 [00:13<00:00,  7.40it/s]

Train set: Average loss: 80034.0312, Accuracy: 61.26%
Val set: Average loss: 95483.2578, Accuracy: 57.29%

Classification report:
              precision    recall  f1-score   support

       sedan       0.67      0.64      0.65       418
         SUV       0.43      0.47      0.45       247

    accuracy                           0.57       665
   macro avg       0.55      0.55      0.55       665
weighted avg       0.58      0.57      0.58       665


Epoch: 6

100%|██████████| 97/97 [00:13<00:00,  7.17it/s]

Train set: Average loss: 64985.2344, Accuracy: 61.65%
Val set: Average loss: 89875.2188, Accuracy: 55.64%

Classification report:
              precision    recall  f1-score   support

       sedan       0.68      0.56      0.61       418
         SUV       0.42      0.55      0.48       247

    accuracy                           0.56       665
   macro avg       0.55      0.56      0.55       665
weighted avg       0.58      0.56      0.56       665


Epoch: 7

100%|██████████| 97/97 [00:13<00:00,  7.45it/s]

Train set: Average loss: 41940.0117, Accuracy: 63.97%
Val set: Average loss: 81814.4062, Accuracy: 55.19%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.58      0.62       418
         SUV       0.42      0.51      0.46       247

    accuracy                           0.55       665
   macro avg       0.54      0.54      0.54       665
weighted avg       0.57      0.55      0.56       665


Epoch: 8

100%|██████████| 97/97 [00:12<00:00,  7.52it/s]

Train set: Average loss: 67743.3906, Accuracy: 62.84%
Val set: Average loss: 82431.4219, Accuracy: 57.29%

Classification report:
              precision    recall  f1-score   support

       sedan       0.67      0.63      0.65       418
         SUV       0.43      0.48      0.46       247

    accuracy                           0.57       665
   macro avg       0.55      0.55      0.55       665
weighted avg       0.58      0.57      0.58       665


Epoch: 9

100%|██████████| 97/97 [00:12<00:00,  7.58it/s]

Train set: Average loss: 51832.0078, Accuracy: 64.90%
Val set: Average loss: 74938.6016, Accuracy: 56.69%

Classification report:
              precision    recall  f1-score   support

       sedan       0.68      0.59      0.63       418
         SUV       0.43      0.52      0.47       247

    accuracy                           0.57       665
   macro avg       0.55      0.56      0.55       665
weighted avg       0.59      0.57      0.57       665


Epoch: 10

100%|██████████| 97/97 [00:12<00:00,  7.72it/s]

Train set: Average loss: 30968.8867, Accuracy: 63.68%
Val set: Average loss: 71612.6641, Accuracy: 55.49%

Classification report:
              precision    recall  f1-score   support

       sedan       0.67      0.57      0.62       418
         SUV       0.42      0.53      0.47       247

    accuracy                           0.55       665
   macro avg       0.55      0.55      0.54       665
weighted avg       0.58      0.55      0.56       665

Training is ended!
[OK] модель сохранена: ../data/models/BaseLine_FC_body_type.pt

#### Задача на определение марки

In [19]:
CFG.classes = all_brands

model_baseline_brand = FC_Net(task='brand')

In [20]:
summary(model=model_baseline_brand,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
FC_Net                                   [32, 3, 96, 160]     [32, 8]              --                   True
├─Linear: 1-1                            [32, 46080]          [32, 1024]           47,186,944           True
├─Linear: 1-2                            [32, 1024]           [32, 512]            524,800              True
├─Linear: 1-3                            [32, 512]            [32, 128]            65,664               True
├─Linear: 1-4                            [32, 128]            [32, 8]              1,032                True
========================================================================================================================
Total params: 47,778,440
Trainable params: 47,778,440
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 1.53
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 0.43
Params size (MB): 191.11
Estimated Total Size (MB): 197.44
========================================================================================================================

In [21]:
main_kolesa(model_baseline_brand, train_df = train_df_brand, val_df = val_df_brand)
save_model_artifact(model_baseline_brand, 'BaseLine_FC_brand')

Epoch: 1

100%|██████████| 97/97 [00:13<00:00,  7.38it/s]

Train set: Average loss: 285470.6250, Accuracy: 13.89%
Val set: Average loss: 388377.4688, Accuracy: 12.18%

Classification report:
               precision    recall  f1-score   support

         Audi       0.08      0.10      0.09        73
          BMW       0.17      0.09      0.12        90
    Chevrolet       0.15      0.19      0.17        79
      Hyundai       0.11      0.13      0.12        85
          Kia       0.16      0.16      0.16        77
        Lexus       0.13      0.13      0.13        95
Mercedes-Benz       0.10      0.11      0.11        81
       Toyota       0.08      0.08      0.08        85

     accuracy                           0.12       665
    macro avg       0.12      0.12      0.12       665
 weighted avg       0.13      0.12      0.12       665


Epoch: 2

100%|██████████| 97/97 [00:12<00:00,  7.89it/s]

Train set: Average loss: 319479.7188, Accuracy: 13.63%
Val set: Average loss: 333627.9688, Accuracy: 11.28%

Classification report:
               precision    recall  f1-score   support

         Audi       0.07      0.07      0.07        73
          BMW       0.14      0.12      0.13        90
    Chevrolet       0.13      0.15      0.14        79
      Hyundai       0.11      0.12      0.12        85
          Kia       0.13      0.10      0.12        77
        Lexus       0.09      0.12      0.10        95
Mercedes-Benz       0.14      0.11      0.12        81
       Toyota       0.10      0.11      0.11        85

     accuracy                           0.11       665
    macro avg       0.11      0.11      0.11       665
 weighted avg       0.11      0.11      0.11       665


Epoch: 3

100%|██████████| 97/97 [00:12<00:00,  7.49it/s]

Train set: Average loss: 183402.8750, Accuracy: 15.53%
Val set: Average loss: 283816.7188, Accuracy: 13.83%

Classification report:
               precision    recall  f1-score   support

         Audi       0.10      0.10      0.10        73
          BMW       0.13      0.11      0.12        90
    Chevrolet       0.14      0.15      0.14        79
      Hyundai       0.13      0.12      0.12        85
          Kia       0.19      0.18      0.19        77
        Lexus       0.12      0.16      0.14        95
Mercedes-Benz       0.16      0.15      0.15        81
       Toyota       0.15      0.14      0.14        85

     accuracy                           0.14       665
    macro avg       0.14      0.14      0.14       665
 weighted avg       0.14      0.14      0.14       665


Epoch: 4

100%|██████████| 97/97 [00:12<00:00,  7.95it/s]

Train set: Average loss: 216754.2656, Accuracy: 16.56%
Val set: Average loss: 251771.6094, Accuracy: 11.58%

Classification report:
               precision    recall  f1-score   support

         Audi       0.09      0.08      0.09        73
          BMW       0.14      0.10      0.12        90
    Chevrolet       0.09      0.11      0.10        79
      Hyundai       0.05      0.04      0.04        85
          Kia       0.17      0.19      0.18        77
        Lexus       0.12      0.17      0.14        95
Mercedes-Benz       0.14      0.12      0.13        81
       Toyota       0.10      0.11      0.10        85

     accuracy                           0.12       665
    macro avg       0.11      0.12      0.11       665
 weighted avg       0.11      0.12      0.11       665


Epoch: 5

100%|██████████| 97/97 [00:12<00:00,  8.00it/s]

Train set: Average loss: 173704.8125, Accuracy: 17.14%
Val set: Average loss: 220074.8281, Accuracy: 12.18%

Classification report:
               precision    recall  f1-score   support

         Audi       0.08      0.08      0.08        73
          BMW       0.19      0.12      0.15        90
    Chevrolet       0.12      0.15      0.13        79
      Hyundai       0.05      0.05      0.05        85
          Kia       0.19      0.18      0.19        77
        Lexus       0.12      0.15      0.13        95
Mercedes-Benz       0.14      0.12      0.13        81
       Toyota       0.13      0.12      0.12        85

     accuracy                           0.12       665
    macro avg       0.13      0.12      0.12       665
 weighted avg       0.13      0.12      0.12       665


Epoch: 6

100%|██████████| 97/97 [00:12<00:00,  7.87it/s]

Train set: Average loss: 98674.2891, Accuracy: 17.98%
Val set: Average loss: 188636.0625, Accuracy: 12.33%

Classification report:
               precision    recall  f1-score   support

         Audi       0.08      0.08      0.08        73
          BMW       0.13      0.10      0.11        90
    Chevrolet       0.08      0.09      0.09        79
      Hyundai       0.07      0.07      0.07        85
          Kia       0.15      0.13      0.14        77
        Lexus       0.12      0.16      0.14        95
Mercedes-Benz       0.20      0.16      0.18        81
       Toyota       0.16      0.19      0.17        85

     accuracy                           0.12       665
    macro avg       0.12      0.12      0.12       665
 weighted avg       0.13      0.12      0.12       665


Epoch: 7

100%|██████████| 97/97 [00:12<00:00,  7.94it/s]

Train set: Average loss: 81279.3203, Accuracy: 19.05%
Val set: Average loss: 165904.5781, Accuracy: 13.83%

Classification report:
               precision    recall  f1-score   support

         Audi       0.10      0.10      0.10        73
          BMW       0.17      0.13      0.15        90
    Chevrolet       0.17      0.18      0.17        79
      Hyundai       0.06      0.06      0.06        85
          Kia       0.16      0.13      0.14        77
        Lexus       0.15      0.18      0.16        95
Mercedes-Benz       0.16      0.17      0.17        81
       Toyota       0.14      0.15      0.14        85

     accuracy                           0.14       665
    macro avg       0.14      0.14      0.14       665
 weighted avg       0.14      0.14      0.14       665


Epoch: 8

100%|██████████| 97/97 [00:12<00:00,  7.95it/s]

Train set: Average loss: 75338.2891, Accuracy: 17.82%
Val set: Average loss: 143131.1406, Accuracy: 12.93%

Classification report:
               precision    recall  f1-score   support

         Audi       0.09      0.08      0.08        73
          BMW       0.15      0.12      0.13        90
    Chevrolet       0.15      0.18      0.16        79
      Hyundai       0.06      0.05      0.05        85
          Kia       0.12      0.12      0.12        77
        Lexus       0.14      0.17      0.15        95
Mercedes-Benz       0.14      0.14      0.14        81
       Toyota       0.16      0.18      0.17        85

     accuracy                           0.13       665
    macro avg       0.13      0.13      0.13       665
 weighted avg       0.13      0.13      0.13       665


Epoch: 9

100%|██████████| 97/97 [00:12<00:00,  7.97it/s]

Train set: Average loss: 46430.6680, Accuracy: 16.89%
Val set: Average loss: 120568.9688, Accuracy: 14.14%

Classification report:
               precision    recall  f1-score   support

         Audi       0.09      0.08      0.09        73
          BMW       0.15      0.16      0.15        90
    Chevrolet       0.17      0.22      0.19        79
      Hyundai       0.07      0.06      0.06        85
          Kia       0.16      0.16      0.16        77
        Lexus       0.17      0.19      0.18        95
Mercedes-Benz       0.18      0.15      0.16        81
       Toyota       0.11      0.12      0.11        85

     accuracy                           0.14       665
    macro avg       0.14      0.14      0.14       665
 weighted avg       0.14      0.14      0.14       665


Epoch: 10

100%|██████████| 97/97 [00:12<00:00,  7.98it/s]

Train set: Average loss: 16634.3750, Accuracy: 17.24%
Val set: Average loss: 97859.7031, Accuracy: 14.14%

Classification report:
               precision    recall  f1-score   support

         Audi       0.09      0.10      0.09        73
          BMW       0.14      0.11      0.13        90
    Chevrolet       0.17      0.16      0.17        79
      Hyundai       0.10      0.09      0.10        85
          Kia       0.18      0.14      0.16        77
        Lexus       0.18      0.20      0.19        95
Mercedes-Benz       0.16      0.12      0.14        81
       Toyota       0.12      0.19      0.14        85

     accuracy                           0.14       665
    macro avg       0.14      0.14      0.14       665
 weighted avg       0.14      0.14      0.14       665

Training is ended!
[OK] модель сохранена: ../data/models/BaseLine_FC_brand.pt

Модель сильно переобучилась. Посмотрим далее сверточную сеть

## Простой CNN

In [22]:
class CNN_Net(nn.Module):
    def __init__(self, task='body_type'):
        super(CNN_Net, self).__init__()

        self.task = task

        self.conv1 = torch.nn.Conv2d(3, 16, 3, padding=1)
        self.act1  = torch.nn.ReLU()
        self.pool1 = torch.nn.MaxPool2d(2, 2) # 48 80

        self.conv2 = torch.nn.Conv2d(16, 32, 3, padding=1)
        self.act2  = torch.nn.ReLU()
        self.pool2 = torch.nn.MaxPool2d(2, 2) # 24 40

        self.conv3 = torch.nn.Conv2d(32, 64, 3, padding=1)
        self.act3  = torch.nn.ReLU()
        self.pool3 = torch.nn.MaxPool2d(2, 2) # 12 20

        self.fc1   = torch.nn.Linear(12 * 20 * 64, 256)
        self.act4  = torch.nn.Tanh()

        self.fc2   = torch.nn.Linear(256, 64)
        self.act5  = torch.nn.Tanh()
        
        if task == 'body_type':
            self.fc3   = torch.nn.Linear(64, 2)
        elif task == 'brand':
            self.fc3   = torch.nn.Linear(64, 8)

    def forward(self, x):
        x = self.conv1(x)
        x = self.act1(x)
        x = self.pool1(x)

        x = self.conv2(x)
        x = self.act2(x)
        x = self.pool2(x)

        x = self.conv3(x)
        x = self.act3(x)
        x = self.pool3(x)

        x = x.view(x.size(0), x.size(1) * x.size(2) * x.size(3))
        x = self.fc1(x)
        x = self.act4(x)
        x = self.fc2(x)
        x = self.act5(x)
        x = self.fc3(x)

        return x

#### Задача на тип кузова

In [23]:
CFG.classes = all_body_types

model_cnn_1_bt = CNN_Net()

In [24]:
summary(model=model_cnn_1_bt,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
CNN_Net                                  [32, 3, 96, 160]     [32, 2]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 16, 96, 160]    448                  True
├─ReLU: 1-2                              [32, 16, 96, 160]    [32, 16, 96, 160]    --                   --
├─MaxPool2d: 1-3                         [32, 16, 96, 160]    [32, 16, 48, 80]     --                   --
├─Conv2d: 1-4                            [32, 16, 48, 80]     [32, 32, 48, 80]     4,640                True
├─ReLU: 1-5                              [32, 32, 48, 80]     [32, 32, 48, 80]     --                   --
├─MaxPool2d: 1-6                         [32, 32, 48, 80]     [32, 32, 24, 40]     --                   --
├─Conv2d: 1-7                            [32, 32, 24, 40]     [32, 64, 24, 40]     18,496               True
├─ReLU: 1-8                              [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─MaxPool2d: 1-9                         [32, 64, 24, 40]     [32, 64, 12, 20]     --                   --
├─Linear: 1-10                           [32, 15360]          [32, 256]            3,932,416            True
├─Tanh: 1-11                             [32, 256]            [32, 256]            --                   --
├─Linear: 1-12                           [32, 256]            [32, 64]             16,448               True
├─Tanh: 1-13                             [32, 64]             [32, 64]             --                   --
├─Linear: 1-14                           [32, 64]             [32, 2]              130                  True
========================================================================================================================
Total params: 3,972,578
Trainable params: 3,972,578
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 1.48
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 110.18
Params size (MB): 15.89
Estimated Total Size (MB): 131.97
========================================================================================================================

In [25]:
main_kolesa(model_cnn_1_bt, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_cnn_1_bt, 'Base_CNN_body_type')

Epoch: 1

100%|██████████| 97/97 [00:12<00:00,  7.56it/s]

Train set: Average loss: 0.7569, Accuracy: 62.20%
Val set: Average loss: 0.6640, Accuracy: 63.61%

Classification report:
              precision    recall  f1-score   support

       sedan       0.63      1.00      0.78       418
         SUV       1.00      0.02      0.04       247

    accuracy                           0.64       665
   macro avg       0.82      0.51      0.41       665
weighted avg       0.77      0.64      0.50       665


Epoch: 2

100%|██████████| 97/97 [00:13<00:00,  7.45it/s]

Train set: Average loss: 0.6975, Accuracy: 63.26%
Val set: Average loss: 0.6970, Accuracy: 56.69%

Classification report:
              precision    recall  f1-score   support

       sedan       0.74      0.48      0.58       418
         SUV       0.45      0.71      0.55       247

    accuracy                           0.57       665
   macro avg       0.59      0.60      0.57       665
weighted avg       0.63      0.57      0.57       665


Epoch: 3

100%|██████████| 97/97 [00:13<00:00,  7.45it/s]

Train set: Average loss: 0.6562, Accuracy: 64.20%
Val set: Average loss: 0.6519, Accuracy: 63.31%

Classification report:
              precision    recall  f1-score   support

       sedan       0.74      0.64      0.69       418
         SUV       0.50      0.62      0.55       247

    accuracy                           0.63       665
   macro avg       0.62      0.63      0.62       665
weighted avg       0.65      0.63      0.64       665


Epoch: 4

100%|██████████| 97/97 [00:12<00:00,  7.66it/s]

Train set: Average loss: 0.6659, Accuracy: 66.07%
Val set: Average loss: 0.6544, Accuracy: 63.76%

Classification report:
              precision    recall  f1-score   support

       sedan       0.76      0.61      0.68       418
         SUV       0.51      0.68      0.58       247

    accuracy                           0.64       665
   macro avg       0.64      0.65      0.63       665
weighted avg       0.67      0.64      0.64       665


Epoch: 5

100%|██████████| 97/97 [00:12<00:00,  7.95it/s]

Train set: Average loss: 0.6540, Accuracy: 66.65%
Val set: Average loss: 0.6371, Accuracy: 65.41%

Classification report:
              precision    recall  f1-score   support

       sedan       0.76      0.66      0.71       418
         SUV       0.53      0.64      0.58       247

    accuracy                           0.65       665
   macro avg       0.64      0.65      0.64       665
weighted avg       0.67      0.65      0.66       665


Epoch: 6

100%|██████████| 97/97 [00:12<00:00,  7.96it/s]

Train set: Average loss: 0.6345, Accuracy: 68.10%
Val set: Average loss: 0.6591, Accuracy: 64.66%

Classification report:
              precision    recall  f1-score   support

       sedan       0.75      0.65      0.70       418
         SUV       0.52      0.64      0.57       247

    accuracy                           0.65       665
   macro avg       0.64      0.64      0.64       665
weighted avg       0.67      0.65      0.65       665


Epoch: 7

100%|██████████| 97/97 [00:12<00:00,  7.94it/s]

Train set: Average loss: 0.5790, Accuracy: 69.03%
Val set: Average loss: 0.6571, Accuracy: 65.86%

Classification report:
              precision    recall  f1-score   support

       sedan       0.78      0.64      0.70       418
         SUV       0.53      0.69      0.60       247

    accuracy                           0.66       665
   macro avg       0.65      0.66      0.65       665
weighted avg       0.69      0.66      0.66       665


Epoch: 8

100%|██████████| 97/97 [00:12<00:00,  7.95it/s]

Train set: Average loss: 0.6542, Accuracy: 70.51%
Val set: Average loss: 0.6426, Accuracy: 65.56%

Classification report:
              precision    recall  f1-score   support

       sedan       0.74      0.70      0.72       418
         SUV       0.53      0.58      0.56       247

    accuracy                           0.66       665
   macro avg       0.64      0.64      0.64       665
weighted avg       0.66      0.66      0.66       665


Epoch: 9

100%|██████████| 97/97 [00:13<00:00,  7.25it/s]

Train set: Average loss: 0.5823, Accuracy: 71.87%
Val set: Average loss: 0.6666, Accuracy: 64.06%

Classification report:
              precision    recall  f1-score   support

       sedan       0.75      0.65      0.69       418
         SUV       0.51      0.63      0.56       247

    accuracy                           0.64       665
   macro avg       0.63      0.64      0.63       665
weighted avg       0.66      0.64      0.65       665


Epoch: 10

100%|██████████| 97/97 [00:13<00:00,  7.39it/s]

Train set: Average loss: 0.6147, Accuracy: 72.09%
Val set: Average loss: 0.6598, Accuracy: 66.02%

Classification report:
              precision    recall  f1-score   support

       sedan       0.77      0.66      0.71       418
         SUV       0.53      0.66      0.59       247

    accuracy                           0.66       665
   macro avg       0.65      0.66      0.65       665
weighted avg       0.68      0.66      0.67       665

Training is ended!
[OK] модель сохранена: ../data/models/Base_CNN_body_type.pt

#### Задача на определение марки

In [26]:
CFG.classes = all_brands

model_cnn_1_brand = CNN_Net(task='brand')

In [27]:
summary(model=model_cnn_1_brand,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
CNN_Net                                  [32, 3, 96, 160]     [32, 8]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 16, 96, 160]    448                  True
├─ReLU: 1-2                              [32, 16, 96, 160]    [32, 16, 96, 160]    --                   --
├─MaxPool2d: 1-3                         [32, 16, 96, 160]    [32, 16, 48, 80]     --                   --
├─Conv2d: 1-4                            [32, 16, 48, 80]     [32, 32, 48, 80]     4,640                True
├─ReLU: 1-5                              [32, 32, 48, 80]     [32, 32, 48, 80]     --                   --
├─MaxPool2d: 1-6                         [32, 32, 48, 80]     [32, 32, 24, 40]     --                   --
├─Conv2d: 1-7                            [32, 32, 24, 40]     [32, 64, 24, 40]     18,496               True
├─ReLU: 1-8                              [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─MaxPool2d: 1-9                         [32, 64, 24, 40]     [32, 64, 12, 20]     --                   --
├─Linear: 1-10                           [32, 15360]          [32, 256]            3,932,416            True
├─Tanh: 1-11                             [32, 256]            [32, 256]            --                   --
├─Linear: 1-12                           [32, 256]            [32, 64]             16,448               True
├─Tanh: 1-13                             [32, 64]             [32, 64]             --                   --
├─Linear: 1-14                           [32, 64]             [32, 8]              520                  True
========================================================================================================================
Total params: 3,972,968
Trainable params: 3,972,968
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 1.48
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 110.18
Params size (MB): 15.89
Estimated Total Size (MB): 131.97
========================================================================================================================

In [28]:
main_kolesa(model_cnn_1_brand, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_cnn_1_brand, 'Base_CNN_brand')

Epoch: 1

100%|██████████| 97/97 [00:13<00:00,  7.23it/s]

Train set: Average loss: 2.0729, Accuracy: 14.24%

/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Val set: Average loss: 2.0768, Accuracy: 14.14%

Classification report:
               precision    recall  f1-score   support

         Audi       0.00      0.00      0.00        73
          BMW       0.11      0.33      0.17        90
    Chevrolet       0.21      0.23      0.22        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.23      0.17      0.20        77
        Lexus       0.17      0.24      0.20        95
Mercedes-Benz       0.04      0.01      0.02        81
       Toyota       0.09      0.11      0.10        85

     accuracy                           0.14       665
    macro avg       0.11      0.14      0.11       665
 weighted avg       0.11      0.14      0.11       665


Epoch: 2

100%|██████████| 97/97 [00:12<00:00,  7.80it/s]

Train set: Average loss: 2.0585, Accuracy: 17.31%

/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Val set: Average loss: 2.0692, Accuracy: 16.09%

Classification report:
               precision    recall  f1-score   support

         Audi       0.00      0.00      0.00        73
          BMW       0.14      0.58      0.22        90
    Chevrolet       0.32      0.13      0.18        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.22      0.13      0.16        77
        Lexus       0.15      0.08      0.11        95
Mercedes-Benz       0.17      0.22      0.19        81
       Toyota       0.20      0.11      0.14        85

     accuracy                           0.16       665
    macro avg       0.15      0.16      0.13       665
 weighted avg       0.15      0.16      0.13       665


Epoch: 3

100%|██████████| 97/97 [00:12<00:00,  7.94it/s]

Train set: Average loss: 2.0210, Accuracy: 18.82%

/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Val set: Average loss: 2.0707, Accuracy: 15.94%

Classification report:
               precision    recall  f1-score   support

         Audi       0.40      0.03      0.05        73
          BMW       0.13      0.60      0.22        90
    Chevrolet       0.29      0.09      0.14        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.23      0.17      0.20        77
        Lexus       0.26      0.11      0.15        95
Mercedes-Benz       0.15      0.16      0.15        81
       Toyota       0.14      0.08      0.10        85

     accuracy                           0.16       665
    macro avg       0.20      0.15      0.13       665
 weighted avg       0.20      0.16      0.13       665


Epoch: 4

100%|██████████| 97/97 [00:12<00:00,  7.92it/s]

Train set: Average loss: 2.0166, Accuracy: 21.04%
Val set: Average loss: 2.0714, Accuracy: 16.84%

Classification report:
               precision    recall  f1-score   support

         Audi       0.25      0.03      0.05        73
          BMW       0.15      0.49      0.23        90
    Chevrolet       0.31      0.13      0.18        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.21      0.17      0.19        77
        Lexus       0.20      0.11      0.14        95
Mercedes-Benz       0.16      0.30      0.21        81
       Toyota       0.15      0.11      0.12        85

     accuracy                           0.17       665
    macro avg       0.18      0.16      0.14       665
 weighted avg       0.18      0.17      0.14       665


Epoch: 5

100%|██████████| 97/97 [00:12<00:00,  7.48it/s]

Train set: Average loss: 1.9941, Accuracy: 22.08%
Val set: Average loss: 2.0593, Accuracy: 16.99%

Classification report:
               precision    recall  f1-score   support

         Audi       0.17      0.11      0.13        73
          BMW       0.14      0.41      0.21        90
    Chevrolet       0.45      0.18      0.25        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.16      0.21      0.18        77
        Lexus       0.18      0.07      0.10        95
Mercedes-Benz       0.17      0.25      0.20        81
       Toyota       0.15      0.13      0.14        85

     accuracy                           0.17       665
    macro avg       0.18      0.17      0.15       665
 weighted avg       0.18      0.17      0.15       665


Epoch: 6

100%|██████████| 97/97 [00:13<00:00,  7.43it/s]

Train set: Average loss: 1.9233, Accuracy: 24.94%
Val set: Average loss: 2.0716, Accuracy: 17.14%

Classification report:
               precision    recall  f1-score   support

         Audi       0.11      0.08      0.09        73
          BMW       0.16      0.36      0.22        90
    Chevrolet       0.47      0.10      0.17        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.18      0.19      0.19        77
        Lexus       0.21      0.14      0.17        95
Mercedes-Benz       0.17      0.36      0.23        81
       Toyota       0.15      0.13      0.14        85

     accuracy                           0.17       665
    macro avg       0.18      0.17      0.15       665
 weighted avg       0.18      0.17      0.15       665


Epoch: 7

100%|██████████| 97/97 [00:12<00:00,  7.52it/s]

Train set: Average loss: 1.8667, Accuracy: 25.91%

/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/alexander/Documents/Study/СМАДИМО/gp5/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Val set: Average loss: 2.1014, Accuracy: 17.44%

Classification report:
               precision    recall  f1-score   support

         Audi       0.13      0.14      0.13        73
          BMW       0.17      0.26      0.21        90
    Chevrolet       0.39      0.18      0.24        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.18      0.14      0.16        77
        Lexus       0.17      0.17      0.17        95
Mercedes-Benz       0.15      0.40      0.22        81
       Toyota       0.19      0.12      0.15        85

     accuracy                           0.17       665
    macro avg       0.17      0.17      0.16       665
 weighted avg       0.17      0.17      0.16       665


Epoch: 8

100%|██████████| 97/97 [00:12<00:00,  7.57it/s]

Train set: Average loss: 1.8840, Accuracy: 28.07%
Val set: Average loss: 2.1148, Accuracy: 19.40%

Classification report:
               precision    recall  f1-score   support

         Audi       0.15      0.14      0.14        73
          BMW       0.21      0.39      0.27        90
    Chevrolet       0.35      0.18      0.24        79
      Hyundai       0.12      0.01      0.02        85
          Kia       0.25      0.13      0.17        77
        Lexus       0.23      0.08      0.12        95
Mercedes-Benz       0.18      0.44      0.26        81
       Toyota       0.14      0.18      0.16        85

     accuracy                           0.19       665
    macro avg       0.20      0.19      0.17       665
 weighted avg       0.20      0.19      0.17       665


Epoch: 9

100%|██████████| 97/97 [00:12<00:00,  7.52it/s]

Train set: Average loss: 1.7233, Accuracy: 31.20%
Val set: Average loss: 2.1486, Accuracy: 18.20%

Classification report:
               precision    recall  f1-score   support

         Audi       0.12      0.12      0.12        73
          BMW       0.22      0.39      0.28        90
    Chevrolet       0.36      0.19      0.25        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.23      0.17      0.20        77
        Lexus       0.17      0.11      0.13        95
Mercedes-Benz       0.15      0.33      0.20        81
       Toyota       0.14      0.14      0.14        85

     accuracy                           0.18       665
    macro avg       0.17      0.18      0.16       665
 weighted avg       0.17      0.18      0.16       665


Epoch: 10

100%|██████████| 97/97 [00:12<00:00,  7.70it/s]

Train set: Average loss: 1.5459, Accuracy: 33.23%
Val set: Average loss: 2.1410, Accuracy: 19.10%

Classification report:
               precision    recall  f1-score   support

         Audi       0.17      0.22      0.19        73
          BMW       0.22      0.48      0.30        90
    Chevrolet       0.50      0.16      0.25        79
      Hyundai       0.10      0.01      0.02        85
          Kia       0.22      0.18      0.20        77
        Lexus       0.19      0.08      0.12        95
Mercedes-Benz       0.15      0.26      0.19        81
       Toyota       0.12      0.13      0.12        85

     accuracy                           0.19       665
    macro avg       0.21      0.19      0.17       665
 weighted avg       0.21      0.19      0.17       665

Training is ended!
[OK] модель сохранена: ../data/models/Base_CNN_brand.pt

Не сильно далеко ушли от FC, по крайней мере, пока качество не самое приятное

## CNN с регуляризацией

Теперь попробуем добавить регуляризацию, а именно известные нам BatchNorm и Dropout.

Также поменяем функции активации https://deepmachinelearning.ru/docs/Neural-networks/MLP/Activation-functions. В частности попробуем LeakyReLU.

И наконец добавим побольше сверточных слоев.

In [29]:
class CNNReg_Net(nn.Module):
    def __init__(self, task='body_type'):
        super(CNNReg_Net, self).__init__()

        self.task = task

        self.conv3 = torch.nn.Conv2d(3, 32, 3, padding=1)
        self.bn3   = torch.nn.BatchNorm2d(32)
        self.act3  = torch.nn.LeakyReLU()

        self.conv4 = torch.nn.Conv2d(32, 32, 3, padding=1)
        self.bn4   = torch.nn.BatchNorm2d(32)
        self.act4  = torch.nn.LeakyReLU()
        self.pool2 = torch.nn.MaxPool2d(2, 2) # 24 40

        self.conv5 = torch.nn.Conv2d(32, 64, 3, padding=1)
        self.bn5   = torch.nn.BatchNorm2d(64)
        self.act5  = torch.nn.LeakyReLU()

        self.conv6 = torch.nn.Conv2d(64, 64, 3, padding=1)
        self.bn6   = torch.nn.BatchNorm2d(64)
        self.act6  = torch.nn.LeakyReLU()
        self.pool3 = torch.nn.MaxPool2d(2, 2) # 12 20

        self.drop1 = torch.nn.Dropout2d(0.10)

        self.conv7 = torch.nn.Conv2d(64, 128, 3, padding=1)
        self.bn7   = torch.nn.BatchNorm2d(128)
        self.act7  = torch.nn.LeakyReLU()
        self.drop2 = torch.nn.Dropout2d(0.15)

        self.conv8 = torch.nn.Conv2d(128, 128, 3, padding=1)
        self.bn8   = torch.nn.BatchNorm2d(128)
        self.act8  = torch.nn.LeakyReLU()
        self.pool4 = torch.nn.MaxPool2d(2, 2)
        self.drop3 = torch.nn.Dropout2d(0.2)

        self.conv9 = torch.nn.Conv2d(128, 256, 3, padding=1)
        self.bn9   = torch.nn.BatchNorm2d(256)
        self.act9  = torch.nn.LeakyReLU()
        self.pool5 = torch.nn.MaxPool2d(2, 2)
        self.drop4 = torch.nn.Dropout2d(0.25)

        self.fc1   = torch.nn.Linear(6 * 10 * 256, 256)
        self.bn10  = torch.nn.BatchNorm1d(256)
        self.act10 = torch.nn.LeakyReLU()
        self.drop5 = torch.nn.Dropout(0.3)

        self.fc2   = torch.nn.Linear(256, 64)
        self.act11 = torch.nn.LeakyReLU()
        self.drop6 = torch.nn.Dropout(0.2)

        if task == 'body_type':
            self.fc3 = torch.nn.Linear(64, 2)
        elif task == 'brand':
            self.fc3 = torch.nn.Linear(64, 8)
            

    def forward(self, x):
        x = self.conv3(x)
        x = self.bn3(x)
        x = self.act3(x)

        x = self.conv4(x)
        x = self.bn4(x)
        x = self.act4(x)
        x = self.pool2(x)

        x = self.conv5(x)
        x = self.bn5(x)
        x = self.act5(x)

        x = self.conv6(x)
        x = self.bn6(x)
        x = self.act6(x)
        x = self.pool3(x)
        x = self.drop1(x)

        x = self.conv7(x)
        x = self.bn7(x)
        x = self.act7(x)
        x = self.drop2(x)

        x = self.conv8(x)
        x = self.bn8(x)
        x = self.act8(x)
        x = self.pool4(x)
        x = self.drop3(x)

        x = self.conv9(x)
        x = self.bn9(x)
        x = self.act9(x)
        x = self.pool5(x)
        x = self.drop4(x)

        x = x.view(x.size(0), x.size(1) * x.size(2) * x.size(3))
        x = self.fc1(x)
        x = self.bn10(x)
        x = self.act10(x)
        x = self.drop5(x)

        x = self.fc2(x)
        x = self.act11(x)
        x = self.drop6(x)

        x = self.fc3(x)

        return x

На этой модели попробуем побольше эпох

In [30]:
CFG.num_epochs = 30

#### Задача на тип кузова

In [31]:
CFG.classes = all_body_types

model_cnn_2_bt = CNNReg_Net()

In [32]:
summary(model=model_cnn_2_bt,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
CNNReg_Net                               [32, 3, 96, 160]     [32, 2]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 32, 96, 160]    896                  True
├─BatchNorm2d: 1-2                       [32, 32, 96, 160]    [32, 32, 96, 160]    64                   True
├─LeakyReLU: 1-3                         [32, 32, 96, 160]    [32, 32, 96, 160]    --                   --
├─Conv2d: 1-4                            [32, 32, 96, 160]    [32, 32, 96, 160]    9,248                True
├─BatchNorm2d: 1-5                       [32, 32, 96, 160]    [32, 32, 96, 160]    64                   True
├─LeakyReLU: 1-6                         [32, 32, 96, 160]    [32, 32, 96, 160]    --                   --
├─MaxPool2d: 1-7                         [32, 32, 96, 160]    [32, 32, 48, 80]     --                   --
├─Conv2d: 1-8                            [32, 32, 48, 80]     [32, 64, 48, 80]     18,496               True
├─BatchNorm2d: 1-9                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─LeakyReLU: 1-10                        [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─Conv2d: 1-11                           [32, 64, 48, 80]     [32, 64, 48, 80]     36,928               True
├─BatchNorm2d: 1-12                      [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─LeakyReLU: 1-13                        [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-14                        [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Dropout2d: 1-15                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Conv2d: 1-16                           [32, 64, 24, 40]     [32, 128, 24, 40]    73,856               True
├─BatchNorm2d: 1-17                      [32, 128, 24, 40]    [32, 128, 24, 40]    256                  True
├─LeakyReLU: 1-18                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─Dropout2d: 1-19                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─Conv2d: 1-20                           [32, 128, 24, 40]    [32, 128, 24, 40]    147,584              True
├─BatchNorm2d: 1-21                      [32, 128, 24, 40]    [32, 128, 24, 40]    256                  True
├─LeakyReLU: 1-22                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─MaxPool2d: 1-23                        [32, 128, 24, 40]    [32, 128, 12, 20]    --                   --
├─Dropout2d: 1-24                        [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Conv2d: 1-25                           [32, 128, 12, 20]    [32, 256, 12, 20]    295,168              True
├─BatchNorm2d: 1-26                      [32, 256, 12, 20]    [32, 256, 12, 20]    512                  True
├─LeakyReLU: 1-27                        [32, 256, 12, 20]    [32, 256, 12, 20]    --                   --
├─MaxPool2d: 1-28                        [32, 256, 12, 20]    [32, 256, 6, 10]     --                   --
├─Dropout2d: 1-29                        [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Linear: 1-30                           [32, 15360]          [32, 256]            3,932,416            True
├─BatchNorm1d: 1-31                      [32, 256]            [32, 256]            512                  True
├─LeakyReLU: 1-32                        [32, 256]            [32, 256]            --                   --
├─Dropout: 1-33                          [32, 256]            [32, 256]            --                   --
├─Linear: 1-34                           [32, 256]            [32, 64]             16,448               True
├─LeakyReLU: 1-35                        [32, 64]             [32, 64]             --                   --
├─Dropout: 1-36                          [32, 64]             [32, 64]             --                   --
├─Linear: 1-37                           [32, 64]             [32, 2]              130                  True
========================================================================================================================
Total params: 4,533,090
Trainable params: 4,533,090
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 20.99
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 912.41
Params size (MB): 18.13
Estimated Total Size (MB): 936.44
========================================================================================================================

In [33]:
main_kolesa(model_cnn_2_bt, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_cnn_2_bt, 'Reg_CNN_body_type')

Epoch: 1

100%|██████████| 97/97 [00:15<00:00,  6.35it/s]

Train set: Average loss: 0.8110, Accuracy: 61.26%
Val set: Average loss: 0.6159, Accuracy: 65.41%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.92      0.77       418
         SUV       0.60      0.21      0.31       247

    accuracy                           0.65       665
   macro avg       0.63      0.56      0.54       665
weighted avg       0.64      0.65      0.60       665


Epoch: 2

100%|██████████| 97/97 [00:15<00:00,  6.26it/s]

Train set: Average loss: 0.7646, Accuracy: 64.00%
Val set: Average loss: 0.6254, Accuracy: 66.02%

Classification report:
              precision    recall  f1-score   support

       sedan       0.67      0.92      0.77       418
         SUV       0.62      0.21      0.32       247

    accuracy                           0.66       665
   macro avg       0.64      0.57      0.55       665
weighted avg       0.65      0.66      0.60       665


Epoch: 3

100%|██████████| 97/97 [00:15<00:00,  6.26it/s]

Train set: Average loss: 0.7301, Accuracy: 65.36%
Val set: Average loss: 0.6120, Accuracy: 66.92%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.98      0.79       418
         SUV       0.81      0.14      0.24       247

    accuracy                           0.67       665
   macro avg       0.74      0.56      0.51       665
weighted avg       0.72      0.67      0.59       665


Epoch: 4

100%|██████████| 97/97 [00:15<00:00,  6.37it/s]

Train set: Average loss: 0.7951, Accuracy: 66.45%
Val set: Average loss: 0.5989, Accuracy: 66.32%

Classification report:
              precision    recall  f1-score   support

       sedan       0.76      0.67      0.72       418
         SUV       0.54      0.64      0.59       247

    accuracy                           0.66       665
   macro avg       0.65      0.66      0.65       665
weighted avg       0.68      0.66      0.67       665


Epoch: 5

100%|██████████| 97/97 [00:15<00:00,  6.21it/s]

Train set: Average loss: 0.7300, Accuracy: 67.00%
Val set: Average loss: 0.5757, Accuracy: 69.62%

Classification report:
              precision    recall  f1-score   support

       sedan       0.73      0.81      0.77       418
         SUV       0.61      0.51      0.55       247

    accuracy                           0.70       665
   macro avg       0.67      0.66      0.66       665
weighted avg       0.69      0.70      0.69       665


Epoch: 6

100%|██████████| 97/97 [00:15<00:00,  6.31it/s]

Train set: Average loss: 0.7523, Accuracy: 68.19%
Val set: Average loss: 0.5755, Accuracy: 70.08%

Classification report:
              precision    recall  f1-score   support

       sedan       0.76      0.76      0.76       418
         SUV       0.60      0.60      0.60       247

    accuracy                           0.70       665
   macro avg       0.68      0.68      0.68       665
weighted avg       0.70      0.70      0.70       665


Epoch: 7

100%|██████████| 97/97 [00:14<00:00,  6.54it/s]

Train set: Average loss: 0.6658, Accuracy: 70.54%
Val set: Average loss: 0.5670, Accuracy: 71.43%

Classification report:
              precision    recall  f1-score   support

       sedan       0.72      0.90      0.80       418
         SUV       0.70      0.40      0.51       247

    accuracy                           0.71       665
   macro avg       0.71      0.65      0.66       665
weighted avg       0.71      0.71      0.69       665


Epoch: 8

100%|██████████| 97/97 [00:14<00:00,  6.59it/s]

Train set: Average loss: 0.6785, Accuracy: 70.25%
Val set: Average loss: 0.6615, Accuracy: 64.06%

Classification report:
              precision    recall  f1-score   support

       sedan       0.83      0.54      0.65       418
         SUV       0.51      0.82      0.63       247

    accuracy                           0.64       665
   macro avg       0.67      0.68      0.64       665
weighted avg       0.71      0.64      0.64       665


Epoch: 9

100%|██████████| 97/97 [00:14<00:00,  6.59it/s]

Train set: Average loss: 0.7227, Accuracy: 71.80%
Val set: Average loss: 0.7133, Accuracy: 60.75%

Classification report:
              precision    recall  f1-score   support

       sedan       0.83      0.47      0.60       418
         SUV       0.48      0.83      0.61       247

    accuracy                           0.61       665
   macro avg       0.66      0.65      0.61       665
weighted avg       0.70      0.61      0.61       665


Epoch: 10

100%|██████████| 97/97 [00:14<00:00,  6.60it/s]

Train set: Average loss: 0.7334, Accuracy: 72.25%
Val set: Average loss: 0.6081, Accuracy: 69.17%

Classification report:
              precision    recall  f1-score   support

       sedan       0.83      0.65      0.72       418
         SUV       0.56      0.77      0.65       247

    accuracy                           0.69       665
   macro avg       0.69      0.71      0.69       665
weighted avg       0.73      0.69      0.70       665


Epoch: 11

100%|██████████| 97/97 [00:14<00:00,  6.59it/s]

Train set: Average loss: 0.6852, Accuracy: 73.54%
Val set: Average loss: 0.5504, Accuracy: 71.43%

Classification report:
              precision    recall  f1-score   support

       sedan       0.83      0.69      0.75       418
         SUV       0.59      0.75      0.66       247

    accuracy                           0.71       665
   macro avg       0.71      0.72      0.71       665
weighted avg       0.74      0.71      0.72       665


Epoch: 12

100%|██████████| 97/97 [00:14<00:00,  6.76it/s]

Train set: Average loss: 0.6779, Accuracy: 74.51%
Val set: Average loss: 0.5670, Accuracy: 72.48%

Classification report:
              precision    recall  f1-score   support

       sedan       0.81      0.74      0.77       418
         SUV       0.61      0.70      0.65       247

    accuracy                           0.72       665
   macro avg       0.71      0.72      0.71       665
weighted avg       0.73      0.72      0.73       665


Epoch: 13

100%|██████████| 97/97 [00:14<00:00,  6.84it/s]

Train set: Average loss: 0.6307, Accuracy: 75.64%
Val set: Average loss: 0.5604, Accuracy: 73.68%

Classification report:
              precision    recall  f1-score   support

       sedan       0.83      0.74      0.78       418
         SUV       0.62      0.74      0.68       247

    accuracy                           0.74       665
   macro avg       0.72      0.74      0.73       665
weighted avg       0.75      0.74      0.74       665


Epoch: 14

100%|██████████| 97/97 [00:14<00:00,  6.59it/s]

Train set: Average loss: 0.7381, Accuracy: 76.70%
Val set: Average loss: 0.5326, Accuracy: 72.18%

Classification report:
              precision    recall  f1-score   support

       sedan       0.81      0.73      0.77       418
         SUV       0.61      0.70      0.65       247

    accuracy                           0.72       665
   macro avg       0.71      0.72      0.71       665
weighted avg       0.73      0.72      0.73       665


Epoch: 15

100%|██████████| 97/97 [00:15<00:00,  6.30it/s]

Train set: Average loss: 0.6036, Accuracy: 77.09%
Val set: Average loss: 0.7023, Accuracy: 65.11%

Classification report:
              precision    recall  f1-score   support

       sedan       0.84      0.55      0.66       418
         SUV       0.52      0.82      0.64       247

    accuracy                           0.65       665
   macro avg       0.68      0.69      0.65       665
weighted avg       0.72      0.65      0.65       665


Epoch: 16

100%|██████████| 97/97 [00:15<00:00,  6.30it/s]

Train set: Average loss: 0.6424, Accuracy: 77.22%
Val set: Average loss: 0.5355, Accuracy: 73.38%

Classification report:
              precision    recall  f1-score   support

       sedan       0.82      0.73      0.78       418
         SUV       0.62      0.74      0.67       247

    accuracy                           0.73       665
   macro avg       0.72      0.73      0.72       665
weighted avg       0.75      0.73      0.74       665


Epoch: 17

100%|██████████| 97/97 [00:15<00:00,  6.30it/s]

Train set: Average loss: 0.6952, Accuracy: 79.50%
Val set: Average loss: 0.6388, Accuracy: 68.72%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.61      0.71       418
         SUV       0.55      0.83      0.66       247

    accuracy                           0.69       665
   macro avg       0.70      0.72      0.69       665
weighted avg       0.74      0.69      0.69       665


Epoch: 18

100%|██████████| 97/97 [00:15<00:00,  6.21it/s]

Train set: Average loss: 0.6495, Accuracy: 79.60%
Val set: Average loss: 0.6096, Accuracy: 69.47%

Classification report:
              precision    recall  f1-score   support

       sedan       0.84      0.64      0.72       418
         SUV       0.56      0.79      0.66       247

    accuracy                           0.69       665
   macro avg       0.70      0.71      0.69       665
weighted avg       0.74      0.69      0.70       665


Epoch: 19

100%|██████████| 97/97 [00:15<00:00,  6.28it/s]

Train set: Average loss: 0.6493, Accuracy: 79.44%
Val set: Average loss: 0.5809, Accuracy: 72.48%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.68      0.76       418
         SUV       0.60      0.79      0.68       247

    accuracy                           0.72       665
   macro avg       0.72      0.74      0.72       665
weighted avg       0.76      0.72      0.73       665


Epoch: 20

100%|██████████| 97/97 [00:15<00:00,  6.44it/s]

Train set: Average loss: 0.5669, Accuracy: 80.83%
Val set: Average loss: 0.6084, Accuracy: 71.43%

Classification report:
              precision    recall  f1-score   support

       sedan       0.86      0.66      0.74       418
         SUV       0.58      0.81      0.68       247

    accuracy                           0.71       665
   macro avg       0.72      0.73      0.71       665
weighted avg       0.75      0.71      0.72       665


Epoch: 21

100%|██████████| 97/97 [00:15<00:00,  6.26it/s]

Train set: Average loss: 0.5156, Accuracy: 80.92%
Val set: Average loss: 0.5362, Accuracy: 73.08%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.70      0.76       418
         SUV       0.61      0.79      0.69       247

    accuracy                           0.73       665
   macro avg       0.73      0.74      0.73       665
weighted avg       0.76      0.73      0.74       665


Epoch: 22

100%|██████████| 97/97 [00:15<00:00,  6.33it/s]

Train set: Average loss: 0.5660, Accuracy: 80.99%
Val set: Average loss: 0.6138, Accuracy: 69.02%

Classification report:
              precision    recall  f1-score   support

       sedan       0.86      0.61      0.71       418
         SUV       0.56      0.83      0.66       247

    accuracy                           0.69       665
   macro avg       0.71      0.72      0.69       665
weighted avg       0.74      0.69      0.69       665


Epoch: 23

100%|██████████| 97/97 [00:15<00:00,  6.22it/s]

Train set: Average loss: 0.4351, Accuracy: 82.40%
Val set: Average loss: 0.6304, Accuracy: 68.87%

Classification report:
              precision    recall  f1-score   support

       sedan       0.84      0.62      0.71       418
         SUV       0.56      0.81      0.66       247

    accuracy                           0.69       665
   macro avg       0.70      0.71      0.69       665
weighted avg       0.74      0.69      0.69       665


Epoch: 24

100%|██████████| 97/97 [00:15<00:00,  6.44it/s]

Train set: Average loss: 0.6455, Accuracy: 82.28%
Val set: Average loss: 0.8879, Accuracy: 59.40%

Classification report:
              precision    recall  f1-score   support

       sedan       0.87      0.42      0.56       418
         SUV       0.48      0.89      0.62       247

    accuracy                           0.59       665
   macro avg       0.67      0.65      0.59       665
weighted avg       0.72      0.59      0.59       665


Epoch: 25

100%|██████████| 97/97 [00:14<00:00,  6.50it/s]

Train set: Average loss: 0.5601, Accuracy: 82.21%
Val set: Average loss: 0.7502, Accuracy: 67.22%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.58      0.69       418
         SUV       0.54      0.82      0.65       247

    accuracy                           0.67       665
   macro avg       0.69      0.70      0.67       665
weighted avg       0.73      0.67      0.68       665


Epoch: 26

100%|██████████| 97/97 [00:14<00:00,  6.48it/s]

Train set: Average loss: 0.5743, Accuracy: 83.31%
Val set: Average loss: 0.6457, Accuracy: 69.62%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.63      0.72       418
         SUV       0.56      0.81      0.66       247

    accuracy                           0.70       665
   macro avg       0.70      0.72      0.69       665
weighted avg       0.74      0.70      0.70       665


Epoch: 27

100%|██████████| 97/97 [00:14<00:00,  6.56it/s]

Train set: Average loss: 0.5663, Accuracy: 84.43%
Val set: Average loss: 0.6779, Accuracy: 68.12%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.60      0.70       418
         SUV       0.55      0.83      0.66       247

    accuracy                           0.68       665
   macro avg       0.70      0.71      0.68       665
weighted avg       0.74      0.68      0.69       665


Epoch: 28

100%|██████████| 97/97 [00:15<00:00,  6.25it/s]

Train set: Average loss: 0.4263, Accuracy: 84.43%
Val set: Average loss: 0.7434, Accuracy: 68.27%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.60      0.70       418
         SUV       0.55      0.82      0.66       247

    accuracy                           0.68       665
   macro avg       0.70      0.71      0.68       665
weighted avg       0.74      0.68      0.69       665


Epoch: 29

100%|██████████| 97/97 [00:15<00:00,  6.28it/s]

Train set: Average loss: 0.5795, Accuracy: 84.53%
Val set: Average loss: 0.6479, Accuracy: 70.68%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.65      0.74       418
         SUV       0.58      0.80      0.67       247

    accuracy                           0.71       665
   macro avg       0.71      0.73      0.70       665
weighted avg       0.75      0.71      0.71       665


Epoch: 30

  9%|▉         | 9/97 [00:01<00:15,  5.74it/s]

KeyboardInterrupt:

#### Задача на определение марки

In [ ]:
CFG.classes = all_brands

model_cnn_2_brand = CNNReg_Net(task='brand')

In [ ]:
summary(model=model_cnn_2_brand,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
CNNReg_Net                               [32, 3, 96, 160]     [32, 8]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 32, 96, 160]    896                  True
├─BatchNorm2d: 1-2                       [32, 32, 96, 160]    [32, 32, 96, 160]    64                   True
├─LeakyReLU: 1-3                         [32, 32, 96, 160]    [32, 32, 96, 160]    --                   --
├─Conv2d: 1-4                            [32, 32, 96, 160]    [32, 32, 96, 160]    9,248                True
├─BatchNorm2d: 1-5                       [32, 32, 96, 160]    [32, 32, 96, 160]    64                   True
├─LeakyReLU: 1-6                         [32, 32, 96, 160]    [32, 32, 96, 160]    --                   --
├─MaxPool2d: 1-7                         [32, 32, 96, 160]    [32, 32, 48, 80]     --                   --
├─Conv2d: 1-8                            [32, 32, 48, 80]     [32, 64, 48, 80]     18,496               True
├─BatchNorm2d: 1-9                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─LeakyReLU: 1-10                        [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─Conv2d: 1-11                           [32, 64, 48, 80]     [32, 64, 48, 80]     36,928               True
├─BatchNorm2d: 1-12                      [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─LeakyReLU: 1-13                        [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-14                        [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Dropout2d: 1-15                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Conv2d: 1-16                           [32, 64, 24, 40]     [32, 128, 24, 40]    73,856               True
├─BatchNorm2d: 1-17                      [32, 128, 24, 40]    [32, 128, 24, 40]    256                  True
├─LeakyReLU: 1-18                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─Dropout2d: 1-19                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─Conv2d: 1-20                           [32, 128, 24, 40]    [32, 128, 24, 40]    147,584              True
├─BatchNorm2d: 1-21                      [32, 128, 24, 40]    [32, 128, 24, 40]    256                  True
├─LeakyReLU: 1-22                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─MaxPool2d: 1-23                        [32, 128, 24, 40]    [32, 128, 12, 20]    --                   --
├─Dropout2d: 1-24                        [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Conv2d: 1-25                           [32, 128, 12, 20]    [32, 256, 12, 20]    295,168              True
├─BatchNorm2d: 1-26                      [32, 256, 12, 20]    [32, 256, 12, 20]    512                  True
├─LeakyReLU: 1-27                        [32, 256, 12, 20]    [32, 256, 12, 20]    --                   --
├─MaxPool2d: 1-28                        [32, 256, 12, 20]    [32, 256, 6, 10]     --                   --
├─Dropout2d: 1-29                        [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Linear: 1-30                           [32, 15360]          [32, 256]            3,932,416            True
├─BatchNorm1d: 1-31                      [32, 256]            [32, 256]            512                  True
├─LeakyReLU: 1-32                        [32, 256]            [32, 256]            --                   --
├─Dropout: 1-33                          [32, 256]            [32, 256]            --                   --
├─Linear: 1-34                           [32, 256]            [32, 64]             16,448               True
├─LeakyReLU: 1-35                        [32, 64]             [32, 64]             --                   --
├─Dropout: 1-36                          [32, 64]             [32, 64]             --                   --
├─Linear: 1-37                           [32, 64]             [32, 8]              520                  True
========================================================================================================================
Total params: 4,533,480
Trainable params: 4,533,480
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 20.99
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 912.41
Params size (MB): 18.13
Estimated Total Size (MB): 936.44
========================================================================================================================

In [ ]:
main_kolesa(model_cnn_2_brand, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_cnn_2_brand, 'Reg_CNN_brand')

Epoch: 1

100%|██████████| 97/97 [00:19<00:00,  5.10it/s]

Train set: Average loss: 2.0976, Accuracy: 15.37%
Val set: Average loss: 2.0732, Accuracy: 14.29%

Classification report:
               precision    recall  f1-score   support

         Audi       0.20      0.01      0.03        73
          BMW       0.11      0.17      0.14        90
    Chevrolet       0.16      0.67      0.26        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.33      0.12      0.17        77
        Lexus       0.11      0.12      0.11        95
Mercedes-Benz       0.00      0.00      0.00        81
       Toyota       0.09      0.07      0.08        85

     accuracy                           0.14       665
    macro avg       0.13      0.14      0.10       665
 weighted avg       0.12      0.14      0.10       665


Epoch: 2

100%|██████████| 97/97 [00:19<00:00,  4.90it/s]

Train set: Average loss: 2.0746, Accuracy: 17.60%
Val set: Average loss: 2.0500, Accuracy: 16.84%

Classification report:
               precision    recall  f1-score   support

         Audi       0.11      0.01      0.02        73
          BMW       0.16      0.22      0.19        90
    Chevrolet       0.15      0.70      0.25        79
      Hyundai       1.00      0.02      0.05        85
          Kia       0.21      0.21      0.21        77
        Lexus       0.19      0.15      0.17        95
Mercedes-Benz       0.33      0.01      0.02        81
       Toyota       0.16      0.04      0.06        85

     accuracy                           0.17       665
    macro avg       0.29      0.17      0.12       665
 weighted avg       0.29      0.17      0.12       665


Epoch: 3

100%|██████████| 97/97 [00:19<00:00,  5.02it/s]

Train set: Average loss: 1.9728, Accuracy: 19.37%
Val set: Average loss: 2.0120, Accuracy: 20.45%

Classification report:
               precision    recall  f1-score   support

         Audi       0.50      0.01      0.03        73
          BMW       0.17      0.49      0.26        90
    Chevrolet       0.31      0.47      0.37        79
      Hyundai       0.15      0.02      0.04        85
          Kia       0.20      0.21      0.21        77
        Lexus       0.15      0.19      0.17        95
Mercedes-Benz       0.33      0.12      0.18        81
       Toyota       0.16      0.09      0.12        85

     accuracy                           0.20       665
    macro avg       0.25      0.20      0.17       665
 weighted avg       0.24      0.20      0.17       665


Epoch: 4

100%|██████████| 97/97 [00:20<00:00,  4.84it/s]

Train set: Average loss: 1.8476, Accuracy: 21.46%
Val set: Average loss: 2.0294, Accuracy: 18.50%

Classification report:
               precision    recall  f1-score   support

         Audi       0.19      0.04      0.07        73
          BMW       0.20      0.37      0.26        90
    Chevrolet       0.17      0.71      0.28        79
      Hyundai       0.23      0.04      0.06        85
          Kia       0.18      0.16      0.17        77
        Lexus       0.16      0.07      0.10        95
Mercedes-Benz       0.43      0.11      0.18        81
       Toyota       0.00      0.00      0.00        85

     accuracy                           0.18       665
    macro avg       0.20      0.19      0.14       665
 weighted avg       0.19      0.18      0.14       665


Epoch: 5

100%|██████████| 97/97 [00:18<00:00,  5.13it/s]

Train set: Average loss: 1.8707, Accuracy: 23.07%
Val set: Average loss: 2.0192, Accuracy: 20.00%

Classification report:
               precision    recall  f1-score   support

         Audi       0.32      0.16      0.22        73
          BMW       0.18      0.22      0.20        90
    Chevrolet       0.18      0.72      0.29        79
      Hyundai       0.27      0.07      0.11        85
          Kia       0.18      0.17      0.17        77
        Lexus       0.20      0.13      0.15        95
Mercedes-Benz       0.45      0.11      0.18        81
       Toyota       0.14      0.05      0.07        85

     accuracy                           0.20       665
    macro avg       0.24      0.20      0.17       665
 weighted avg       0.24      0.20      0.17       665


Epoch: 6

100%|██████████| 97/97 [00:18<00:00,  5.12it/s]

Train set: Average loss: 1.7933, Accuracy: 24.36%
Val set: Average loss: 1.9932, Accuracy: 21.35%

Classification report:
               precision    recall  f1-score   support

         Audi       0.45      0.12      0.19        73
          BMW       0.21      0.31      0.25        90
    Chevrolet       0.24      0.66      0.35        79
      Hyundai       0.20      0.13      0.16        85
          Kia       0.16      0.10      0.12        77
        Lexus       0.20      0.16      0.18        95
Mercedes-Benz       0.21      0.14      0.16        81
       Toyota       0.14      0.09      0.11        85

     accuracy                           0.21       665
    macro avg       0.22      0.21      0.19       665
 weighted avg       0.22      0.21      0.19       665


Epoch: 7

100%|██████████| 97/97 [00:19<00:00,  5.06it/s]

Train set: Average loss: 1.7623, Accuracy: 25.23%
Val set: Average loss: 1.9947, Accuracy: 22.26%

Classification report:
               precision    recall  f1-score   support

         Audi       0.25      0.07      0.11        73
          BMW       0.21      0.63      0.32        90
    Chevrolet       0.23      0.59      0.34        79
      Hyundai       0.28      0.06      0.10        85
          Kia       0.21      0.12      0.15        77
        Lexus       0.22      0.13      0.16        95
Mercedes-Benz       0.27      0.12      0.17        81
       Toyota       0.14      0.04      0.06        85

     accuracy                           0.22       665
    macro avg       0.23      0.22      0.17       665
 weighted avg       0.23      0.22      0.18       665


Epoch: 8

100%|██████████| 97/97 [00:19<00:00,  4.97it/s]

Train set: Average loss: 1.7182, Accuracy: 26.07%
Val set: Average loss: 1.9495, Accuracy: 23.61%

Classification report:
               precision    recall  f1-score   support

         Audi       0.28      0.16      0.21        73
          BMW       0.23      0.46      0.31        90
    Chevrolet       0.29      0.51      0.37        79
      Hyundai       0.22      0.15      0.18        85
          Kia       0.22      0.14      0.17        77
        Lexus       0.26      0.17      0.20        95
Mercedes-Benz       0.28      0.23      0.25        81
       Toyota       0.08      0.06      0.07        85

     accuracy                           0.24       665
    macro avg       0.23      0.24      0.22       665
 weighted avg       0.23      0.24      0.22       665


Epoch: 9

100%|██████████| 97/97 [00:18<00:00,  5.37it/s]

Train set: Average loss: 1.7069, Accuracy: 27.39%
Val set: Average loss: 2.0655, Accuracy: 21.35%

Classification report:
               precision    recall  f1-score   support

         Audi       0.40      0.16      0.23        73
          BMW       0.20      0.33      0.25        90
    Chevrolet       0.20      0.71      0.31        79
      Hyundai       0.36      0.09      0.15        85
          Kia       0.21      0.13      0.16        77
        Lexus       0.30      0.07      0.12        95
Mercedes-Benz       0.43      0.15      0.22        81
       Toyota       0.09      0.08      0.08        85

     accuracy                           0.21       665
    macro avg       0.27      0.22      0.19       665
 weighted avg       0.27      0.21      0.19       665


Epoch: 10

100%|██████████| 97/97 [00:18<00:00,  5.37it/s]

Train set: Average loss: 1.7413, Accuracy: 29.65%
Val set: Average loss: 1.9441, Accuracy: 25.26%

Classification report:
               precision    recall  f1-score   support

         Audi       0.29      0.08      0.13        73
          BMW       0.23      0.52      0.32        90
    Chevrolet       0.32      0.46      0.38        79
      Hyundai       0.30      0.25      0.27        85
          Kia       0.28      0.17      0.21        77
        Lexus       0.25      0.20      0.22        95
Mercedes-Benz       0.21      0.19      0.20        81
       Toyota       0.17      0.13      0.15        85

     accuracy                           0.25       665
    macro avg       0.26      0.25      0.23       665
 weighted avg       0.25      0.25      0.24       665


Epoch: 11

100%|██████████| 97/97 [00:17<00:00,  5.41it/s]

Train set: Average loss: 1.7499, Accuracy: 29.04%
Val set: Average loss: 1.9824, Accuracy: 25.11%

Classification report:
               precision    recall  f1-score   support

         Audi       0.22      0.15      0.18        73
          BMW       0.24      0.53      0.33        90
    Chevrolet       0.55      0.29      0.38        79
      Hyundai       0.24      0.21      0.22        85
          Kia       0.31      0.14      0.19        77
        Lexus       0.23      0.18      0.20        95
Mercedes-Benz       0.21      0.42      0.28        81
       Toyota       0.24      0.06      0.09        85

     accuracy                           0.25       665
    macro avg       0.28      0.25      0.23       665
 weighted avg       0.28      0.25      0.24       665


Epoch: 12

100%|██████████| 97/97 [00:17<00:00,  5.40it/s]

Train set: Average loss: 1.7320, Accuracy: 30.94%
Val set: Average loss: 1.9659, Accuracy: 23.91%

Classification report:
               precision    recall  f1-score   support

         Audi       0.24      0.12      0.16        73
          BMW       0.26      0.44      0.33        90
    Chevrolet       0.25      0.57      0.35        79
      Hyundai       0.27      0.15      0.20        85
          Kia       0.28      0.17      0.21        77
        Lexus       0.24      0.16      0.19        95
Mercedes-Benz       0.22      0.20      0.21        81
       Toyota       0.12      0.09      0.10        85

     accuracy                           0.24       665
    macro avg       0.24      0.24      0.22       665
 weighted avg       0.24      0.24      0.22       665


Epoch: 13

100%|██████████| 97/97 [00:18<00:00,  5.37it/s]

Train set: Average loss: 1.7475, Accuracy: 29.75%
Val set: Average loss: 1.9530, Accuracy: 26.17%

Classification report:
               precision    recall  f1-score   support

         Audi       0.26      0.16      0.20        73
          BMW       0.24      0.50      0.32        90
    Chevrolet       0.33      0.51      0.40        79
      Hyundai       0.28      0.20      0.23        85
          Kia       0.33      0.17      0.22        77
        Lexus       0.21      0.15      0.17        95
Mercedes-Benz       0.26      0.31      0.28        81
       Toyota       0.19      0.09      0.12        85

     accuracy                           0.26       665
    macro avg       0.26      0.26      0.24       665
 weighted avg       0.26      0.26      0.24       665


Epoch: 14

100%|██████████| 97/97 [00:17<00:00,  5.39it/s]

Train set: Average loss: 1.7114, Accuracy: 31.68%
Val set: Average loss: 1.9518, Accuracy: 26.77%

Classification report:
               precision    recall  f1-score   support

         Audi       0.27      0.18      0.21        73
          BMW       0.25      0.57      0.35        90
    Chevrolet       0.37      0.49      0.42        79
      Hyundai       0.26      0.18      0.21        85
          Kia       0.37      0.17      0.23        77
        Lexus       0.24      0.20      0.22        95
Mercedes-Benz       0.20      0.21      0.20        81
       Toyota       0.21      0.13      0.16        85

     accuracy                           0.27       665
    macro avg       0.27      0.27      0.25       665
 weighted avg       0.27      0.27      0.25       665


Epoch: 15

100%|██████████| 97/97 [00:18<00:00,  5.36it/s]

Train set: Average loss: 1.6452, Accuracy: 32.81%
Val set: Average loss: 1.9718, Accuracy: 24.51%

Classification report:
               precision    recall  f1-score   support

         Audi       0.22      0.12      0.16        73
          BMW       0.29      0.30      0.30        90
    Chevrolet       0.61      0.22      0.32        79
      Hyundai       0.21      0.32      0.25        85
          Kia       0.34      0.19      0.25        77
        Lexus       0.21      0.27      0.24        95
Mercedes-Benz       0.21      0.43      0.28        81
       Toyota       0.19      0.08      0.11        85

     accuracy                           0.25       665
    macro avg       0.28      0.24      0.24       665
 weighted avg       0.28      0.25      0.24       665


Epoch: 16

100%|██████████| 97/97 [00:24<00:00,  3.96it/s]

Train set: Average loss: 1.5578, Accuracy: 32.58%
Val set: Average loss: 1.9660, Accuracy: 25.26%

Classification report:
               precision    recall  f1-score   support

         Audi       0.28      0.14      0.18        73
          BMW       0.29      0.29      0.29        90
    Chevrolet       0.41      0.41      0.41        79
      Hyundai       0.23      0.21      0.22        85
          Kia       0.45      0.17      0.25        77
        Lexus       0.20      0.31      0.24        95
Mercedes-Benz       0.21      0.26      0.23        81
       Toyota       0.17      0.22      0.20        85

     accuracy                           0.25       665
    macro avg       0.28      0.25      0.25       665
 weighted avg       0.28      0.25      0.25       665


Epoch: 17

100%|██████████| 97/97 [00:24<00:00,  3.99it/s]

Train set: Average loss: 1.5825, Accuracy: 35.45%
Val set: Average loss: 1.9242, Accuracy: 29.17%

Classification report:
               precision    recall  f1-score   support

         Audi       0.33      0.19      0.24        73
          BMW       0.25      0.57      0.35        90
    Chevrolet       0.50      0.42      0.46        79
      Hyundai       0.27      0.16      0.21        85
          Kia       0.40      0.23      0.30        77
        Lexus       0.26      0.26      0.26        95
Mercedes-Benz       0.24      0.35      0.28        81
       Toyota       0.26      0.13      0.17        85

     accuracy                           0.29       665
    macro avg       0.31      0.29      0.28       665
 weighted avg       0.31      0.29      0.28       665


Epoch: 18

100%|██████████| 97/97 [00:22<00:00,  4.24it/s]

Train set: Average loss: 1.6552, Accuracy: 36.93%
Val set: Average loss: 1.9417, Accuracy: 27.82%

Classification report:
               precision    recall  f1-score   support

         Audi       0.27      0.25      0.26        73
          BMW       0.29      0.44      0.35        90
    Chevrolet       0.45      0.42      0.43        79
      Hyundai       0.26      0.21      0.23        85
          Kia       0.27      0.29      0.28        77
        Lexus       0.24      0.25      0.25        95
Mercedes-Benz       0.23      0.22      0.23        81
       Toyota       0.20      0.14      0.16        85

     accuracy                           0.28       665
    macro avg       0.28      0.28      0.27       665
 weighted avg       0.28      0.28      0.27       665


Epoch: 19

100%|██████████| 97/97 [00:19<00:00,  4.95it/s]

Train set: Average loss: 1.4869, Accuracy: 37.19%
Val set: Average loss: 1.9588, Accuracy: 25.71%

Classification report:
               precision    recall  f1-score   support

         Audi       0.24      0.16      0.19        73
          BMW       0.28      0.50      0.36        90
    Chevrolet       0.58      0.27      0.37        79
      Hyundai       0.24      0.24      0.24        85
          Kia       0.30      0.16      0.21        77
        Lexus       0.23      0.27      0.25        95
Mercedes-Benz       0.21      0.30      0.24        81
       Toyota       0.17      0.13      0.15        85

     accuracy                           0.26       665
    macro avg       0.28      0.25      0.25       665
 weighted avg       0.28      0.26      0.25       665


Epoch: 20

100%|██████████| 97/97 [00:17<00:00,  5.48it/s]

Train set: Average loss: 1.5557, Accuracy: 37.45%
Val set: Average loss: 1.9535, Accuracy: 27.22%

Classification report:
               precision    recall  f1-score   support

         Audi       0.25      0.18      0.21        73
          BMW       0.28      0.61      0.38        90
    Chevrolet       0.61      0.25      0.36        79
      Hyundai       0.20      0.20      0.20        85
          Kia       0.28      0.17      0.21        77
        Lexus       0.24      0.24      0.24        95
Mercedes-Benz       0.25      0.36      0.30        81
       Toyota       0.24      0.13      0.17        85

     accuracy                           0.27       665
    macro avg       0.30      0.27      0.26       665
 weighted avg       0.29      0.27      0.26       665


Epoch: 21

100%|██████████| 97/97 [00:19<00:00,  4.91it/s]

Train set: Average loss: 1.5519, Accuracy: 38.19%
Val set: Average loss: 1.9560, Accuracy: 27.52%

Classification report:
               precision    recall  f1-score   support

         Audi       0.28      0.21      0.24        73
          BMW       0.27      0.52      0.36        90
    Chevrolet       0.53      0.25      0.34        79
      Hyundai       0.25      0.19      0.22        85
          Kia       0.26      0.22      0.24        77
        Lexus       0.28      0.32      0.29        95
Mercedes-Benz       0.26      0.31      0.28        81
       Toyota       0.20      0.15      0.17        85

     accuracy                           0.28       665
    macro avg       0.29      0.27      0.27       665
 weighted avg       0.29      0.28      0.27       665


Epoch: 22

100%|██████████| 97/97 [00:20<00:00,  4.70it/s]

Train set: Average loss: 1.4621, Accuracy: 38.54%
Val set: Average loss: 1.9756, Accuracy: 28.72%

Classification report:
               precision    recall  f1-score   support

         Audi       0.40      0.25      0.31        73
          BMW       0.30      0.50      0.37        90
    Chevrolet       0.48      0.37      0.41        79
      Hyundai       0.24      0.24      0.24        85
          Kia       0.50      0.26      0.34        77
        Lexus       0.20      0.27      0.23        95
Mercedes-Benz       0.23      0.21      0.22        81
       Toyota       0.20      0.19      0.19        85

     accuracy                           0.29       665
    macro avg       0.32      0.29      0.29       665
 weighted avg       0.31      0.29      0.29       665


Epoch: 23

100%|██████████| 97/97 [00:19<00:00,  4.87it/s]

Train set: Average loss: 1.4220, Accuracy: 40.28%
Val set: Average loss: 1.9362, Accuracy: 27.82%

Classification report:
               precision    recall  f1-score   support

         Audi       0.33      0.29      0.31        73
          BMW       0.32      0.41      0.36        90
    Chevrolet       0.51      0.25      0.34        79
      Hyundai       0.25      0.28      0.27        85
          Kia       0.29      0.34      0.31        77
        Lexus       0.22      0.26      0.24        95
Mercedes-Benz       0.23      0.26      0.24        81
       Toyota       0.20      0.13      0.16        85

     accuracy                           0.28       665
    macro avg       0.29      0.28      0.28       665
 weighted avg       0.29      0.28      0.28       665


Epoch: 24

100%|██████████| 97/97 [00:18<00:00,  5.14it/s]

Train set: Average loss: 1.3701, Accuracy: 41.28%
Val set: Average loss: 1.9410, Accuracy: 28.42%

Classification report:
               precision    recall  f1-score   support

         Audi       0.28      0.27      0.28        73
          BMW       0.29      0.53      0.37        90
    Chevrolet       0.45      0.27      0.33        79
      Hyundai       0.27      0.21      0.24        85
          Kia       0.32      0.26      0.29        77
        Lexus       0.28      0.25      0.26        95
Mercedes-Benz       0.26      0.33      0.30        81
       Toyota       0.18      0.13      0.15        85

     accuracy                           0.28       665
    macro avg       0.29      0.28      0.28       665
 weighted avg       0.29      0.28      0.28       665


Epoch: 25

100%|██████████| 97/97 [00:19<00:00,  5.10it/s]

Train set: Average loss: 1.3254, Accuracy: 42.44%
Val set: Average loss: 1.9773, Accuracy: 28.87%

Classification report:
               precision    recall  f1-score   support

         Audi       0.25      0.25      0.25        73
          BMW       0.29      0.52      0.37        90
    Chevrolet       0.42      0.39      0.41        79
      Hyundai       0.30      0.21      0.25        85
          Kia       0.33      0.25      0.28        77
        Lexus       0.26      0.27      0.27        95
Mercedes-Benz       0.31      0.20      0.24        81
       Toyota       0.20      0.20      0.20        85

     accuracy                           0.29       665
    macro avg       0.29      0.29      0.28       665
 weighted avg       0.29      0.29      0.28       665


Epoch: 26

100%|██████████| 97/97 [00:19<00:00,  5.07it/s]

Train set: Average loss: 1.4600, Accuracy: 43.35%
Val set: Average loss: 1.9470, Accuracy: 27.97%

Classification report:
               precision    recall  f1-score   support

         Audi       0.25      0.22      0.24        73
          BMW       0.31      0.52      0.39        90
    Chevrolet       0.57      0.38      0.45        79
      Hyundai       0.30      0.26      0.28        85
          Kia       0.31      0.22      0.26        77
        Lexus       0.19      0.22      0.21        95
Mercedes-Benz       0.21      0.25      0.23        81
       Toyota       0.19      0.15      0.17        85

     accuracy                           0.28       665
    macro avg       0.29      0.28      0.28       665
 weighted avg       0.29      0.28      0.28       665


Epoch: 27

100%|██████████| 97/97 [00:19<00:00,  4.89it/s]

Train set: Average loss: 1.3872, Accuracy: 44.15%
Val set: Average loss: 1.9350, Accuracy: 28.27%

Classification report:
               precision    recall  f1-score   support

         Audi       0.26      0.25      0.26        73
          BMW       0.30      0.56      0.39        90
    Chevrolet       0.60      0.30      0.40        79
      Hyundai       0.26      0.25      0.25        85
          Kia       0.30      0.27      0.29        77
        Lexus       0.23      0.26      0.24        95
Mercedes-Benz       0.26      0.22      0.24        81
       Toyota       0.19      0.13      0.15        85

     accuracy                           0.28       665
    macro avg       0.30      0.28      0.28       665
 weighted avg       0.30      0.28      0.28       665


Epoch: 28

100%|██████████| 97/97 [00:18<00:00,  5.19it/s]

Train set: Average loss: 1.2394, Accuracy: 46.79%
Val set: Average loss: 1.9829, Accuracy: 27.97%

Classification report:
               precision    recall  f1-score   support

         Audi       0.24      0.29      0.26        73
          BMW       0.30      0.54      0.39        90
    Chevrolet       0.58      0.27      0.37        79
      Hyundai       0.24      0.21      0.23        85
          Kia       0.28      0.26      0.27        77
        Lexus       0.29      0.27      0.28        95
Mercedes-Benz       0.22      0.30      0.25        81
       Toyota       0.21      0.08      0.12        85

     accuracy                           0.28       665
    macro avg       0.30      0.28      0.27       665
 weighted avg       0.29      0.28      0.27       665


Epoch: 29

100%|██████████| 97/97 [00:19<00:00,  5.10it/s]

Train set: Average loss: 1.3832, Accuracy: 47.02%
Val set: Average loss: 1.9554, Accuracy: 28.72%

Classification report:
               precision    recall  f1-score   support

         Audi       0.33      0.19      0.24        73
          BMW       0.39      0.43      0.41        90
    Chevrolet       0.48      0.35      0.41        79
      Hyundai       0.27      0.24      0.25        85
          Kia       0.28      0.32      0.30        77
        Lexus       0.22      0.25      0.23        95
Mercedes-Benz       0.26      0.35      0.29        81
       Toyota       0.16      0.15      0.16        85

     accuracy                           0.29       665
    macro avg       0.30      0.29      0.29       665
 weighted avg       0.30      0.29      0.29       665


Epoch: 30

100%|██████████| 97/97 [00:18<00:00,  5.16it/s]

Train set: Average loss: 1.2477, Accuracy: 48.47%
Val set: Average loss: 1.9180, Accuracy: 28.57%

Classification report:
               precision    recall  f1-score   support

         Audi       0.33      0.26      0.29        73
          BMW       0.31      0.53      0.40        90
    Chevrolet       0.67      0.23      0.34        79
      Hyundai       0.23      0.25      0.24        85
          Kia       0.29      0.31      0.30        77
        Lexus       0.23      0.29      0.26        95
Mercedes-Benz       0.27      0.32      0.29        81
       Toyota       0.18      0.07      0.10        85

     accuracy                           0.29       665
    macro avg       0.31      0.28      0.28       665
 weighted avg       0.31      0.29      0.28       665

Training is ended!
[OK] модель сохранена: models/Reg_CNN_brand.pt

И вернем дефолтное количество эпох

In [ ]:
CFG.num_epochs = 10

Вышло уже в разы лучше

## FineTuned AlexNet

Далее попробуем в качестве другого подхода взять уже ранее предобученную модель. Возьмем AlexNet

In [ ]:
from torchvision.models import alexnet
from torchvision.models import AlexNet_Weights

num_in_features = 9216  # Alex net после сверток выдает 256 каналов, а пуллинг сжимает картинку до 6 x 6
num_out_features = 2    # Sedan и SUV

CFG.lr = 1e-4 #learning rate понижаем для более корректного шага модели

#### Задача на тип кузова

In [ ]:
CFG.classes = all_body_types

model_alexnet_bt = alexnet(weights=AlexNet_Weights.DEFAULT) #DEFAULT - рекомендованный вариант
model_alexnet_bt.classifier = torch.nn.Linear(num_in_features, num_out_features) #alexnet.classifier по умолчанию выдает 1000 классов, а нам нужно 2, поэтому сокращаем

In [ ]:
summary(model=model_alexnet_bt,
        input_size=(32, 3, 96, 160), #картинкики, канал, высота и ширина
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
) #прогоняем фиктивный батч через модель

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
AlexNet                                  [32, 3, 96, 160]     [32, 2]              --                   True
├─Sequential: 1-1                        [32, 3, 96, 160]     [32, 256, 2, 4]      --                   True
│    └─Conv2d: 2-1                       [32, 3, 96, 160]     [32, 64, 23, 39]     23,296               True
│    └─ReLU: 2-2                         [32, 64, 23, 39]     [32, 64, 23, 39]     --                   --
│    └─MaxPool2d: 2-3                    [32, 64, 23, 39]     [32, 64, 11, 19]     --                   --
│    └─Conv2d: 2-4                       [32, 64, 11, 19]     [32, 192, 11, 19]    307,392              True
│    └─ReLU: 2-5                         [32, 192, 11, 19]    [32, 192, 11, 19]    --                   --
│    └─MaxPool2d: 2-6                    [32, 192, 11, 19]    [32, 192, 5, 9]      --                   --
│    └─Conv2d: 2-7                       [32, 192, 5, 9]      [32, 384, 5, 9]      663,936              True
│    └─ReLU: 2-8                         [32, 384, 5, 9]      [32, 384, 5, 9]      --                   --
│    └─Conv2d: 2-9                       [32, 384, 5, 9]      [32, 256, 5, 9]      884,992              True
│    └─ReLU: 2-10                        [32, 256, 5, 9]      [32, 256, 5, 9]      --                   --
│    └─Conv2d: 2-11                      [32, 256, 5, 9]      [32, 256, 5, 9]      590,080              True
│    └─ReLU: 2-12                        [32, 256, 5, 9]      [32, 256, 5, 9]      --                   --
│    └─MaxPool2d: 2-13                   [32, 256, 5, 9]      [32, 256, 2, 4]      --                   --
├─AdaptiveAvgPool2d: 1-2                 [32, 256, 2, 4]      [32, 256, 6, 6]      --                   --
├─Linear: 1-3                            [32, 9216]           [32, 2]              18,434               True
========================================================================================================================
Total params: 2,488,130
Trainable params: 2,488,130
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 5.81
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 35.29
Params size (MB): 9.95
Estimated Total Size (MB): 51.14
========================================================================================================================

In [ ]:
main_kolesa(model_alexnet_bt, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_alexnet_bt, 'AlexNet_finetune_body_type')

Epoch: 1

  0%|          | 0/97 [00:00<?, ?it/s]

RuntimeError: Adaptive pool MPS: output sizes must be divisible by input sizes. Non-divisible input sizes are not implemented on MPS device yet. For now, you can manually transfer tensor to cpu in this case. Please refer to [this issue](https://github.com/pytorch/pytorch/issues/96056)

#### Задача на определение марки

In [ ]:
num_out_features = 8 # 8 разных марок
CFG.classes = all_brands

model_alexnet_brand = alexnet(weights=AlexNet_Weights.DEFAULT) #DEFAULT - рекомендованный вариант
model_alexnet_brand.classifier = torch.nn.Linear(num_in_features, num_out_features) #alexnet.classifier по умолчанию выдает 1000 классов, а нам нужно 8, поэтому сокращаем

In [ ]:
summary(model=model_alexnet_brand,
        input_size=(32, 3, 96, 160), #картинкики, канал, высота и ширина
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
) #прогоняем фиктивный батч через модель

In [ ]:
main_kolesa(model_alexnet_brand, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_alexnet_brand, 'AlexNet_finetune_brand')

Доообучение прошло хорошо. Train accuracy выросло с 65 до 90%, на валидации с 70 до 78%.

Качество нессиметрично по классам - Седан распозднается стабильно лучше внедородника

Попробуем второй вариант (который был на семинаре) дообучать только верхние слои + классификатор.

Замороженные параметры (`requires_grad=False`) оптимизатор просто не обновляет.

#### Задача на тип кузова

In [ ]:
CFG.classes = all_body_types
num_out_features = 2

model_alexnet_frozen_bt = alexnet(weights=AlexNet_Weights.DEFAULT)

# замораживаем первые 6 параметров f
layers_to_freeze = 6
for i, (name, param) in enumerate(model_alexnet_frozen_bt.features.named_parameters()):
    if i < layers_to_freeze:
        param.requires_grad = False
    print(f'{name:30}{param.requires_grad}') #выводим имя параметра и его статус (будет использоваться или гет)
    #name:30 выравниваение параметров по ширине в 30 символов (чтобы аккуратно было)

model_alexnet_frozen_bt.classifier = torch.nn.Linear(num_in_features, num_out_features)

0.weight                      False
0.bias                        False
3.weight                      False
3.bias                        False
6.weight                      False
6.bias                        False
8.weight                      True
8.bias                        True
10.weight                     True
10.bias                       True

In [ ]:
main_kolesa(model_alexnet_frozen_bt, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_alexnet_frozen_bt, 'AlexNet_finetune_frozen_body_type')

Epoch: 1

  0%|          | 0/97 [00:00<?, ?it/s]

RuntimeError: Adaptive pool MPS: output sizes must be divisible by input sizes. Non-divisible input sizes are not implemented on MPS device yet. For now, you can manually transfer tensor to cpu in this case. Please refer to [this issue](https://github.com/pytorch/pytorch/issues/96056)

#### Задача на определение марки

In [ ]:
CFG.classes = all_brands
num_out_features = 8

model_alexnet_frozen_brand = alexnet(weights=AlexNet_Weights.DEFAULT)

# замораживаем первые 6 параметров f
layers_to_freeze = 6
for i, (name, param) in enumerate(model_alexnet_frozen_brand.features.named_parameters()):
    if i < layers_to_freeze:
        param.requires_grad = False
    print(f'{name:30}{param.requires_grad}') #выводим имя параметра и его статус (будет использоваться или гет)
    #name:30 выравниваение параметров по ширине в 30 символов (чтобы аккуратно было)

model_alexnet_frozen_brand.classifier = torch.nn.Linear(num_in_features, num_out_features)

In [ ]:
main_kolesa(model_alexnet_frozen_brand, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_alexnet_frozen_brand, 'AlexNet_finetune_frozen_brand')

Заморозка дала результат по всем метрикам: accuracy +2 п.п., macro-F1 +0.03, и что важно - подтянулся слабый класс «внедорожник» (F1 0.72 → 0.75).

## ResNet18

Возьмём более современную **ResNet18**.

Ее преимущество - остаточные связи, которые позволяют обучать глубокие сети без затухания градиента.

Дообучаем так же — через наш `main_kolesa`, заменив только финальный полносвязный слой.

In [ ]:
from torchvision.models import resnet18
from torchvision.models import ResNet18_Weights

#### Задача на тип кузова

In [ ]:
CFG.classes = all_body_types
num_out_features = 2

model_resnet_bt = resnet18(weights=ResNet18_Weights.DEFAULT)
model_resnet_bt.fc = torch.nn.Linear(model_resnet_bt.fc.in_features, num_out_features)

In [ ]:
summary(model=model_resnet_bt,
        input_size=(32, 3, 96, 160),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
ResNet                                   [32, 3, 96, 160]     [32, 2]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 64, 48, 80]     9,408                True
├─BatchNorm2d: 1-2                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─ReLU: 1-3                              [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-4                         [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-5                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    └─BasicBlock: 2-1                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-1                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-2             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-3                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-4                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-5             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-6                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    └─BasicBlock: 2-2                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-7                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-8             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-9                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-10                 [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-11            [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-12                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-6                        [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    └─BasicBlock: 2-3                   [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-13                 [32, 64, 24, 40]     [32, 128, 12, 20]    73,728               True
│    │    └─BatchNorm2d: 3-14            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-15                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-16                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-17            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─Sequential: 3-18             [32, 64, 24, 40]     [32, 128, 12, 20]    8,448                True
│    │    └─ReLU: 3-19                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    └─BasicBlock: 2-4                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-20                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-21            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-22                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-23                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-24            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-25                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Sequential: 1-7                        [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    └─BasicBlock: 2-5                   [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-26                 [32, 128, 12, 20]    [32, 256, 6, 10]     294,912              True
│    │    └─BatchNorm2d: 3-27            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-28                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-29                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-30            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─Sequential: 3-31             [32, 128, 12, 20]    [32, 256, 6, 10]     33,280               True
│    │    └─ReLU: 3-32                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    └─BasicBlock: 2-6                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-33                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-34            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-35                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-36                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-37            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-38                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Sequential: 1-8                        [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    └─BasicBlock: 2-7                   [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-39                 [32, 256, 6, 10]     [32, 512, 3, 5]      1,179,648            True
│    │    └─BatchNorm2d: 3-40            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-41                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-42                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-43            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─Sequential: 3-44             [32, 256, 6, 10]     [32, 512, 3, 5]      132,096              True
│    │    └─ReLU: 3-45                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    └─BasicBlock: 2-8                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-46                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-47            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-48                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-49                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-50            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-51                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
├─AdaptiveAvgPool2d: 1-9                 [32, 512, 3, 5]      [32, 512, 1, 1]      --                   --
├─Linear: 1-10                           [32, 512]            [32, 2]              1,026                True
========================================================================================================================
Total params: 11,177,538
Trainable params: 11,177,538
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 17.77
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 389.28
Params size (MB): 44.71
Estimated Total Size (MB): 439.89
========================================================================================================================

In [ ]:
main_kolesa(model_resnet_bt, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_resnet_bt, 'ResNet18_finetune_body_type')

Epoch: 1

100%|██████████| 97/97 [00:22<00:00,  4.36it/s]

Train set: Average loss: 0.6797, Accuracy: 72.99%
Val set: Average loss: 0.3294, Accuracy: 83.61%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.89      0.87       418
         SUV       0.81      0.74      0.77       247

    accuracy                           0.84       665
   macro avg       0.83      0.82      0.82       665
weighted avg       0.83      0.84      0.83       665


Epoch: 2

100%|██████████| 97/97 [00:17<00:00,  5.67it/s]

Train set: Average loss: 0.4057, Accuracy: 85.98%
Val set: Average loss: 0.3828, Accuracy: 83.61%

Classification report:
              precision    recall  f1-score   support

       sedan       0.87      0.87      0.87       418
         SUV       0.78      0.78      0.78       247

    accuracy                           0.84       665
   macro avg       0.82      0.82      0.82       665
weighted avg       0.84      0.84      0.84       665


Epoch: 3

100%|██████████| 97/97 [00:18<00:00,  5.33it/s]

Train set: Average loss: 0.4759, Accuracy: 91.62%
Val set: Average loss: 0.3449, Accuracy: 85.71%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.94      0.89       418
         SUV       0.87      0.72      0.79       247

    accuracy                           0.86       665
   macro avg       0.86      0.83      0.84       665
weighted avg       0.86      0.86      0.85       665


Epoch: 4

100%|██████████| 97/97 [00:17<00:00,  5.43it/s]

Train set: Average loss: 0.2125, Accuracy: 93.97%
Val set: Average loss: 0.3891, Accuracy: 85.86%

Classification report:
              precision    recall  f1-score   support

       sedan       0.91      0.86      0.88       418
         SUV       0.79      0.85      0.82       247

    accuracy                           0.86       665
   macro avg       0.85      0.86      0.85       665
weighted avg       0.86      0.86      0.86       665


Epoch: 5

100%|██████████| 97/97 [00:16<00:00,  5.72it/s]

Train set: Average loss: 0.2819, Accuracy: 94.81%
Val set: Average loss: 0.3389, Accuracy: 86.92%

Classification report:
              precision    recall  f1-score   support

       sedan       0.88      0.92      0.90       418
         SUV       0.85      0.79      0.82       247

    accuracy                           0.87       665
   macro avg       0.86      0.85      0.86       665
weighted avg       0.87      0.87      0.87       665


Epoch: 6

100%|██████████| 97/97 [00:18<00:00,  5.36it/s]

Train set: Average loss: 0.1677, Accuracy: 96.97%
Val set: Average loss: 0.3325, Accuracy: 86.32%

Classification report:
              precision    recall  f1-score   support

       sedan       0.91      0.86      0.89       418
         SUV       0.79      0.86      0.82       247

    accuracy                           0.86       665
   macro avg       0.85      0.86      0.86       665
weighted avg       0.87      0.86      0.86       665


Epoch: 7

100%|██████████| 97/97 [00:22<00:00,  4.31it/s]

Train set: Average loss: 0.1705, Accuracy: 97.52%
Val set: Average loss: 0.4010, Accuracy: 87.52%

Classification report:
              precision    recall  f1-score   support

       sedan       0.91      0.89      0.90       418
         SUV       0.82      0.85      0.83       247

    accuracy                           0.88       665
   macro avg       0.87      0.87      0.87       665
weighted avg       0.88      0.88      0.88       665


Epoch: 8

100%|██████████| 97/97 [00:20<00:00,  4.76it/s]

Train set: Average loss: 0.0487, Accuracy: 97.49%
Val set: Average loss: 0.3203, Accuracy: 89.17%

Classification report:
              precision    recall  f1-score   support

       sedan       0.91      0.92      0.91       418
         SUV       0.86      0.84      0.85       247

    accuracy                           0.89       665
   macro avg       0.89      0.88      0.88       665
weighted avg       0.89      0.89      0.89       665


Epoch: 9

100%|██████████| 97/97 [00:20<00:00,  4.83it/s]

Train set: Average loss: 0.0760, Accuracy: 97.94%
Val set: Average loss: 0.2873, Accuracy: 87.37%

Classification report:
              precision    recall  f1-score   support

       sedan       0.89      0.91      0.90       418
         SUV       0.84      0.81      0.83       247

    accuracy                           0.87       665
   macro avg       0.87      0.86      0.86       665
weighted avg       0.87      0.87      0.87       665


Epoch: 10

100%|██████████| 97/97 [00:21<00:00,  4.61it/s]

Train set: Average loss: 0.0479, Accuracy: 98.36%
Val set: Average loss: 0.4579, Accuracy: 87.82%

Classification report:
              precision    recall  f1-score   support

       sedan       0.90      0.91      0.90       418
         SUV       0.85      0.82      0.83       247

    accuracy                           0.88       665
   macro avg       0.87      0.87      0.87       665
weighted avg       0.88      0.88      0.88       665

Training is ended!
[OK] модель сохранена: models/ResNet18_finetune_body_type.pt

#### Задача на определение марки

In [ ]:
CFG.classes = all_brands
num_out_features = 8

model_resnet_brand = resnet18(weights=ResNet18_Weights.DEFAULT)
model_resnet_brand.fc = torch.nn.Linear(model_resnet_brand.fc.in_features, num_out_features)

In [ ]:
summary(model=model_resnet_brand,
        input_size=(32, 3, 96, 160),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
ResNet                                   [32, 3, 96, 160]     [32, 8]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 64, 48, 80]     9,408                True
├─BatchNorm2d: 1-2                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─ReLU: 1-3                              [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-4                         [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-5                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    └─BasicBlock: 2-1                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-1                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-2             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-3                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-4                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-5             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-6                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    └─BasicBlock: 2-2                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-7                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-8             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-9                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-10                 [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-11            [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-12                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-6                        [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    └─BasicBlock: 2-3                   [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-13                 [32, 64, 24, 40]     [32, 128, 12, 20]    73,728               True
│    │    └─BatchNorm2d: 3-14            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-15                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-16                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-17            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─Sequential: 3-18             [32, 64, 24, 40]     [32, 128, 12, 20]    8,448                True
│    │    └─ReLU: 3-19                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    └─BasicBlock: 2-4                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-20                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-21            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-22                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-23                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-24            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-25                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Sequential: 1-7                        [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    └─BasicBlock: 2-5                   [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-26                 [32, 128, 12, 20]    [32, 256, 6, 10]     294,912              True
│    │    └─BatchNorm2d: 3-27            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-28                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-29                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-30            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─Sequential: 3-31             [32, 128, 12, 20]    [32, 256, 6, 10]     33,280               True
│    │    └─ReLU: 3-32                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    └─BasicBlock: 2-6                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-33                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-34            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-35                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-36                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-37            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-38                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Sequential: 1-8                        [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    └─BasicBlock: 2-7                   [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-39                 [32, 256, 6, 10]     [32, 512, 3, 5]      1,179,648            True
│    │    └─BatchNorm2d: 3-40            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-41                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-42                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-43            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─Sequential: 3-44             [32, 256, 6, 10]     [32, 512, 3, 5]      132,096              True
│    │    └─ReLU: 3-45                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    └─BasicBlock: 2-8                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-46                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-47            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-48                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-49                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-50            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-51                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
├─AdaptiveAvgPool2d: 1-9                 [32, 512, 3, 5]      [32, 512, 1, 1]      --                   --
├─Linear: 1-10                           [32, 512]            [32, 8]              4,104                True
========================================================================================================================
Total params: 11,180,616
Trainable params: 11,180,616
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 17.77
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 389.29
Params size (MB): 44.72
Estimated Total Size (MB): 439.91
========================================================================================================================

In [ ]:
main_kolesa(model_resnet_brand, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_resnet_brand, 'ResNet18_finetune_brand')

Epoch: 1

100%|██████████| 97/97 [00:17<00:00,  5.66it/s]

Train set: Average loss: 1.6108, Accuracy: 26.07%
Val set: Average loss: 1.7420, Accuracy: 37.14%

Classification report:
               precision    recall  f1-score   support

         Audi       0.61      0.34      0.44        73
          BMW       0.71      0.36      0.47        90
    Chevrolet       0.39      0.75      0.51        79
      Hyundai       0.35      0.26      0.30        85
          Kia       0.29      0.32      0.31        77
        Lexus       0.32      0.26      0.29        95
Mercedes-Benz       0.29      0.58      0.39        81
       Toyota       0.32      0.14      0.20        85

     accuracy                           0.37       665
    macro avg       0.41      0.38      0.36       665
 weighted avg       0.41      0.37      0.36       665


Epoch: 2

100%|██████████| 97/97 [00:16<00:00,  5.76it/s]

Train set: Average loss: 1.1984, Accuracy: 50.02%
Val set: Average loss: 1.6863, Accuracy: 47.67%

Classification report:
               precision    recall  f1-score   support

         Audi       0.75      0.45      0.56        73
          BMW       0.61      0.78      0.69        90
    Chevrolet       0.60      0.48      0.54        79
      Hyundai       0.51      0.21      0.30        85
          Kia       0.39      0.35      0.37        77
        Lexus       0.44      0.55      0.49        95
Mercedes-Benz       0.42      0.58      0.48        81
       Toyota       0.29      0.38      0.33        85

     accuracy                           0.48       665
    macro avg       0.50      0.47      0.47       665
 weighted avg       0.50      0.48      0.47       665


Epoch: 3

100%|██████████| 97/97 [00:16<00:00,  5.71it/s]

Train set: Average loss: 0.6794, Accuracy: 64.74%
Val set: Average loss: 1.6265, Accuracy: 49.62%

Classification report:
               precision    recall  f1-score   support

         Audi       0.41      0.66      0.51        73
          BMW       0.63      0.74      0.68        90
    Chevrolet       0.58      0.63      0.61        79
      Hyundai       0.51      0.28      0.36        85
          Kia       0.50      0.40      0.45        77
        Lexus       0.42      0.49      0.45        95
Mercedes-Benz       0.48      0.56      0.51        81
       Toyota       0.44      0.21      0.29        85

     accuracy                           0.50       665
    macro avg       0.50      0.50      0.48       665
 weighted avg       0.50      0.50      0.48       665


Epoch: 4

100%|██████████| 97/97 [00:19<00:00,  5.07it/s]

Train set: Average loss: 0.4777, Accuracy: 72.48%
Val set: Average loss: 1.7866, Accuracy: 51.43%

Classification report:
               precision    recall  f1-score   support

         Audi       0.43      0.55      0.48        73
          BMW       0.64      0.72      0.68        90
    Chevrolet       0.53      0.58      0.55        79
      Hyundai       0.56      0.38      0.45        85
          Kia       0.43      0.64      0.52        77
        Lexus       0.58      0.40      0.47        95
Mercedes-Benz       0.64      0.48      0.55        81
       Toyota       0.38      0.39      0.38        85

     accuracy                           0.51       665
    macro avg       0.52      0.52      0.51       665
 weighted avg       0.53      0.51      0.51       665


Epoch: 5

100%|██████████| 97/97 [00:18<00:00,  5.16it/s]

Train set: Average loss: 0.3211, Accuracy: 78.79%
Val set: Average loss: 1.8243, Accuracy: 58.05%

Classification report:
               precision    recall  f1-score   support

         Audi       0.58      0.67      0.62        73
          BMW       0.69      0.81      0.74        90
    Chevrolet       0.60      0.71      0.65        79
      Hyundai       0.56      0.42      0.48        85
          Kia       0.46      0.57      0.51        77
        Lexus       0.60      0.52      0.55        95
Mercedes-Benz       0.73      0.51      0.60        81
       Toyota       0.45      0.45      0.45        85

     accuracy                           0.58       665
    macro avg       0.58      0.58      0.58       665
 weighted avg       0.59      0.58      0.58       665


Epoch: 6

100%|██████████| 97/97 [00:17<00:00,  5.56it/s]

Train set: Average loss: 0.1329, Accuracy: 83.44%
Val set: Average loss: 1.9385, Accuracy: 52.63%

Classification report:
               precision    recall  f1-score   support

         Audi       0.75      0.45      0.56        73
          BMW       0.65      0.71      0.68        90
    Chevrolet       0.58      0.76      0.66        79
      Hyundai       0.48      0.34      0.40        85
          Kia       0.43      0.52      0.47        77
        Lexus       0.51      0.48      0.50        95
Mercedes-Benz       0.72      0.44      0.55        81
       Toyota       0.34      0.49      0.40        85

     accuracy                           0.53       665
    macro avg       0.56      0.53      0.53       665
 weighted avg       0.55      0.53      0.53       665


Epoch: 7

100%|██████████| 97/97 [00:17<00:00,  5.53it/s]

Train set: Average loss: 0.2012, Accuracy: 88.40%
Val set: Average loss: 2.0961, Accuracy: 54.44%

Classification report:
               precision    recall  f1-score   support

         Audi       0.68      0.53      0.60        73
          BMW       0.63      0.73      0.68        90
    Chevrolet       0.50      0.80      0.62        79
      Hyundai       0.57      0.41      0.48        85
          Kia       0.47      0.49      0.48        77
        Lexus       0.51      0.46      0.49        95
Mercedes-Benz       0.62      0.49      0.55        81
       Toyota       0.43      0.44      0.43        85

     accuracy                           0.54       665
    macro avg       0.55      0.55      0.54       665
 weighted avg       0.55      0.54      0.54       665


Epoch: 8

100%|██████████| 97/97 [00:19<00:00,  4.87it/s]

Train set: Average loss: 0.2971, Accuracy: 88.66%
Val set: Average loss: 1.7923, Accuracy: 54.89%

Classification report:
               precision    recall  f1-score   support

         Audi       0.54      0.75      0.63        73
          BMW       0.64      0.72      0.68        90
    Chevrolet       0.67      0.63      0.65        79
      Hyundai       0.53      0.41      0.46        85
          Kia       0.48      0.60      0.53        77
        Lexus       0.56      0.44      0.49        95
Mercedes-Benz       0.46      0.59      0.52        81
       Toyota       0.51      0.28      0.36        85

     accuracy                           0.55       665
    macro avg       0.55      0.55      0.54       665
 weighted avg       0.55      0.55      0.54       665


Epoch: 9

100%|██████████| 97/97 [00:18<00:00,  5.18it/s]

Train set: Average loss: 0.6464, Accuracy: 89.08%
Val set: Average loss: 1.9045, Accuracy: 54.89%

Classification report:
               precision    recall  f1-score   support

         Audi       0.56      0.66      0.61        73
          BMW       0.70      0.71      0.70        90
    Chevrolet       0.78      0.57      0.66        79
      Hyundai       0.54      0.53      0.54        85
          Kia       0.57      0.39      0.46        77
        Lexus       0.45      0.66      0.54        95
Mercedes-Benz       0.60      0.47      0.53        81
       Toyota       0.35      0.38      0.36        85

     accuracy                           0.55       665
    macro avg       0.57      0.55      0.55       665
 weighted avg       0.57      0.55      0.55       665


Epoch: 10

100%|██████████| 97/97 [00:17<00:00,  5.62it/s]

Train set: Average loss: 0.0875, Accuracy: 92.49%
Val set: Average loss: 1.9049, Accuracy: 56.99%

Classification report:
               precision    recall  f1-score   support

         Audi       0.77      0.55      0.64        73
          BMW       0.76      0.70      0.73        90
    Chevrolet       0.50      0.82      0.62        79
      Hyundai       0.47      0.66      0.55        85
          Kia       0.59      0.47      0.52        77
        Lexus       0.63      0.54      0.58        95
Mercedes-Benz       0.56      0.53      0.54        81
       Toyota       0.39      0.29      0.34        85

     accuracy                           0.57       665
    macro avg       0.58      0.57      0.57       665
 weighted avg       0.58      0.57      0.57       665

Training is ended!
[OK] модель сохранена: models/ResNet18_finetune_brand.pt

  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ksa/CodeProjects/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

У нас получились пока все еще плохие результаты для задачи на марки. Модель переобучилась. Попробуем изменить гиперпараметры для ResNet.

Сделаем измененную main функцию

In [ ]:
def main_kolesa_new(model, train_df, val_df):

    if CFG.wandb:
        wandb.init(project=CFG.project, entity=CFG.entity, reinit=True, config=class2dict(CFG))
        # логируем архитектуру модели
        # https://docs.wandb.ai/guides/track/config
        wandb.config.update({'model': str(model)})

    seed_everything(CFG.seed)

    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')

    kwargs = {'num_workers': CFG.num_workers, 'pin_memory': torch.cuda.is_available()}

    # Попробуем картинки побольше
    # будем использовать различные методы аугментации https://docs.pytorch.org/vision/0.13/transforms.html
    train_transform = transforms.Compose([
        transforms.Resize((320, 512)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.1),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    test_transform = transforms.Compose([
        transforms.Resize((320, 512)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    train_ds = KolesaDataset(train_df, transform=train_transform)
    val_ds = KolesaDataset(val_df, transform=test_transform)
    # test_ds = KolesaDataset(test_df, transform=test_transform)

    train_loader = torch.utils.data.DataLoader(train_ds, batch_size=CFG.train_batch_size, **kwargs)
    val_loader = torch.utils.data.DataLoader(val_ds, batch_size=CFG.test_batch_size, **kwargs)
    # test_loader = torch.utils.data.DataLoader(test_ds, batch_size=CFG.test_batch_size, **kwargs)

    model = model.to(device)

    if CFG.wandb:
        wandb.watch(model, log='all')

    # https://habr.com/ru/articles/988198/
    # добавим l2 регуляризацию (weight_decay)
    optimizer = optim.Adam(model.parameters(),
                          lr=CFG.lr, weight_decay=3e-4)

    # добавим небольшой коэф. сглаживания, что может помочь с переобучением
    criterion = nn.CrossEntropyLoss(label_smoothing=0.05)

    for epoch in range(1, CFG.num_epochs + 1):
        print('\nEpoch:', epoch)
        train(model, device, train_loader, optimizer, criterion, epoch, CFG.wandb)
        val(model, device, val_loader, criterion, CFG.wandb)

    print('Training is ended!')

Изменим learning rate и возьмем побольше эпох

In [ ]:
CFG.num_epochs = 15
CFG.lr = 3e-5

Также добавим dropout (регуляризацию) в модель.

### Задача на тип кузова

In [ ]:
CFG.classes = all_body_types
num_out_features = 2
CFG.test_batch_size = 64 # иначе не хватает памяти с дефолтным 512

# https://discuss.pytorch.org/t/resnet-last-layer-modification/33530
model_resnet_bt_reg = resnet18(weights=ResNet18_Weights.DEFAULT)
model_resnet_bt_reg.fc = nn.Sequential(
    nn.Dropout(0.4),
    nn.Linear(model_resnet_bt_reg.fc.in_features, num_out_features)
)

In [ ]:
summary(model=model_resnet_bt_reg,
        input_size=(32, 3, 320, 512),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
ResNet                                   [32, 3, 320, 512]    [32, 2]              --                   True
├─Conv2d: 1-1                            [32, 3, 320, 512]    [32, 64, 160, 256]   9,408                True
├─BatchNorm2d: 1-2                       [32, 64, 160, 256]   [32, 64, 160, 256]   128                  True
├─ReLU: 1-3                              [32, 64, 160, 256]   [32, 64, 160, 256]   --                   --
├─MaxPool2d: 1-4                         [32, 64, 160, 256]   [32, 64, 80, 128]    --                   --
├─Sequential: 1-5                        [32, 64, 80, 128]    [32, 64, 80, 128]    --                   True
│    └─BasicBlock: 2-1                   [32, 64, 80, 128]    [32, 64, 80, 128]    --                   True
│    │    └─Conv2d: 3-1                  [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-2             [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-3                    [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
│    │    └─Conv2d: 3-4                  [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-5             [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-6                    [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
│    └─BasicBlock: 2-2                   [32, 64, 80, 128]    [32, 64, 80, 128]    --                   True
│    │    └─Conv2d: 3-7                  [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-8             [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-9                    [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
│    │    └─Conv2d: 3-10                 [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-11            [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-12                   [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
├─Sequential: 1-6                        [32, 64, 80, 128]    [32, 128, 40, 64]    --                   True
│    └─BasicBlock: 2-3                   [32, 64, 80, 128]    [32, 128, 40, 64]    --                   True
│    │    └─Conv2d: 3-13                 [32, 64, 80, 128]    [32, 128, 40, 64]    73,728               True
│    │    └─BatchNorm2d: 3-14            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─ReLU: 3-15                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
│    │    └─Conv2d: 3-16                 [32, 128, 40, 64]    [32, 128, 40, 64]    147,456              True
│    │    └─BatchNorm2d: 3-17            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─Sequential: 3-18             [32, 64, 80, 128]    [32, 128, 40, 64]    8,448                True
│    │    └─ReLU: 3-19                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
│    └─BasicBlock: 2-4                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   True
│    │    └─Conv2d: 3-20                 [32, 128, 40, 64]    [32, 128, 40, 64]    147,456              True
│    │    └─BatchNorm2d: 3-21            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─ReLU: 3-22                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
│    │    └─Conv2d: 3-23                 [32, 128, 40, 64]    [32, 128, 40, 64]    147,456              True
│    │    └─BatchNorm2d: 3-24            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─ReLU: 3-25                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
├─Sequential: 1-7                        [32, 128, 40, 64]    [32, 256, 20, 32]    --                   True
│    └─BasicBlock: 2-5                   [32, 128, 40, 64]    [32, 256, 20, 32]    --                   True
│    │    └─Conv2d: 3-26                 [32, 128, 40, 64]    [32, 256, 20, 32]    294,912              True
│    │    └─BatchNorm2d: 3-27            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─ReLU: 3-28                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
│    │    └─Conv2d: 3-29                 [32, 256, 20, 32]    [32, 256, 20, 32]    589,824              True
│    │    └─BatchNorm2d: 3-30            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─Sequential: 3-31             [32, 128, 40, 64]    [32, 256, 20, 32]    33,280               True
│    │    └─ReLU: 3-32                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
│    └─BasicBlock: 2-6                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   True
│    │    └─Conv2d: 3-33                 [32, 256, 20, 32]    [32, 256, 20, 32]    589,824              True
│    │    └─BatchNorm2d: 3-34            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─ReLU: 3-35                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
│    │    └─Conv2d: 3-36                 [32, 256, 20, 32]    [32, 256, 20, 32]    589,824              True
│    │    └─BatchNorm2d: 3-37            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─ReLU: 3-38                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
├─Sequential: 1-8                        [32, 256, 20, 32]    [32, 512, 10, 16]    --                   True
│    └─BasicBlock: 2-7                   [32, 256, 20, 32]    [32, 512, 10, 16]    --                   True
│    │    └─Conv2d: 3-39                 [32, 256, 20, 32]    [32, 512, 10, 16]    1,179,648            True
│    │    └─BatchNorm2d: 3-40            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─ReLU: 3-41                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
│    │    └─Conv2d: 3-42                 [32, 512, 10, 16]    [32, 512, 10, 16]    2,359,296            True
│    │    └─BatchNorm2d: 3-43            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─Sequential: 3-44             [32, 256, 20, 32]    [32, 512, 10, 16]    132,096              True
│    │    └─ReLU: 3-45                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
│    └─BasicBlock: 2-8                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   True
│    │    └─Conv2d: 3-46                 [32, 512, 10, 16]    [32, 512, 10, 16]    2,359,296            True
│    │    └─BatchNorm2d: 3-47            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─ReLU: 3-48                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
│    │    └─Conv2d: 3-49                 [32, 512, 10, 16]    [32, 512, 10, 16]    2,359,296            True
│    │    └─BatchNorm2d: 3-50            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─ReLU: 3-51                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
├─AdaptiveAvgPool2d: 1-9                 [32, 512, 10, 16]    [32, 512, 1, 1]      --                   --
├─Sequential: 1-10                       [32, 512]            [32, 2]              --                   True
│    └─Dropout: 2-9                      [32, 512]            [32, 512]            --                   --
│    └─Linear: 2-10                      [32, 512]            [32, 2]              1,026                True
========================================================================================================================
Total params: 11,177,538
Trainable params: 11,177,538
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 189.50
========================================================================================================================
Input size (MB): 62.91
Forward/backward pass size (MB): 4152.36
Params size (MB): 44.71
Estimated Total Size (MB): 4259.99
========================================================================================================================

In [ ]:
main_kolesa_new(model_resnet_bt_reg, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_resnet_bt_reg, 'ResNet18_reg_finetune_bt')

Epoch: 1

  0%|          | 0/97 [00:11<?, ?it/s]

KeyboardInterrupt:

### Задача на марки

In [ ]:
CFG.classes = all_brands
num_out_features = 8
# https://discuss.pytorch.org/t/resnet-last-layer-modification/33530
model_resnet_brand_reg = resnet18(weights=ResNet18_Weights.DEFAULT)
model_resnet_brand_reg.fc = nn.Sequential(
    nn.Dropout(0.4),
    nn.Linear(model_resnet_brand.fc.in_features, num_out_features)
)

In [ ]:
summary(model=model_resnet_brand_reg,
        input_size=(32, 3, 96, 160),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
ResNet                                   [32, 3, 96, 160]     [32, 8]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 64, 48, 80]     9,408                True
├─BatchNorm2d: 1-2                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─ReLU: 1-3                              [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-4                         [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-5                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    └─BasicBlock: 2-1                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-1                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-2             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-3                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-4                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-5             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-6                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    └─BasicBlock: 2-2                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-7                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-8             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-9                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-10                 [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-11            [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-12                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-6                        [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    └─BasicBlock: 2-3                   [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-13                 [32, 64, 24, 40]     [32, 128, 12, 20]    73,728               True
│    │    └─BatchNorm2d: 3-14            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-15                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-16                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-17            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─Sequential: 3-18             [32, 64, 24, 40]     [32, 128, 12, 20]    8,448                True
│    │    └─ReLU: 3-19                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    └─BasicBlock: 2-4                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-20                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-21            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-22                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-23                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-24            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-25                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Sequential: 1-7                        [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    └─BasicBlock: 2-5                   [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-26                 [32, 128, 12, 20]    [32, 256, 6, 10]     294,912              True
│    │    └─BatchNorm2d: 3-27            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-28                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-29                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-30            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─Sequential: 3-31             [32, 128, 12, 20]    [32, 256, 6, 10]     33,280               True
│    │    └─ReLU: 3-32                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    └─BasicBlock: 2-6                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-33                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-34            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-35                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-36                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-37            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-38                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Sequential: 1-8                        [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    └─BasicBlock: 2-7                   [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-39                 [32, 256, 6, 10]     [32, 512, 3, 5]      1,179,648            True
│    │    └─BatchNorm2d: 3-40            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-41                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-42                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-43            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─Sequential: 3-44             [32, 256, 6, 10]     [32, 512, 3, 5]      132,096              True
│    │    └─ReLU: 3-45                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    └─BasicBlock: 2-8                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-46                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-47            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-48                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-49                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-50            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-51                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
├─AdaptiveAvgPool2d: 1-9                 [32, 512, 3, 5]      [32, 512, 1, 1]      --                   --
├─Sequential: 1-10                       [32, 512]            [32, 8]              --                   True
│    └─Dropout: 2-9                      [32, 512]            [32, 512]            --                   --
│    └─Linear: 2-10                      [32, 512]            [32, 8]              4,104                True
========================================================================================================================
Total params: 11,180,616
Trainable params: 11,180,616
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 17.77
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 389.29
Params size (MB): 44.72
Estimated Total Size (MB): 439.91
========================================================================================================================

In [ ]:
main_kolesa_new(model_resnet_brand_reg, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_resnet_brand_reg, 'ResNet18_reg_finetune_brand')

Epoch: 1

100%|██████████| 97/97 [01:25<00:00,  1.14it/s]

Train set: Average loss: 1.2974, Accuracy: 44.02%
Val set: Average loss: 1.2707, Accuracy: 58.95%

Classification report:
               precision    recall  f1-score   support

         Audi       0.75      0.66      0.70        73
          BMW       0.76      0.88      0.81        90
    Chevrolet       0.48      0.87      0.62        79
      Hyundai       0.52      0.62      0.57        85
          Kia       0.59      0.39      0.47        77
        Lexus       0.52      0.48      0.50        95
Mercedes-Benz       0.61      0.68      0.64        81
       Toyota       0.52      0.14      0.22        85

     accuracy                           0.59       665
    macro avg       0.59      0.59      0.57       665
 weighted avg       0.59      0.59      0.57       665


Epoch: 2

100%|██████████| 97/97 [03:52<00:00,  2.39s/it]

Train set: Average loss: 0.9791, Accuracy: 66.65%
Val set: Average loss: 1.0123, Accuracy: 23.61%

Classification report:
               precision    recall  f1-score   support

         Audi       0.67      0.19      0.30        73
          BMW       0.80      0.18      0.29        90
    Chevrolet       0.57      0.15      0.24        79
      Hyundai       0.27      0.22      0.24        85
          Kia       0.13      0.78      0.22        77
        Lexus       0.53      0.19      0.28        95
Mercedes-Benz       1.00      0.16      0.28        81
       Toyota       0.71      0.06      0.11        85

     accuracy                           0.24       665
    macro avg       0.58      0.24      0.24       665
 weighted avg       0.59      0.24      0.24       665


Epoch: 3

100%|██████████| 97/97 [01:18<00:00,  1.23it/s]

Train set: Average loss: 0.6938, Accuracy: 75.86%
Val set: Average loss: 0.8980, Accuracy: 75.94%

Classification report:
               precision    recall  f1-score   support

         Audi       0.78      0.85      0.82        73
          BMW       0.86      0.90      0.88        90
    Chevrolet       0.71      0.90      0.79        79
      Hyundai       0.63      0.80      0.70        85
          Kia       0.77      0.71      0.74        77
        Lexus       0.76      0.66      0.71        95
Mercedes-Benz       0.90      0.74      0.81        81
       Toyota       0.71      0.53      0.61        85

     accuracy                           0.76       665
    macro avg       0.77      0.76      0.76       665
 weighted avg       0.77      0.76      0.76       665


Epoch: 4

100%|██████████| 97/97 [01:18<00:00,  1.23it/s]

Train set: Average loss: 0.6905, Accuracy: 82.31%
Val set: Average loss: 0.8249, Accuracy: 78.05%

Classification report:
               precision    recall  f1-score   support

         Audi       0.88      0.81      0.84        73
          BMW       0.84      0.90      0.87        90
    Chevrolet       0.74      0.85      0.79        79
      Hyundai       0.67      0.80      0.73        85
          Kia       0.81      0.71      0.76        77
        Lexus       0.74      0.74      0.74        95
Mercedes-Benz       0.87      0.85      0.86        81
       Toyota       0.72      0.59      0.65        85

     accuracy                           0.78       665
    macro avg       0.79      0.78      0.78       665
 weighted avg       0.78      0.78      0.78       665


Epoch: 5

100%|██████████| 97/97 [01:18<00:00,  1.23it/s]

Train set: Average loss: 0.6264, Accuracy: 86.50%
Val set: Average loss: 0.7911, Accuracy: 80.30%

Classification report:
               precision    recall  f1-score   support

         Audi       0.91      0.82      0.86        73
          BMW       0.91      0.90      0.91        90
    Chevrolet       0.74      0.89      0.80        79
      Hyundai       0.70      0.81      0.75        85
          Kia       0.77      0.74      0.75        77
        Lexus       0.81      0.72      0.76        95
Mercedes-Benz       0.90      0.89      0.89        81
       Toyota       0.73      0.67      0.70        85

     accuracy                           0.80       665
    macro avg       0.81      0.80      0.80       665
 weighted avg       0.81      0.80      0.80       665


Epoch: 6

100%|██████████| 97/97 [01:11<00:00,  1.37it/s]

Train set: Average loss: 0.4926, Accuracy: 90.14%
Val set: Average loss: 0.7679, Accuracy: 81.50%

Classification report:
               precision    recall  f1-score   support

         Audi       0.87      0.84      0.85        73
          BMW       0.87      0.89      0.88        90
    Chevrolet       0.72      0.91      0.80        79
      Hyundai       0.76      0.85      0.80        85
          Kia       0.87      0.71      0.79        77
        Lexus       0.80      0.77      0.78        95
Mercedes-Benz       0.84      0.88      0.86        81
       Toyota       0.84      0.68      0.75        85

     accuracy                           0.82       665
    macro avg       0.82      0.82      0.81       665
 weighted avg       0.82      0.82      0.81       665


Epoch: 7

100%|██████████| 97/97 [01:08<00:00,  1.42it/s]

Train set: Average loss: 0.4549, Accuracy: 92.88%
Val set: Average loss: 0.7430, Accuracy: 81.35%

Classification report:
               precision    recall  f1-score   support

         Audi       0.86      0.84      0.85        73
          BMW       0.91      0.89      0.90        90
    Chevrolet       0.73      0.91      0.81        79
      Hyundai       0.67      0.92      0.77        85
          Kia       0.86      0.71      0.78        77
        Lexus       0.89      0.74      0.80        95
Mercedes-Benz       0.85      0.86      0.86        81
       Toyota       0.83      0.65      0.73        85

     accuracy                           0.81       665
    macro avg       0.83      0.81      0.81       665
 weighted avg       0.83      0.81      0.81       665


Epoch: 8

100%|██████████| 97/97 [01:12<00:00,  1.34it/s]

Train set: Average loss: 0.4232, Accuracy: 95.17%
Val set: Average loss: 0.7186, Accuracy: 83.31%

Classification report:
               precision    recall  f1-score   support

         Audi       0.87      0.84      0.85        73
          BMW       0.92      0.89      0.90        90
    Chevrolet       0.73      0.91      0.81        79
      Hyundai       0.76      0.89      0.82        85
          Kia       0.88      0.78      0.83        77
        Lexus       0.85      0.79      0.82        95
Mercedes-Benz       0.85      0.88      0.86        81
       Toyota       0.84      0.69      0.76        85

     accuracy                           0.83       665
    macro avg       0.84      0.83      0.83       665
 weighted avg       0.84      0.83      0.83       665


Epoch: 9

100%|██████████| 97/97 [01:21<00:00,  1.19it/s]

Train set: Average loss: 0.3657, Accuracy: 96.52%
Val set: Average loss: 0.7200, Accuracy: 83.91%

Classification report:
               precision    recall  f1-score   support

         Audi       0.89      0.85      0.87        73
          BMW       0.87      0.90      0.89        90
    Chevrolet       0.76      0.94      0.84        79
      Hyundai       0.74      0.87      0.80        85
          Kia       0.86      0.79      0.82        77
        Lexus       0.90      0.75      0.82        95
Mercedes-Benz       0.91      0.86      0.89        81
       Toyota       0.84      0.76      0.80        85

     accuracy                           0.84       665
    macro avg       0.85      0.84      0.84       665
 weighted avg       0.85      0.84      0.84       665


Epoch: 10

100%|██████████| 97/97 [01:16<00:00,  1.27it/s]

Train set: Average loss: 0.3847, Accuracy: 97.13%
Val set: Average loss: 0.7246, Accuracy: 82.71%

Classification report:
               precision    recall  f1-score   support

         Audi       0.86      0.84      0.85        73
          BMW       0.91      0.89      0.90        90
    Chevrolet       0.74      0.95      0.83        79
      Hyundai       0.76      0.88      0.82        85
          Kia       0.84      0.82      0.83        77
        Lexus       0.91      0.72      0.80        95
Mercedes-Benz       0.84      0.88      0.86        81
       Toyota       0.81      0.67      0.74        85

     accuracy                           0.83       665
    macro avg       0.83      0.83      0.83       665
 weighted avg       0.83      0.83      0.83       665


Epoch: 11

100%|██████████| 97/97 [01:08<00:00,  1.41it/s]

Train set: Average loss: 0.3465, Accuracy: 97.97%
Val set: Average loss: 0.7086, Accuracy: 84.21%

Classification report:
               precision    recall  f1-score   support

         Audi       0.84      0.84      0.84        73
          BMW       0.89      0.91      0.90        90
    Chevrolet       0.79      0.95      0.86        79
      Hyundai       0.75      0.93      0.83        85
          Kia       0.90      0.81      0.85        77
        Lexus       0.88      0.76      0.81        95
Mercedes-Benz       0.86      0.88      0.87        81
       Toyota       0.88      0.68      0.77        85

     accuracy                           0.84       665
    macro avg       0.85      0.84      0.84       665
 weighted avg       0.85      0.84      0.84       665


Epoch: 12

100%|██████████| 97/97 [01:20<00:00,  1.20it/s]

Train set: Average loss: 0.3261, Accuracy: 98.68%
Val set: Average loss: 0.6849, Accuracy: 84.06%

Classification report:
               precision    recall  f1-score   support

         Audi       0.86      0.82      0.84        73
          BMW       0.90      0.87      0.88        90
    Chevrolet       0.80      0.92      0.86        79
      Hyundai       0.76      0.91      0.83        85
          Kia       0.87      0.84      0.86        77
        Lexus       0.86      0.80      0.83        95
Mercedes-Benz       0.84      0.88      0.86        81
       Toyota       0.87      0.69      0.77        85

     accuracy                           0.84       665
    macro avg       0.84      0.84      0.84       665
 weighted avg       0.84      0.84      0.84       665


Epoch: 13

100%|██████████| 97/97 [01:16<00:00,  1.26it/s]

Train set: Average loss: 0.3238, Accuracy: 99.19%
Val set: Average loss: 0.7005, Accuracy: 83.76%

Classification report:
               precision    recall  f1-score   support

         Audi       0.88      0.82      0.85        73
          BMW       0.90      0.90      0.90        90
    Chevrolet       0.84      0.91      0.87        79
      Hyundai       0.68      0.92      0.78        85
          Kia       0.90      0.81      0.85        77
        Lexus       0.92      0.74      0.82        95
Mercedes-Benz       0.85      0.88      0.86        81
       Toyota       0.81      0.74      0.77        85

     accuracy                           0.84       665
    macro avg       0.85      0.84      0.84       665
 weighted avg       0.85      0.84      0.84       665


Epoch: 14

100%|██████████| 97/97 [01:08<00:00,  1.42it/s]

Train set: Average loss: 0.3403, Accuracy: 99.26%
Val set: Average loss: 0.7004, Accuracy: 84.51%

Classification report:
               precision    recall  f1-score   support

         Audi       0.87      0.85      0.86        73
          BMW       0.88      0.90      0.89        90
    Chevrolet       0.77      0.92      0.84        79
      Hyundai       0.73      0.88      0.80        85
          Kia       0.90      0.82      0.86        77
        Lexus       0.89      0.80      0.84        95
Mercedes-Benz       0.88      0.88      0.88        81
       Toyota       0.90      0.72      0.80        85

     accuracy                           0.85       665
    macro avg       0.85      0.85      0.85       665
 weighted avg       0.85      0.85      0.85       665


Epoch: 15

100%|██████████| 97/97 [01:15<00:00,  1.28it/s]

Train set: Average loss: 0.3202, Accuracy: 99.65%
Val set: Average loss: 0.6829, Accuracy: 85.71%

Classification report:
               precision    recall  f1-score   support

         Audi       0.87      0.82      0.85        73
          BMW       0.89      0.90      0.90        90
    Chevrolet       0.79      0.95      0.86        79
      Hyundai       0.79      0.91      0.85        85
          Kia       0.89      0.81      0.84        77
        Lexus       0.89      0.83      0.86        95
Mercedes-Benz       0.88      0.89      0.88        81
       Toyota       0.89      0.75      0.82        85

     accuracy                           0.86       665
    macro avg       0.86      0.86      0.86       665
 weighted avg       0.86      0.86      0.86       665

Training is ended!
[OK] модель сохранена: models/ResNet18_reg_finetune_brand.pt

Модель переобучилась но качество сильно лучше. Добавим scheduler для снижения шага модели с каждой эпохой + добавим больше эпох и смягчим dropout

In [ ]:
def main_kolesa_new(model, train_df, val_df):

    if CFG.wandb:
        wandb.init(project=CFG.project, entity=CFG.entity, reinit=True, config=class2dict(CFG))
        # логируем архитектуру модели
        # https://docs.wandb.ai/guides/track/config
        wandb.config.update({'model': str(model)})

    seed_everything(CFG.seed)

    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')

    kwargs = {'num_workers': CFG.num_workers, 'pin_memory': torch.cuda.is_available()}

    # Попробуем картинки побольше
    # будем использовать различные методы аугментации https://docs.pytorch.org/vision/0.13/transforms.html
    train_transform = transforms.Compose([
        transforms.Resize((320, 512)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.1),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    test_transform = transforms.Compose([
        transforms.Resize((320, 512)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    train_ds = KolesaDataset(train_df, transform=train_transform)
    val_ds = KolesaDataset(val_df, transform=test_transform)
    # test_ds = KolesaDataset(test_df, transform=test_transform)

    train_loader = torch.utils.data.DataLoader(train_ds, batch_size=CFG.train_batch_size, **kwargs)
    val_loader = torch.utils.data.DataLoader(val_ds, batch_size=CFG.test_batch_size, **kwargs)
    # test_loader = torch.utils.data.DataLoader(test_ds, batch_size=CFG.test_batch_size, **kwargs)

    model = model.to(device)

    if CFG.wandb:
        wandb.watch(model, log='all')

    # https://habr.com/ru/articles/988198/
    # добавим l2 регуляризацию (weight_decay)
    optimizer = optim.Adam(model.parameters(),
                          lr=CFG.lr, weight_decay=3e-4)
    
    # https://discuss.pytorch.org/t/how-to-choose-learning-rate-and-scheduler/174319/4
    # https://www.kaggle.com/code/greatcodes/pytorch-cnn-resnet18-cifar10?scriptVersionId=42951150&cellId=12
    # добавим scheduler чтобы наш lr не был статическим
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)
    # добавим небольшой коэф. сглаживания, что может помочь с переобучением
    criterion = nn.CrossEntropyLoss(label_smoothing=0.05)

    for epoch in range(1, CFG.num_epochs + 1):
        print('\nEpoch:', epoch)
        train(model, device, train_loader, optimizer, criterion, epoch, CFG.wandb)
        val(model, device, val_loader, criterion, CFG.wandb)
        scheduler.step()

    print('Training is ended!')

In [ ]:
CFG.num_epochs = 20
CFG.lr = 3e-5
CFG.classes = all_brands
CFG.test_batch_size = 64 # иначе не хватает памяти с дефолтным 512
num_out_features = 8
# https://discuss.pytorch.org/t/resnet-last-layer-modification/33530
model_resnet_brand_reg_v2 = resnet18(weights=ResNet18_Weights.DEFAULT)
model_resnet_brand_reg_v2.fc = nn.Sequential(
    nn.Dropout(0.3),
    nn.Linear(model_resnet_brand_reg_v2.fc.in_features, num_out_features)
)

In [ ]:
summary(model=model_resnet_brand_reg_v2,
        input_size=(32, 3, 320, 512),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
ResNet                                   [32, 3, 320, 512]    [32, 8]              --                   True
├─Conv2d: 1-1                            [32, 3, 320, 512]    [32, 64, 160, 256]   9,408                True
├─BatchNorm2d: 1-2                       [32, 64, 160, 256]   [32, 64, 160, 256]   128                  True
├─ReLU: 1-3                              [32, 64, 160, 256]   [32, 64, 160, 256]   --                   --
├─MaxPool2d: 1-4                         [32, 64, 160, 256]   [32, 64, 80, 128]    --                   --
├─Sequential: 1-5                        [32, 64, 80, 128]    [32, 64, 80, 128]    --                   True
│    └─BasicBlock: 2-1                   [32, 64, 80, 128]    [32, 64, 80, 128]    --                   True
│    │    └─Conv2d: 3-1                  [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-2             [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-3                    [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
│    │    └─Conv2d: 3-4                  [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-5             [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-6                    [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
│    └─BasicBlock: 2-2                   [32, 64, 80, 128]    [32, 64, 80, 128]    --                   True
│    │    └─Conv2d: 3-7                  [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-8             [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-9                    [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
│    │    └─Conv2d: 3-10                 [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-11            [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-12                   [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
├─Sequential: 1-6                        [32, 64, 80, 128]    [32, 128, 40, 64]    --                   True
│    └─BasicBlock: 2-3                   [32, 64, 80, 128]    [32, 128, 40, 64]    --                   True
│    │    └─Conv2d: 3-13                 [32, 64, 80, 128]    [32, 128, 40, 64]    73,728               True
│    │    └─BatchNorm2d: 3-14            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─ReLU: 3-15                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
│    │    └─Conv2d: 3-16                 [32, 128, 40, 64]    [32, 128, 40, 64]    147,456              True
│    │    └─BatchNorm2d: 3-17            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─Sequential: 3-18             [32, 64, 80, 128]    [32, 128, 40, 64]    8,448                True
│    │    └─ReLU: 3-19                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
│    └─BasicBlock: 2-4                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   True
│    │    └─Conv2d: 3-20                 [32, 128, 40, 64]    [32, 128, 40, 64]    147,456              True
│    │    └─BatchNorm2d: 3-21            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─ReLU: 3-22                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
│    │    └─Conv2d: 3-23                 [32, 128, 40, 64]    [32, 128, 40, 64]    147,456              True
│    │    └─BatchNorm2d: 3-24            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─ReLU: 3-25                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
├─Sequential: 1-7                        [32, 128, 40, 64]    [32, 256, 20, 32]    --                   True
│    └─BasicBlock: 2-5                   [32, 128, 40, 64]    [32, 256, 20, 32]    --                   True
│    │    └─Conv2d: 3-26                 [32, 128, 40, 64]    [32, 256, 20, 32]    294,912              True
│    │    └─BatchNorm2d: 3-27            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─ReLU: 3-28                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
│    │    └─Conv2d: 3-29                 [32, 256, 20, 32]    [32, 256, 20, 32]    589,824              True
│    │    └─BatchNorm2d: 3-30            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─Sequential: 3-31             [32, 128, 40, 64]    [32, 256, 20, 32]    33,280               True
│    │    └─ReLU: 3-32                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
│    └─BasicBlock: 2-6                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   True
│    │    └─Conv2d: 3-33                 [32, 256, 20, 32]    [32, 256, 20, 32]    589,824              True
│    │    └─BatchNorm2d: 3-34            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─ReLU: 3-35                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
│    │    └─Conv2d: 3-36                 [32, 256, 20, 32]    [32, 256, 20, 32]    589,824              True
│    │    └─BatchNorm2d: 3-37            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─ReLU: 3-38                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
├─Sequential: 1-8                        [32, 256, 20, 32]    [32, 512, 10, 16]    --                   True
│    └─BasicBlock: 2-7                   [32, 256, 20, 32]    [32, 512, 10, 16]    --                   True
│    │    └─Conv2d: 3-39                 [32, 256, 20, 32]    [32, 512, 10, 16]    1,179,648            True
│    │    └─BatchNorm2d: 3-40            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─ReLU: 3-41                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
│    │    └─Conv2d: 3-42                 [32, 512, 10, 16]    [32, 512, 10, 16]    2,359,296            True
│    │    └─BatchNorm2d: 3-43            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─Sequential: 3-44             [32, 256, 20, 32]    [32, 512, 10, 16]    132,096              True
│    │    └─ReLU: 3-45                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
│    └─BasicBlock: 2-8                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   True
│    │    └─Conv2d: 3-46                 [32, 512, 10, 16]    [32, 512, 10, 16]    2,359,296            True
│    │    └─BatchNorm2d: 3-47            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─ReLU: 3-48                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
│    │    └─Conv2d: 3-49                 [32, 512, 10, 16]    [32, 512, 10, 16]    2,359,296            True
│    │    └─BatchNorm2d: 3-50            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─ReLU: 3-51                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
├─AdaptiveAvgPool2d: 1-9                 [32, 512, 10, 16]    [32, 512, 1, 1]      --                   --
├─Sequential: 1-10                       [32, 512]            [32, 8]              --                   True
│    └─Dropout: 2-9                      [32, 512]            [32, 512]            --                   --
│    └─Linear: 2-10                      [32, 512]            [32, 8]              4,104                True
========================================================================================================================
Total params: 11,180,616
Trainable params: 11,180,616
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 189.50
========================================================================================================================
Input size (MB): 62.91
Forward/backward pass size (MB): 4152.36
Params size (MB): 44.72
Estimated Total Size (MB): 4260.00
========================================================================================================================

In [ ]:
main_kolesa_new(model_resnet_brand_reg_v2, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_resnet_brand_reg_v2, 'ResNet18_reg_finetune_brand_v2')

Epoch: 1

100%|██████████| 97/97 [01:02<00:00,  1.56it/s]

Train set: Average loss: 1.8958, Accuracy: 23.11%
Val set: Average loss: 1.8351, Accuracy: 43.61%

Classification report:
               precision    recall  f1-score   support

         Audi       0.69      0.55      0.61        73
          BMW       0.46      0.84      0.60        90
    Chevrolet       0.45      0.57      0.50        79
      Hyundai       0.37      0.31      0.33        85
          Kia       0.41      0.43      0.42        77
        Lexus       0.28      0.36      0.31        95
Mercedes-Benz       0.60      0.33      0.43        81
       Toyota       0.43      0.11      0.17        85

     accuracy                           0.44       665
    macro avg       0.46      0.44      0.42       665
 weighted avg       0.45      0.44      0.42       665


Epoch: 2

100%|██████████| 97/97 [01:03<00:00,  1.53it/s]

Train set: Average loss: 1.3273, Accuracy: 50.27%
Val set: Average loss: 1.3157, Accuracy: 65.56%

Classification report:
               precision    recall  f1-score   support

         Audi       0.70      0.75      0.72        73
          BMW       0.86      0.83      0.85        90
    Chevrolet       0.73      0.81      0.77        79
      Hyundai       0.55      0.65      0.59        85
          Kia       0.71      0.53      0.61        77
        Lexus       0.44      0.72      0.54        95
Mercedes-Benz       0.82      0.68      0.74        81
       Toyota       0.77      0.27      0.40        85

     accuracy                           0.66       665
    macro avg       0.70      0.66      0.65       665
 weighted avg       0.69      0.66      0.65       665


Epoch: 3

100%|██████████| 97/97 [01:04<00:00,  1.51it/s]

Train set: Average loss: 0.8711, Accuracy: 68.77%
Val set: Average loss: 1.0598, Accuracy: 73.53%

Classification report:
               precision    recall  f1-score   support

         Audi       0.74      0.77      0.75        73
          BMW       0.94      0.83      0.88        90
    Chevrolet       0.72      0.90      0.80        79
      Hyundai       0.64      0.72      0.67        85
          Kia       0.76      0.68      0.72        77
        Lexus       0.59      0.72      0.64        95
Mercedes-Benz       0.83      0.70      0.76        81
       Toyota       0.79      0.58      0.67        85

     accuracy                           0.74       665
    macro avg       0.75      0.74      0.74       665
 weighted avg       0.75      0.74      0.74       665


Epoch: 4

100%|██████████| 97/97 [01:03<00:00,  1.53it/s]

Train set: Average loss: 0.7796, Accuracy: 78.18%
Val set: Average loss: 0.9803, Accuracy: 78.20%

Classification report:
               precision    recall  f1-score   support

         Audi       0.82      0.79      0.81        73
          BMW       0.93      0.87      0.90        90
    Chevrolet       0.73      0.94      0.82        79
      Hyundai       0.66      0.76      0.71        85
          Kia       0.84      0.74      0.79        77
        Lexus       0.65      0.78      0.71        95
Mercedes-Benz       0.88      0.78      0.82        81
       Toyota       0.89      0.60      0.72        85

     accuracy                           0.78       665
    macro avg       0.80      0.78      0.78       665
 weighted avg       0.80      0.78      0.78       665


Epoch: 5

100%|██████████| 97/97 [01:03<00:00,  1.53it/s]

Train set: Average loss: 0.6468, Accuracy: 82.79%
Val set: Average loss: 0.9252, Accuracy: 81.20%

Classification report:
               precision    recall  f1-score   support

         Audi       0.86      0.81      0.83        73
          BMW       0.94      0.87      0.90        90
    Chevrolet       0.72      0.94      0.81        79
      Hyundai       0.71      0.80      0.75        85
          Kia       0.88      0.79      0.84        77
        Lexus       0.78      0.79      0.79        95
Mercedes-Benz       0.82      0.80      0.81        81
       Toyota       0.86      0.71      0.77        85

     accuracy                           0.81       665
    macro avg       0.82      0.81      0.81       665
 weighted avg       0.82      0.81      0.81       665


Epoch: 6

100%|██████████| 97/97 [01:01<00:00,  1.57it/s]

Train set: Average loss: 0.5377, Accuracy: 87.37%
Val set: Average loss: 0.8662, Accuracy: 82.56%

Classification report:
               precision    recall  f1-score   support

         Audi       0.84      0.81      0.83        73
          BMW       0.94      0.88      0.91        90
    Chevrolet       0.83      0.91      0.87        79
      Hyundai       0.72      0.85      0.78        85
          Kia       0.91      0.79      0.85        77
        Lexus       0.72      0.83      0.77        95
Mercedes-Benz       0.83      0.83      0.83        81
       Toyota       0.90      0.71      0.79        85

     accuracy                           0.83       665
    macro avg       0.84      0.83      0.83       665
 weighted avg       0.83      0.83      0.83       665


Epoch: 7

100%|██████████| 97/97 [01:01<00:00,  1.59it/s]

Train set: Average loss: 0.5842, Accuracy: 89.59%
Val set: Average loss: 0.8436, Accuracy: 83.01%

Classification report:
               precision    recall  f1-score   support

         Audi       0.81      0.84      0.82        73
          BMW       0.98      0.89      0.93        90
    Chevrolet       0.83      0.91      0.87        79
      Hyundai       0.70      0.88      0.78        85
          Kia       0.88      0.82      0.85        77
        Lexus       0.75      0.81      0.78        95
Mercedes-Benz       0.86      0.81      0.84        81
       Toyota       0.92      0.68      0.78        85

     accuracy                           0.83       665
    macro avg       0.84      0.83      0.83       665
 weighted avg       0.84      0.83      0.83       665


Epoch: 8

100%|██████████| 97/97 [01:00<00:00,  1.59it/s]

Train set: Average loss: 0.5009, Accuracy: 91.72%
Val set: Average loss: 0.8335, Accuracy: 83.16%

Classification report:
               precision    recall  f1-score   support

         Audi       0.85      0.82      0.83        73
          BMW       0.94      0.89      0.91        90
    Chevrolet       0.83      0.91      0.87        79
      Hyundai       0.70      0.88      0.78        85
          Kia       0.89      0.81      0.84        77
        Lexus       0.78      0.82      0.80        95
Mercedes-Benz       0.87      0.83      0.85        81
       Toyota       0.87      0.69      0.77        85

     accuracy                           0.83       665
    macro avg       0.84      0.83      0.83       665
 weighted avg       0.84      0.83      0.83       665


Epoch: 9

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.4641, Accuracy: 92.68%
Val set: Average loss: 0.8129, Accuracy: 84.96%

Classification report:
               precision    recall  f1-score   support

         Audi       0.84      0.84      0.84        73
          BMW       0.94      0.91      0.93        90
    Chevrolet       0.81      0.92      0.86        79
      Hyundai       0.77      0.89      0.83        85
          Kia       0.91      0.82      0.86        77
        Lexus       0.83      0.82      0.83        95
Mercedes-Benz       0.86      0.84      0.85        81
       Toyota       0.86      0.75      0.81        85

     accuracy                           0.85       665
    macro avg       0.85      0.85      0.85       665
 weighted avg       0.85      0.85      0.85       665


Epoch: 10

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.4238, Accuracy: 94.04%
Val set: Average loss: 0.8132, Accuracy: 84.51%

Classification report:
               precision    recall  f1-score   support

         Audi       0.82      0.85      0.83        73
          BMW       0.93      0.90      0.92        90
    Chevrolet       0.83      0.95      0.89        79
      Hyundai       0.77      0.87      0.82        85
          Kia       0.88      0.83      0.85        77
        Lexus       0.82      0.81      0.81        95
Mercedes-Benz       0.87      0.81      0.84        81
       Toyota       0.86      0.74      0.80        85

     accuracy                           0.85       665
    macro avg       0.85      0.85      0.84       665
 weighted avg       0.85      0.85      0.84       665


Epoch: 11

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.3952, Accuracy: 95.07%
Val set: Average loss: 0.7950, Accuracy: 84.36%

Classification report:
               precision    recall  f1-score   support

         Audi       0.82      0.82      0.82        73
          BMW       0.93      0.90      0.92        90
    Chevrolet       0.85      0.90      0.87        79
      Hyundai       0.76      0.86      0.81        85
          Kia       0.89      0.83      0.86        77
        Lexus       0.79      0.86      0.82        95
Mercedes-Benz       0.84      0.83      0.83        81
       Toyota       0.91      0.74      0.82        85

     accuracy                           0.84       665
    macro avg       0.85      0.84      0.84       665
 weighted avg       0.85      0.84      0.84       665


Epoch: 12

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.4453, Accuracy: 95.65%
Val set: Average loss: 0.7745, Accuracy: 84.36%

Classification report:
               precision    recall  f1-score   support

         Audi       0.84      0.79      0.82        73
          BMW       0.93      0.91      0.92        90
    Chevrolet       0.85      0.90      0.87        79
      Hyundai       0.74      0.89      0.81        85
          Kia       0.88      0.82      0.85        77
        Lexus       0.81      0.84      0.82        95
Mercedes-Benz       0.87      0.84      0.86        81
       Toyota       0.88      0.74      0.80        85

     accuracy                           0.84       665
    macro avg       0.85      0.84      0.84       665
 weighted avg       0.85      0.84      0.84       665


Epoch: 13

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.4323, Accuracy: 96.10%
Val set: Average loss: 0.7930, Accuracy: 84.36%

Classification report:
               precision    recall  f1-score   support

         Audi       0.82      0.81      0.81        73
          BMW       0.93      0.89      0.91        90
    Chevrolet       0.84      0.91      0.87        79
      Hyundai       0.75      0.89      0.81        85
          Kia       0.90      0.82      0.86        77
        Lexus       0.83      0.83      0.83        95
Mercedes-Benz       0.86      0.84      0.85        81
       Toyota       0.85      0.75      0.80        85

     accuracy                           0.84       665
    macro avg       0.85      0.84      0.84       665
 weighted avg       0.85      0.84      0.84       665


Epoch: 14

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.3684, Accuracy: 96.04%
Val set: Average loss: 0.7862, Accuracy: 84.66%

Classification report:
               precision    recall  f1-score   support

         Audi       0.86      0.81      0.83        73
          BMW       0.93      0.89      0.91        90
    Chevrolet       0.85      0.90      0.87        79
      Hyundai       0.75      0.88      0.81        85
          Kia       0.89      0.83      0.86        77
        Lexus       0.80      0.86      0.83        95
Mercedes-Benz       0.85      0.84      0.84        81
       Toyota       0.89      0.75      0.82        85

     accuracy                           0.85       665
    macro avg       0.85      0.85      0.85       665
 weighted avg       0.85      0.85      0.85       665


Epoch: 15

100%|██████████| 97/97 [01:01<00:00,  1.59it/s]

Train set: Average loss: 0.3590, Accuracy: 96.91%
Val set: Average loss: 0.7987, Accuracy: 85.11%

Classification report:
               precision    recall  f1-score   support

         Audi       0.84      0.81      0.83        73
          BMW       0.93      0.90      0.92        90
    Chevrolet       0.85      0.90      0.87        79
      Hyundai       0.77      0.88      0.82        85
          Kia       0.90      0.84      0.87        77
        Lexus       0.80      0.87      0.83        95
Mercedes-Benz       0.85      0.85      0.85        81
       Toyota       0.90      0.74      0.81        85

     accuracy                           0.85       665
    macro avg       0.86      0.85      0.85       665
 weighted avg       0.86      0.85      0.85       665


Epoch: 16

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.3863, Accuracy: 97.20%
Val set: Average loss: 0.7854, Accuracy: 85.41%

Classification report:
               precision    recall  f1-score   support

         Audi       0.85      0.79      0.82        73
          BMW       0.93      0.90      0.92        90
    Chevrolet       0.86      0.90      0.88        79
      Hyundai       0.75      0.93      0.83        85
          Kia       0.92      0.84      0.88        77
        Lexus       0.82      0.85      0.84        95
Mercedes-Benz       0.86      0.85      0.86        81
       Toyota       0.89      0.75      0.82        85

     accuracy                           0.85       665
    macro avg       0.86      0.85      0.85       665
 weighted avg       0.86      0.85      0.85       665


Epoch: 17

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.3804, Accuracy: 97.23%
Val set: Average loss: 0.7815, Accuracy: 85.56%

Classification report:
               precision    recall  f1-score   support

         Audi       0.86      0.82      0.84        73
          BMW       0.93      0.90      0.92        90
    Chevrolet       0.85      0.90      0.87        79
      Hyundai       0.77      0.91      0.83        85
          Kia       0.92      0.84      0.88        77
        Lexus       0.80      0.86      0.83        95
Mercedes-Benz       0.86      0.85      0.86        81
       Toyota       0.90      0.75      0.82        85

     accuracy                           0.86       665
    macro avg       0.86      0.85      0.86       665
 weighted avg       0.86      0.86      0.86       665


Epoch: 18

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.3548, Accuracy: 97.81%
Val set: Average loss: 0.7807, Accuracy: 85.71%

Classification report:
               precision    recall  f1-score   support

         Audi       0.86      0.82      0.84        73
          BMW       0.93      0.90      0.92        90
    Chevrolet       0.86      0.90      0.88        79
      Hyundai       0.77      0.91      0.83        85
          Kia       0.90      0.84      0.87        77
        Lexus       0.80      0.86      0.83        95
Mercedes-Benz       0.89      0.86      0.88        81
       Toyota       0.89      0.75      0.82        85

     accuracy                           0.86       665
    macro avg       0.86      0.86      0.86       665
 weighted avg       0.86      0.86      0.86       665


Epoch: 19

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.3866, Accuracy: 97.71%
Val set: Average loss: 0.7781, Accuracy: 85.71%

Classification report:
               precision    recall  f1-score   support

         Audi       0.85      0.82      0.83        73
          BMW       0.93      0.90      0.92        90
    Chevrolet       0.86      0.90      0.88        79
      Hyundai       0.76      0.94      0.84        85
          Kia       0.93      0.83      0.88        77
        Lexus       0.82      0.86      0.84        95
Mercedes-Benz       0.88      0.84      0.86        81
       Toyota       0.88      0.75      0.81        85

     accuracy                           0.86       665
    macro avg       0.86      0.86      0.86       665
 weighted avg       0.86      0.86      0.86       665


Epoch: 20

100%|██████████| 97/97 [01:00<00:00,  1.60it/s]

Train set: Average loss: 0.3690, Accuracy: 97.68%
Val set: Average loss: 0.7621, Accuracy: 85.71%

Classification report:
               precision    recall  f1-score   support

         Audi       0.85      0.82      0.83        73
          BMW       0.93      0.90      0.92        90
    Chevrolet       0.86      0.90      0.88        79
      Hyundai       0.75      0.94      0.84        85
          Kia       0.93      0.82      0.87        77
        Lexus       0.82      0.86      0.84        95
Mercedes-Benz       0.87      0.85      0.86        81
       Toyota       0.90      0.75      0.82        85

     accuracy                           0.86       665
    macro avg       0.86      0.86      0.86       665
 weighted avg       0.86      0.86      0.86       665

Training is ended!
[OK] модель сохранена: models/ResNet18_reg_finetune_brand_v2.pt

ResNet18 показала лучший результат среди всех архитектур: на валидации accuracy 87.5% и macro-F1 0.86, с уверенным распознаванием обоих классов (sedan F1 0.90, SUV F1 0.82).

Также можно отметить, что модель обучилась быстро, так как к 3-ей эпохе вышло на плато, превосходя значительно остальные модели.

На последней эпохе есть переобучение (98% accuracy на тесте).

## Сравнение и выводы