# Глубинное обучение на табличных данных

Начнем конечно с импортов различных, которые понадобятся далее. Также, многое отсюда было реализовано с помощью функций копипаста с семинаров, что мы проходили, помимо этого, семинары дали вдохновление на именно такой пайплайн действий) Стоило упомянуть

In [22]:
import pandas as pd
import numpy as np
import random

import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader #чтобы подавать данные батчами

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score #для подсчета качества

import os
import wandb

Объявим класс конфига

In [23]:
class CFG:
  project = "kolesa-cars"
  entity = "armntvs-d3v-student"
  num_epochs = 15
  train_batch_size = 64
  test_batch_size = 256
  lr = 0.001
  seed = 42
  wandb = True

In [24]:
# конфиг в словарь
def class2dict(f):
  return dict((name, getattr(f, name)) for name in dir(f) if not name.startswith('__'))

In [25]:
# вход в W&B (ключ спросит один раз)
wandb.login()

True

Зафиксируем сиды

In [26]:
def seed_everything(seed): # чтобы запуски были стабильными и воспроизводимымми
    random.seed(seed) # фиксируем генератор случайных чисел
    np.random.seed(seed) # фиксируем генератор случайных чисел numpy
    torch.manual_seed(seed) # фиксируем генератор случайных чисел pytorch
    torch.cuda.manual_seed(seed) # фиксируем генератор случайных чисел для GPU

In [27]:
# https://stackoverflow.com/questions/63423463/using-pytorch-cuda-on-macbook-pro
# т.к. на macbook на их процессорах apple silicon нет cuda (только для карт nvidia), то используем альтеранативу, но если есть cuda - то используем ее
if torch.cuda.is_available():
    device = torch.device('cuda')
elif torch.backends.mps.is_available():
    device = torch.device('mps')
else:
    device = torch.device('cpu')

device

device(type='mps')

Загрузим все предобработанные данные

In [28]:
X_train = pd.read_csv('../data/X_train.csv')
X_test = pd.read_csv('../data/X_test.csv')
y_train = pd.read_csv('../data/y_train.csv')
y_test = pd.read_csv('../data/y_test.csv')

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4236, 570), (1060, 570), (4236, 1), (1060, 1))

Когда переводил в тензоры выдавало ошибку, потому что нужны флоат, а там видимо от ohe остались bool, переведем это все в флоат и пойдем дальше

In [29]:
X_train = X_train.astype(float)
X_test = X_test.astype(float)
y_train = y_train.astype(float)
y_test = y_test.astype(float)

Переведем все в тензоры

In [30]:
X_train_tensor =torch.FloatTensor(X_train.values)
X_test_tensor =torch.FloatTensor(X_test.values)
y_train_tensor =torch.FloatTensor(y_train.values)
y_test_tensor =torch.FloatTensor(y_test.values)

X_train_tensor.shape, y_train_tensor.shape

(torch.Size([4236, 570]), torch.Size([4236, 1]))

Теперь соединим это обратно в датасеты (train/test), чтобы передавать в модели именно все признаки с таргетом, после чего создадим dataloader чтобы подавать в модель данные батчами/частями

In [31]:
train_ds = TensorDataset(X_train_tensor,y_train_tensor)
test_ds = TensorDataset(X_test_tensor,y_test_tensor)

train_ds

In [32]:
train_loader = DataLoader(train_ds, batch_size= CFG.train_batch_size, shuffle=True) #shuffle тут чтобы между эпохами перемешивались строки и модель не привыкала к порядку
test_loader = DataLoader(test_ds, batch_size= CFG.test_batch_size)

In [33]:
input_size = X_train.shape[1]
input_size

570

Сейчас построим достаточно базовую модель (вдохновление от 15 семинара). Архитектура простая - 3 полносвязных слоя и все. Далее будем строить несколько более сложных архитектур. Сначала простую чтобы понимать, помогают ли нам новые архитектуры улучшить так скажем 'базовое' качество.

In [34]:
class Simple(nn.Module): # наследуемся от класса nn.Module
    def __init__(self, input_size):
        super().__init__()
        self.fc1 = nn.Linear(input_size, 128) # первый скрытый слой - 128 нейронов
        self.fc2 = nn.Linear(128, 64) # второй скрытый - 64
        self.fc3 = nn.Linear(64, 1) # третий  выходной- 1 прогноз
        
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x) 
        return x

Теперь построим более сложную (чуть) архитектуру. Попробуем добавить просто больше скрытых слоев и добавим еще больше нейронов 

Но, при этом, есильно выше риск переобучения, поэтому будем все это сравнивать на качестве теста

In [35]:
class Deep(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        
        self.fc1 = nn.Linear(input_size, 512) #теперь начинаем уменьшение размерности с 512 
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, 128)
        self.fc4 = nn.Linear(128, 64)
        self.fc5 = nn.Linear(64, 1)
        
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.relu(self.fc3(x))
        x = torch.relu(self.fc4(x))
        x = self.fc5(x)
        return x

И, добавим третью модель, тут мы добавим еще дропаут и батчнорм. Первый будет бороться с переобучением за счет отключения определенного количества нейронов во время обучения. Батчнорм будет просто стабилизировать значения внутри срктытых слоев

In [36]:
class Regularized(nn.Module):
    def __init__(self, input_size):
        super().__init__()


        self.net = nn.Sequential(nn.Linear(input_size, 256), nn.BatchNorm1d(256), nn.ReLU(), nn.Dropout(0.05), #1 скрытый 
                                 nn.Linear(256, 128), nn.BatchNorm1d(128), nn.ReLU(),nn.Dropout(0.05),  #2 скрытый
                                 nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))    #3 скрытый и 4 выходной
        #sequential тут потому что во первых мы так работали на семинарах, а во-вторых потому что слои и операции в них просто идут по порядку
        #без сложностей , и следующая функция красивая в 2 строки получается )))

    def forward(self, x):
        return self.net(x)

Мы решили добавить еще одну полнсвязную сеть с residual connection. Его преимущество в том, что он сохраняет вход блока и добавляет к выходу. То есь, это хорошо потому что мы по идее не теряем юзфул информацию когда проходим несколько слоев. В нашем случае, это полезно потому что после ohe у нас стало много признаков, и там есть важные признаки ,которые residual mlp поможет учитывать в каких то сложных комбинациях

Сайты, в том числе откуда и вдохновение на код:
- https://discuss.pytorch.org/t/how-to-use-residual-learning-applied-to-fully-connected-networks/98708/5
- https://stackoverflow.com/questions/60817390/implementing-a-simple-resnet-block-with-pytorch

In [37]:
class ResBlock(nn.Module):
    def __init__(self, hidden_size):
        super().__init__()
        
        self.fc1 = nn.Linear(hidden_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        
    def forward(self, x):
        residual = x  # сохраняем вход блока
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        x = x + residual  # прибавляем старый x к новому x
        x = torch.relu(x)
        
        return x

In [38]:
class ResMLP(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        
        self.fc1 = nn.Linear(input_size, 256)
        self.block1 = ResBlock(256)
        self.block2 = ResBlock(256)
        self.fc2 = nn.Linear(256, 1)
        
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.block1(x)
        x = self.block2(x)
        x = self.fc2(x)
        return x

Далее, переходим к следующей части , пока просто зададим функцию потерь и потом напишем фукнцию обучения

In [39]:
criterion = nn.MSELoss()

In [40]:
from tqdm import tqdm

def train(model, device, train_loader, optimizer, criterion, epoch, WANDB): 
    model.train()
    train_loss = 0
    
    for data, target in tqdm(train_loader):
        data = data.to(device)
        target = target.to(device)
        
        optimizer.zero_grad() #обнуяем градиенты
        
        output = model(data) #прямой проход
        loss = criterion(output, target) #считаем ошибку
        
        loss.backward() #обратынй проход
        optimizer.step() #шаг оптимизатором
        train_loss += loss.item()
    
    train_loss = train_loss / len(train_loader)
    
    tqdm.write('\nTrain set: Average loss: {:.4f}'.format(train_loss)) #как в семе, но чуть поправленная, потому что там для картинок

    if WANDB:
        wandb.log({'epoch': epoch,
                   'train_loss': train_loss})
        
    return train_loss

Теперь функция тестирования, оч похожа на сем, но там картинки

In [41]:
def test(model, device, test_loader, criterion, epoch, WANDB):
    model.eval()  
    
    test_loss = 0
    preds = []
    true = []
    
    # показываем, что обучения нет и градиенты не обновляются
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            
            output = model(data)
            test_loss += criterion(output, target).item()
            
            preds.append(output.cpu())
            true.append(target.cpu())
    
    test_loss = test_loss / len(test_loader)
    
    preds = torch.cat(preds).numpy().ravel() #тут мы клеим прогнозы в одномерный массив нампай 
    true = torch.cat(true).numpy().ravel()
    
    preds = np.expm1(preds) #возвращаем логарифмированные числа в первоначальное 
    true = np.expm1(true)
    
    mae = mean_absolute_error(true, preds)
    rmse = np.sqrt(mean_squared_error(true, preds))
    r2 = r2_score(true, preds)
    
    tqdm.write('Test set: Average loss: {:.4f}, MAE: {:.2f}, RMSE: {:.2f}, R2: {:.4f}'.format(
       test_loss, mae, rmse, r2))
    
    if WANDB:
        wandb.log({'epoch': epoch,
                   'test_loss': test_loss,
                   'test_mae': mae,
                   'test_rmse': rmse,
                   'test_r2': r2})
    
    return test_loss, mae, rmse, r2

Теперь нужна функция запуска наших экспериментов, и после этого можно будет лицезреть качество выстроенных нами моделей))

In [42]:
# основная функция для экспериментов
def main(model, model_name):

    if CFG.wandb:
        wandb.init(project=CFG.project, entity=CFG.entity, name=model_name, reinit=True, config=class2dict(CFG)) #reinit чтобы каждый экспер записывался как новый
        # параметры архитектуры https://docs.wandb.ai/guides/track/config
        wandb.config.update({'model': str(model)})
    seed_everything(CFG.seed)  # фиксируем сиды
    
    model = model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=CFG.lr)
    
    train_losses = []
    test_losses = []
    best_mae =10**20
    
    if CFG.wandb:
        wandb.watch(model, log='all') # логируем все (метрики, лоссы, градиенты)


    for epoch in range(1, CFG.num_epochs + 1):
        print('\nEpoch:', epoch)
        train_loss = train(model, device, train_loader, optimizer, criterion, epoch, CFG.wandb)
        test_loss, mae, rmse, r2 = test(model, device, test_loader, criterion, epoch, CFG.wandb)
        train_losses.append(train_loss)
        test_losses.append(test_loss)

        if mae < best_mae:
            best_mae = mae
            best_test_loss = test_loss
            best_rmse = rmse
            best_r2 = r2
    
    print('Training is ended!')
    
    
    if CFG.wandb:
        # сохраняем модель артефактом https://docs.wandb.ai/guides/artifacts
        torch.save(model.state_dict(), f'../data/models/{model_name}.pt')
        artifact = wandb.Artifact(model_name, type='model')
        artifact.add_file(f'../data/models/{model_name}.pt')
        wandb.log_artifact(artifact)
        wandb.finish()

    return model, train_losses, test_losses, best_test_loss, best_mae, best_rmse, best_r2

In [22]:
# данные в W&B для воспроизводимости https://docs.wandb.ai/guides/artifacts
# выполнить один раз
if CFG.wandb:
    wandb.init(project=CFG.project, entity=CFG.entity, name='dataset-tabular', reinit=True)
    art = wandb.Artifact('kolesa-tabular', type='dataset')
    for f in ['X_train.csv', 'X_test.csv', 'y_train.csv', 'y_test.csv']:
        art.add_file(f'../data/{f}')
    wandb.log_artifact(art)
    wandb.finish()

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

KeyboardInterrupt:

Error in callback <bound method _WandbInit._post_run_cell_hook of <wandb.sdk.wandb_init._WandbInit object at 0x1307c2a50>> (for post_run_cell), with arguments args (<ExecutionResult object at 134691080, execution_count=22 error_before_exec=None error_in_exec= info=<ExecutionInfo object at 134766fd0, raw_cell="# данные в W&B для воспроизводимости https://docs..." transformed_cell="# данные в W&B для воспроизводимости https://docs..." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/Users/ksa/smadimo/dev_gp5/gp_5_DL/notebooks/mlp_tab.ipynb#X50sZmlsZQ%3D%3D> result=None>,),kwargs {}:

ConnectionResetError: Connection lost

In [43]:
seed_everything(CFG.seed)
simple_model, simple_train_losses, simple_test_losses, simple_test_loss, simple_mae, simple_rmse, simple_r2 = main(Simple(input_size),'Simple')

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

Epoch: 1

100%|██████████| 67/67 [00:01<00:00, 48.77it/s]

Train set: Average loss: 154.6181
Test set: Average loss: 6.3434, MAE: 175640176.00, RMSE: 442042511.01, R2: -1896.2131

Epoch: 2

100%|██████████| 67/67 [00:00<00:00, 546.32it/s]

Train set: Average loss: 3.1786
Test set: Average loss: 1.8145, MAE: 11987412.00, RMSE: 21867715.81, R2: -3.6430

Epoch: 3

100%|██████████| 67/67 [00:00<00:00, 579.47it/s]

Train set: Average loss: 1.3385
Test set: Average loss: 1.2831, MAE: 10020003.00, RMSE: 18865890.54, R2: -2.4558

Epoch: 4

100%|██████████| 67/67 [00:00<00:00, 507.45it/s]

Train set: Average loss: 0.8693
Test set: Average loss: 0.9333, MAE: 7393583.50, RMSE: 15917357.45, R2: -1.4600

Epoch: 5

100%|██████████| 67/67 [00:00<00:00, 545.59it/s]

Train set: Average loss: 0.5539
Test set: Average loss: 0.6744, MAE: 6028309.50, RMSE: 14989343.20, R2: -1.1815

Epoch: 6

100%|██████████| 67/67 [00:00<00:00, 544.08it/s]

Train set: Average loss: 0.3569
Test set: Average loss: 0.5102, MAE: 4817632.00, RMSE: 11982810.72, R2: -0.3941

Epoch: 7

100%|██████████| 67/67 [00:00<00:00, 401.33it/s]

Train set: Average loss: 0.2541
Test set: Average loss: 0.4304, MAE: 4122894.00, RMSE: 10188147.71, R2: -0.0078

Epoch: 8

100%|██████████| 67/67 [00:00<00:00, 439.38it/s]

Train set: Average loss: 0.2000
Test set: Average loss: 0.3756, MAE: 3643718.00, RMSE: 8404721.52, R2: 0.3141

Epoch: 9

100%|██████████| 67/67 [00:00<00:00, 361.72it/s]

Train set: Average loss: 0.1601
Test set: Average loss: 0.3391, MAE: 3513930.00, RMSE: 8090002.59, R2: 0.3645

Epoch: 10

100%|██████████| 67/67 [00:00<00:00, 444.97it/s]

Train set: Average loss: 0.1379
Test set: Average loss: 0.3094, MAE: 3401778.75, RMSE: 7482194.72, R2: 0.4564

Epoch: 11

100%|██████████| 67/67 [00:00<00:00, 436.43it/s]

Train set: Average loss: 0.1166
Test set: Average loss: 0.2934, MAE: 3249323.50, RMSE: 6989344.84, R2: 0.5257

Epoch: 12

100%|██████████| 67/67 [00:00<00:00, 484.89it/s]

Train set: Average loss: 0.0983
Test set: Average loss: 0.2782, MAE: 2915768.00, RMSE: 6023843.78, R2: 0.6477

Epoch: 13

100%|██████████| 67/67 [00:00<00:00, 423.29it/s]

Train set: Average loss: 0.0873
Test set: Average loss: 0.2604, MAE: 2957542.75, RMSE: 6070009.78, R2: 0.6423

Epoch: 14

100%|██████████| 67/67 [00:00<00:00, 416.59it/s]

Train set: Average loss: 0.0755
Test set: Average loss: 0.2579, MAE: 2695520.75, RMSE: 5436532.98, R2: 0.7130

Epoch: 15

100%|██████████| 67/67 [00:00<00:00, 520.84it/s]

Train set: Average loss: 0.0675
Test set: Average loss: 0.2489, MAE: 2573330.25, RMSE: 5338706.86, R2: 0.7233
Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

In [44]:
seed_everything(CFG.seed)
deep_model,deep_train_losses, deep_test_losses, deep_test_loss, deep_mae,deep_rmse, deep_r2 = main(Deep(input_size), 'Deep')

Epoch: 1

100%|██████████| 67/67 [00:00<00:00, 107.96it/s]

Train set: Average loss: 69.2995
Test set: Average loss: 2.1083, MAE: 32222498.00, RMSE: 74257584.05, R2: -52.5389

Epoch: 2

100%|██████████| 67/67 [00:00<00:00, 414.16it/s]

Train set: Average loss: 0.9805
Test set: Average loss: 0.7312, MAE: 7087168.50, RMSE: 17028573.08, R2: -1.8154

Epoch: 3

100%|██████████| 67/67 [00:00<00:00, 360.07it/s]

Train set: Average loss: 0.4161
Test set: Average loss: 0.4788, MAE: 5547501.50, RMSE: 12547968.81, R2: -0.5287

Epoch: 4

100%|██████████| 67/67 [00:00<00:00, 271.91it/s]

Train set: Average loss: 0.2604
Test set: Average loss: 0.3743, MAE: 4261899.00, RMSE: 10492180.43, R2: -0.0689

Epoch: 5

100%|██████████| 67/67 [00:00<00:00, 343.03it/s]

Train set: Average loss: 0.1780
Test set: Average loss: 0.3304, MAE: 4211566.50, RMSE: 9737791.41, R2: 0.0793

Epoch: 6

100%|██████████| 67/67 [00:00<00:00, 350.63it/s]

Train set: Average loss: 0.1460
Test set: Average loss: 0.2944, MAE: 3815518.75, RMSE: 8242238.53, R2: 0.3404

Epoch: 7

100%|██████████| 67/67 [00:00<00:00, 349.45it/s]

Train set: Average loss: 0.1154
Test set: Average loss: 0.2676, MAE: 3300848.50, RMSE: 7278331.24, R2: 0.4857

Epoch: 8

100%|██████████| 67/67 [00:00<00:00, 254.73it/s]

Train set: Average loss: 0.0956
Test set: Average loss: 0.2469, MAE: 2992856.00, RMSE: 6427239.09, R2: 0.5989

Epoch: 9

100%|██████████| 67/67 [00:00<00:00, 352.50it/s]

Train set: Average loss: 0.0803
Test set: Average loss: 0.2293, MAE: 2775653.75, RMSE: 6228958.92, R2: 0.6233

Epoch: 10

100%|██████████| 67/67 [00:00<00:00, 346.21it/s]

Train set: Average loss: 0.0689
Test set: Average loss: 0.2407, MAE: 2792445.25, RMSE: 5094475.23, R2: 0.7480

Epoch: 11

100%|██████████| 67/67 [00:00<00:00, 350.73it/s]

Train set: Average loss: 0.0613
Test set: Average loss: 0.2224, MAE: 2431971.25, RMSE: 4557900.95, R2: 0.7983

Epoch: 12

100%|██████████| 67/67 [00:00<00:00, 277.92it/s]

Train set: Average loss: 0.0539
Test set: Average loss: 0.2111, MAE: 2387306.75, RMSE: 4776360.38, R2: 0.7785

Epoch: 13

100%|██████████| 67/67 [00:00<00:00, 346.97it/s]

Train set: Average loss: 0.0504
Test set: Average loss: 0.2078, MAE: 2719998.50, RMSE: 5062437.48, R2: 0.7512

Epoch: 14

100%|██████████| 67/67 [00:00<00:00, 344.20it/s]

Train set: Average loss: 0.0501
Test set: Average loss: 0.2127, MAE: 2456760.75, RMSE: 4940377.12, R2: 0.7630

Epoch: 15

100%|██████████| 67/67 [00:00<00:00, 342.59it/s]

Train set: Average loss: 0.0457
Test set: Average loss: 0.2174, MAE: 2350698.25, RMSE: 4476950.95, R2: 0.8054
Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

In [45]:
seed_everything(CFG.seed)
regularized_model,regularized_train_losses, regularized_test_losses, regularized_test_loss, regularized_mae,regularized_rmse, regularized_r2 = main(
    Regularized(input_size),'Regularized')

Epoch: 1

100%|██████████| 67/67 [00:00<00:00, 85.08it/s]

Train set: Average loss: 113.1711
Test set: Average loss: 4.6014, MAE: 9288961.00, RMSE: 13108109.41, R2: -0.6683

Epoch: 2

100%|██████████| 67/67 [00:00<00:00, 325.46it/s]

Train set: Average loss: 1.4206
Test set: Average loss: 0.8367, MAE: 6228206.00, RMSE: 9693206.72, R2: 0.0877

Epoch: 3

100%|██████████| 67/67 [00:00<00:00, 349.11it/s]

Train set: Average loss: 0.8369
Test set: Average loss: 0.5196, MAE: 5320718.00, RMSE: 7994137.08, R2: 0.3795

Epoch: 4

100%|██████████| 67/67 [00:00<00:00, 282.66it/s]

Train set: Average loss: 0.7883
Test set: Average loss: 0.3594, MAE: 4681507.50, RMSE: 8543366.46, R2: 0.2913

Epoch: 5

100%|██████████| 67/67 [00:00<00:00, 293.99it/s]

Train set: Average loss: 0.7876
Test set: Average loss: 0.6359, MAE: 5382187.00, RMSE: 8368834.95, R2: 0.3200

Epoch: 6

100%|██████████| 67/67 [00:00<00:00, 337.85it/s]

Train set: Average loss: 0.7245
Test set: Average loss: 0.3695, MAE: 4570535.00, RMSE: 8553298.35, R2: 0.2897

Epoch: 7

100%|██████████| 67/67 [00:00<00:00, 251.90it/s]

Train set: Average loss: 0.6359
Test set: Average loss: 0.3111, MAE: 4892529.00, RMSE: 8615231.80, R2: 0.2794

Epoch: 8

100%|██████████| 67/67 [00:00<00:00, 276.87it/s]

Train set: Average loss: 0.6469
Test set: Average loss: 0.3021, MAE: 4197550.50, RMSE: 6682334.96, R2: 0.5664

Epoch: 9

100%|██████████| 67/67 [00:00<00:00, 332.09it/s]

Train set: Average loss: 0.5682
Test set: Average loss: 0.2921, MAE: 4513241.00, RMSE: 7343056.23, R2: 0.4765

Epoch: 10

100%|██████████| 67/67 [00:00<00:00, 359.60it/s]

Train set: Average loss: 0.5850
Test set: Average loss: 0.6019, MAE: 5949745.00, RMSE: 9782462.32, R2: 0.0709

Epoch: 11

100%|██████████| 67/67 [00:00<00:00, 290.77it/s]

Train set: Average loss: 0.5749
Test set: Average loss: 0.2850, MAE: 3672826.75, RMSE: 5971287.40, R2: 0.6538

Epoch: 12

100%|██████████| 67/67 [00:00<00:00, 266.36it/s]

Train set: Average loss: 0.5586
Test set: Average loss: 0.4791, MAE: 4532303.50, RMSE: 6494089.81, R2: 0.5905

Epoch: 13

100%|██████████| 67/67 [00:00<00:00, 268.27it/s]

Train set: Average loss: 0.5363
Test set: Average loss: 0.2711, MAE: 4459308.00, RMSE: 7414493.17, R2: 0.4662

Epoch: 14

100%|██████████| 67/67 [00:00<00:00, 331.81it/s]

Train set: Average loss: 0.5583
Test set: Average loss: 0.2971, MAE: 4534983.00, RMSE: 7478348.49, R2: 0.4570

Epoch: 15

100%|██████████| 67/67 [00:00<00:00, 343.35it/s]

Train set: Average loss: 0.4687
Test set: Average loss: 0.4182, MAE: 5057628.00, RMSE: 7938428.16, R2: 0.3881
Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

In [46]:
seed_everything(CFG.seed)
res_model, res_train_losses, res_test_losses, res_test_loss, res_mae, res_rmse, res_r2 = main(ResMLP(input_size), 'ResMLP')

Epoch: 1

100%|██████████| 67/67 [00:00<00:00, 133.37it/s]

Train set: Average loss: 41.0732
Test set: Average loss: 0.8385, MAE: 9280553.00, RMSE: 26109617.14, R2: -5.6189

Epoch: 2

100%|██████████| 67/67 [00:00<00:00, 356.24it/s]

Train set: Average loss: 0.5792
Test set: Average loss: 0.4251, MAE: 5570532.00, RMSE: 13822507.15, R2: -0.8551

Epoch: 3

100%|██████████| 67/67 [00:00<00:00, 356.11it/s]

Train set: Average loss: 0.2593
Test set: Average loss: 0.3163, MAE: 3898517.25, RMSE: 7415061.95, R2: 0.4662

Epoch: 4

100%|██████████| 67/67 [00:00<00:00, 362.44it/s]

Train set: Average loss: 0.1620
Test set: Average loss: 0.2244, MAE: 3414824.50, RMSE: 7328599.10, R2: 0.4785

Epoch: 5

100%|██████████| 67/67 [00:00<00:00, 354.10it/s]

Train set: Average loss: 0.1049

Test set: Average loss: 0.1965, MAE: 3261900.25, RMSE: 6365360.59, R2: 0.6066

Epoch: 6

100%|██████████| 67/67 [00:00<00:00, 275.89it/s]

Train set: Average loss: 0.0785
Test set: Average loss: 0.1798, MAE: 2753076.00, RMSE: 4913340.23, R2: 0.7656

Epoch: 7

100%|██████████| 67/67 [00:00<00:00, 292.38it/s]

Train set: Average loss: 0.0653
Test set: Average loss: 0.1569, MAE: 2713619.00, RMSE: 5102883.90, R2: 0.7472

Epoch: 8

100%|██████████| 67/67 [00:00<00:00, 284.27it/s]

Train set: Average loss: 0.0516
Test set: Average loss: 0.1530, MAE: 2494837.75, RMSE: 4578878.95, R2: 0.7964

Epoch: 9

100%|██████████| 67/67 [00:00<00:00, 290.76it/s]

Train set: Average loss: 0.0460
Test set: Average loss: 0.1429, MAE: 2383383.75, RMSE: 4381591.54, R2: 0.8136

Epoch: 10

100%|██████████| 67/67 [00:00<00:00, 349.71it/s]

Train set: Average loss: 0.0404
Test set: Average loss: 0.1469, MAE: 2333615.00, RMSE: 4335105.18, R2: 0.8175

Epoch: 11

100%|██████████| 67/67 [00:00<00:00, 322.59it/s]

Train set: Average loss: 0.0422
Test set: Average loss: 0.1460, MAE: 2546647.00, RMSE: 4514735.06, R2: 0.8021

Epoch: 12

100%|██████████| 67/67 [00:00<00:00, 308.65it/s]

Train set: Average loss: 0.0422
Test set: Average loss: 0.1577, MAE: 2374902.00, RMSE: 4727513.12, R2: 0.7830

Epoch: 13

100%|██████████| 67/67 [00:00<00:00, 324.43it/s]

Train set: Average loss: 0.0407
Test set: Average loss: 0.1611, MAE: 3103655.25, RMSE: 5569043.18, R2: 0.6989

Epoch: 14

100%|██████████| 67/67 [00:00<00:00, 291.40it/s]

Train set: Average loss: 0.0401
Test set: Average loss: 0.1541, MAE: 2607253.00, RMSE: 4554967.71, R2: 0.7986

Epoch: 15

100%|██████████| 67/67 [00:00<00:00, 289.95it/s]

Train set: Average loss: 0.0423
Test set: Average loss: 0.1499, MAE: 2369907.50, RMSE: 4301483.10, R2: 0.8204
Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

In [47]:
res = pd.DataFrame([{'model': 'Simple', 'test_loss': simple_test_loss, 'MAE': simple_mae, 'RMSE': simple_rmse, 'R2': simple_r2},
                        {'model': 'Deep', 'test_loss': deep_test_loss, 'MAE': deep_mae, 'RMSE': deep_rmse, 'R2': deep_r2},
                        {'model': 'Regularized', 'test_loss': regularized_test_loss, 'MAE': regularized_mae, 'RMSE': regularized_rmse, 'R2': regularized_r2},
                        {'model': 'ResMLP', 'test_loss': res_test_loss, 'MAE': res_mae, 'RMSE': res_rmse, 'R2': res_r2}])

res

         model  test_loss         MAE          RMSE        R2
0       Simple   0.248894  2573330.25  5.338707e+06  0.723267
1         Deep   0.217364  2350698.25  4.476951e+06  0.805396
2  Regularized   0.285035  3672826.75  5.971287e+06  0.653803
3       ResMLP   0.146879  2333615.00  4.335105e+06  0.817532

In [48]:
res.sort_values('MAE')

         model  test_loss         MAE          RMSE        R2
3       ResMLP   0.146879  2333615.00  4.335105e+06  0.817532
1         Deep   0.217364  2350698.25  4.476951e+06  0.805396
0       Simple   0.248894  2573330.25  5.338707e+06  0.723267
2  Regularized   0.285035  3672826.75  5.971287e+06  0.653803

### Сравнение моделей и выводы

По ходу работы мы обучили 4 модели, от простой базовой полносвязной сети до полносвязной с residual блоками. Основная метрика - считаем MAE, средняя ошибка прогноза цены в тенге. 

По результатам: лучшей стала модель ResMLP с показателями MAE - примерно 2,29 млн тенге, R2 - примерно 0,82, то есть модель лучше остальных отличает цены и в среднем меньше ошибается. Базовая модель(Simple) и модель с бОльшим количеством скрытых слоев(Deep) также дают хороший результат. Худший результат показала модель Regularized, возможно dropout для нашего датасета мешала модели запоминать какие-то важные зависимости в данных или еще что-то, но любые манипуляции с весами не помогали.