# Подготовка к глубинному обучению на табличных данных

Для этой части, мы сначала минимально подготовим датасет для глубинного обучения на табличных данных

In [32]:
import pandas as pd
import numpy as np 

df = pd.read_csv('../data/df_table.csv')
df

,brand,model,generation,year,city,body_type,fuel_type,engine_volume,mileage,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price
0,Chevrolet,Cobalt,2011 - н.в. 2 поколение\n,2021,"Астана, Акмолинская область",Седан,бензин,1.5,145113,Автомат,Передний привод,Слева,черный,Да,25,4490000
1,Chevrolet,Monza,2022 - н.в. 2 поколение рестайлинг\n,2023,"Астана, Акмолинская область",Седан,бензин,1.5,20000,Робот,Передний привод,Слева,серый металлик,Да,6,6400000
2,Chevrolet,Captiva,2018 - н.в. 2 поколение\n,2021,"Алматы, Алматинская область",Внедорожник,бензин,1.5,85024,Автомат,Передний привод,Слева,серый,Да,27,7150000
3,Chevrolet,Cruze,2012 - 2015 J300 рестайлинг\n,2013,"Алматы, Алматинская область",Хэтчбек,бензин,1.8,146000,Автомат,Передний привод,Слева,серебристый,Да,8,4400000
4,Chevrolet,Aveo,2006 - 2012 T250 рестайлинг (T250/T255)\n,2007,"Астана, Акмолинская область",Седан,бензин,1.4,216000,Автомат,Передний привод,Слева,unknown,Да,10,2450000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5291,Hyundai,Grandeur,2011 - 2016 HG\n,2011,"Шымкент, Туркестанская область",Седан,бензин,3.0,148000,Автомат,Передний привод,Слева,белый,Да,24,8300000
5292,Hyundai,Sonata,2019 - н.в. 8 поколение (DN8)\n,2022,"Атырау, Атырауская область",Седан,бензин,2.5,110000,Автомат,Передний привод,Слева,unknown,Да,11,12500000
5293,Hyundai,i30,2020 - н.в. 3 поколение рестайлинг (PD)\n,2023,"Шымкент, Туркестанская область",Универсал,бензин,1.5,45000,Автомат,Передний привод,Слева,белый металлик,Да,10,9000000
5294,Hyundai,Elantra,2018 - 2020 6 поколение рестайлинг (AD/ADA)\n,2018,"Уральск, Западно-Казахстанская область",Седан,бензин,2.0,136197,Автомат,Передний привод,Слева,unknown,Да,19,6200000
5295,Hyundai,Tucson,2018 - 2021 3 поколение рестайлинг (TL/TLE)\n,2018,"Актобе, Актюбинская область",Кроссовер,бензин,2.0,84000,Автомат,Передний привод,Слева,unknown,Да,21,9900000

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5296 entries, 0 to 5295
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            5296 non-null   object
 1   model            5296 non-null   object
 2   generation       5290 non-null   object
 3   year             5296 non-null   int64
 4   city             5296 non-null   object
 5   body_type        5296 non-null   object
 6   fuel_type        5296 non-null   object
 7   engine_volume    5296 non-null   float64
 8   mileage          5296 non-null   int64
 9   transmission     5296 non-null   object
 10  drive_type       5296 non-null   object
 11  steering_wheel   5296 non-null   object
 12  color            5296 non-null   object
 13  kz_registration  5296 non-null   object
 14  imgs_count       5296 non-null   int64
 15  price            5296 non-null   int64
dtypes: float64(1), int64(4), object(11)
memory usage: 662.1+ KB

Отсюда сначала уберем generation

In [34]:
df = df.drop(columns= {'generation'})

df

,brand,model,year,city,body_type,fuel_type,engine_volume,mileage,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price
0,Chevrolet,Cobalt,2021,"Астана, Акмолинская область",Седан,бензин,1.5,145113,Автомат,Передний привод,Слева,черный,Да,25,4490000
1,Chevrolet,Monza,2023,"Астана, Акмолинская область",Седан,бензин,1.5,20000,Робот,Передний привод,Слева,серый металлик,Да,6,6400000
2,Chevrolet,Captiva,2021,"Алматы, Алматинская область",Внедорожник,бензин,1.5,85024,Автомат,Передний привод,Слева,серый,Да,27,7150000
3,Chevrolet,Cruze,2013,"Алматы, Алматинская область",Хэтчбек,бензин,1.8,146000,Автомат,Передний привод,Слева,серебристый,Да,8,4400000
4,Chevrolet,Aveo,2007,"Астана, Акмолинская область",Седан,бензин,1.4,216000,Автомат,Передний привод,Слева,unknown,Да,10,2450000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5291,Hyundai,Grandeur,2011,"Шымкент, Туркестанская область",Седан,бензин,3.0,148000,Автомат,Передний привод,Слева,белый,Да,24,8300000
5292,Hyundai,Sonata,2022,"Атырау, Атырауская область",Седан,бензин,2.5,110000,Автомат,Передний привод,Слева,unknown,Да,11,12500000
5293,Hyundai,i30,2023,"Шымкент, Туркестанская область",Универсал,бензин,1.5,45000,Автомат,Передний привод,Слева,белый металлик,Да,10,9000000
5294,Hyundai,Elantra,2018,"Уральск, Западно-Казахстанская область",Седан,бензин,2.0,136197,Автомат,Передний привод,Слева,unknown,Да,19,6200000
5295,Hyundai,Tucson,2018,"Актобе, Актюбинская область",Кроссовер,бензин,2.0,84000,Автомат,Передний привод,Слева,unknown,Да,21,9900000

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5296 entries, 0 to 5295
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            5296 non-null   object
 1   model            5296 non-null   object
 2   year             5296 non-null   int64
 3   city             5296 non-null   object
 4   body_type        5296 non-null   object
 5   fuel_type        5296 non-null   object
 6   engine_volume    5296 non-null   float64
 7   mileage          5296 non-null   int64
 8   transmission     5296 non-null   object
 9   drive_type       5296 non-null   object
 10  steering_wheel   5296 non-null   object
 11  color            5296 non-null   object
 12  kz_registration  5296 non-null   object
 13  imgs_count       5296 non-null   int64
 14  price            5296 non-null   int64
dtypes: float64(1), int64(4), object(10)
memory usage: 620.8+ KB

In [36]:
X = df.drop(columns= {'price'})
y = df['price']

In [37]:
X

,brand,model,year,city,body_type,fuel_type,engine_volume,mileage,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count
0,Chevrolet,Cobalt,2021,"Астана, Акмолинская область",Седан,бензин,1.5,145113,Автомат,Передний привод,Слева,черный,Да,25
1,Chevrolet,Monza,2023,"Астана, Акмолинская область",Седан,бензин,1.5,20000,Робот,Передний привод,Слева,серый металлик,Да,6
2,Chevrolet,Captiva,2021,"Алматы, Алматинская область",Внедорожник,бензин,1.5,85024,Автомат,Передний привод,Слева,серый,Да,27
3,Chevrolet,Cruze,2013,"Алматы, Алматинская область",Хэтчбек,бензин,1.8,146000,Автомат,Передний привод,Слева,серебристый,Да,8
4,Chevrolet,Aveo,2007,"Астана, Акмолинская область",Седан,бензин,1.4,216000,Автомат,Передний привод,Слева,unknown,Да,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5291,Hyundai,Grandeur,2011,"Шымкент, Туркестанская область",Седан,бензин,3.0,148000,Автомат,Передний привод,Слева,белый,Да,24
5292,Hyundai,Sonata,2022,"Атырау, Атырауская область",Седан,бензин,2.5,110000,Автомат,Передний привод,Слева,unknown,Да,11
5293,Hyundai,i30,2023,"Шымкент, Туркестанская область",Универсал,бензин,1.5,45000,Автомат,Передний привод,Слева,белый металлик,Да,10
5294,Hyundai,Elantra,2018,"Уральск, Западно-Казахстанская область",Седан,бензин,2.0,136197,Автомат,Передний привод,Слева,unknown,Да,19
5295,Hyundai,Tucson,2018,"Актобе, Актюбинская область",Кроссовер,бензин,2.0,84000,Автомат,Передний привод,Слева,unknown,Да,21

Следующее - закодировать категориальные признаки

In [38]:
X = pd.get_dummies(X, drop_first=True)
X.shape

(5296, 570)

С предыдущих этапов знаем, что цена варьируется примерно с 2млн до 60млн, что значительный разброс. Поэтому, применим логарифмирование, чтобы хоть как то стабилизировать дальнейшее обучение

In [39]:
y = np.log1p(y)
y

0       15.317363
1       15.671809
2       15.782623
3       15.297115
4       14.711599
          ...
5291    15.931766
5292    16.341239
5293    16.012735
5294    15.640060
5295    16.108045
Name: price, Length: 5296, dtype: float64

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)


X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4236, 570), (1060, 570), (4236,), (1060,))

In [41]:
scaler = StandardScaler() #масштабируем только числовы признаки
X_train[['year', 'engine_volume', 'mileage', 'imgs_count']] = scaler.fit_transform(X_train[['year', 'engine_volume', 'mileage', 'imgs_count']]) #тут фит_трансформ чтобы сначала знать среднее и станд откл выборки, а потом преобразует по ним значения
X_test[['year', 'engine_volume', 'mileage', 'imgs_count']] = scaler.transform(X_test[['year', 'engine_volume', 'mileage', 'imgs_count']])

X_test

,year,engine_volume,mileage,imgs_count,brand_BMW,brand_Chevrolet,brand_Hyundai,brand_Kia,brand_Lexus,brand_Mercedes-Benz,...,color_синий,color_синий металлик,color_сиреневый,color_фиолетовый,color_фиолетовый металлик,color_хамелеон,color_хамелеон металлик,color_черный,color_черный металлик,kz_registration_Нет
422,1.129727,1.131717,-0.840118,1.269651,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1101,-0.053690,-0.600481,0.632074,0.928867,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
810,0.591810,-0.215548,-0.136602,0.162105,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4262,0.484227,-0.600481,-0.242089,0.673280,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
5183,0.591810,-0.408014,-0.469291,-0.008286,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4573,-0.484024,0.843018,0.853353,-0.604657,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
2277,0.161477,-0.600481,0.009457,0.162105,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3226,0.269060,0.843018,0.366490,-0.178678,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
602,0.699394,0.361851,-0.826324,0.417693,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1209,-1.882607,1.709116,1.168312,0.758476,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

Теперь надо это все сохранить, поэтому по хорошему надо преобразовать это все в датафреймы, а потом сохраним

In [42]:
X_train = pd.DataFrame(X_train,columns=X.columns)
X_test = pd.DataFrame(X_test,columns=X.columns)
y_train = pd.DataFrame(y_train,columns=['price'])
y_test = pd.DataFrame(y_test,columns=['price'])

Теперь сохраним в data

In [43]:
X_train.to_csv('../data/X_train.csv', index= False)
X_test.to_csv('../data/X_test.csv', index= False)
y_train.to_csv('../data/y_train.csv', index= False)
y_test.to_csv('../data/y_test.csv', index= False)