# Подготовка к глубинному обучению на табличных данных

Для этой части, мы сначала минимально подготовим датасет для глубинного обучения на табличных данных

In [2]:
import pandas as pd
import numpy as np 

df = pd.read_csv('../data/clean_df.csv')
df

,kolesa_id,kolesa_url,parsed_at,brand,model,generation,year,city,body_type,fuel_type,...,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price,img_filename,img_url,found_img
0,221971452,https://kolesa.kz/a/show/221971452?search_id=4...,2026-06-08 10:31:39.616294+03:00,Kia,K5,2023 - н.в. 3 поколение рестайлинг\n,2025,"Астана, Акмолинская область",Седан,бензин,...,Автомат,Передний привод,Слева,черный металлик,Да,13,14100000,221971452.webp,https://kolesa-photos.kcdn.online/webp/72/724f...,True
1,184557634,https://kolesa.kz/a/show/184557634?search_id=4...,2026-06-08 10:31:55.104766+03:00,Kia,Sorento,2017 - 2020 3 поколение рестайлинг (UM)\n,2020,"Астана, Акмолинская область",Кроссовер,бензин,...,Автомат,Полный привод,Слева,коричневый,Да,11,13500000,184557634.webp,https://kolesa-photos.kcdn.online/webp/3f/3f1b...,True
2,222310850,https://kolesa.kz/a/show/222310850?search_id=4...,2026-06-08 10:32:07.399668+03:00,Kia,K7,2012 - 2015 1 поколение рестайлинг\n,2014,"Алматы, Алматинская область",Седан,бензин,...,Автомат,Передний привод,Слева,черный металлик,Да,25,9500000,222310850.webp,https://kolesa-photos.kcdn.online/webp/13/136a...,True
3,206731143,https://kolesa.kz/a/show/206731143?search_id=4...,2026-06-08 10:32:37.197220+03:00,Kia,Soul,2013 - 2016 2 поколение (PS)\n,2014,"Караганда, Карагандинская область",Хэтчбек,бензин,...,Автомат,Передний привод,Слева,красный металлик,Да,15,6300000,206731143.webp,https://kolesa-photos.kcdn.online/webp/95/95f3...,True
4,221564600,https://kolesa.kz/a/show/221564600?search_id=4...,2026-06-08 10:33:04.907473+03:00,Kia,Soul,2011 - 2014 1 поколение рестайлинг (AM)\n,2013,"Панфилово (Талгарский р-н), Алматинская область",Хэтчбек,бензин,...,Автомат,Передний привод,Слева,бежевый металлик,Да,13,5600000,221564600.webp,https://kolesa-photos.kcdn.online/webp/d4/d458...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3712,222254836,https://kolesa.kz/a/show/222254836?search_id=3...,2026-06-06 20:48:05.146091+03:00,Kia,Sportage,2010 - 2014 3 поколение (SL)\n,2014,"Мангистау, Мангистауская область",Кроссовер,бензин,...,Автомат,Передний привод,Слева,unknown,Да,7,7100000,222254836.webp,https://kolesa-photos.kcdn.online/webp/f0/f072...,True
3713,221970223,https://kolesa.kz/a/show/221970223?search_id=3...,2026-06-06 20:48:19.201839+03:00,Kia,Sorento,2002 - 2006 1 поколение (JC)\n,2004,"Усть-Каменогорск, Восточно-Казахстанская область",Внедорожник,газ-бензин,...,Автомат,Полный привод,Слева,серебристый металлик,Да,8,2900000,221970223.webp,https://kolesa-photos.kcdn.online/webp/ef/ef3e...,True
3714,220273619,https://kolesa.kz/a/show/220273619?search_id=3...,2026-06-06 20:48:34.185487+03:00,Kia,K5,2019 - н.в. 3 поколение\n,2022,"Алматы, Алматинская область",Седан,бензин,...,Автомат,Передний привод,Слева,unknown,Да,18,10800000,220273619.webp,https://kolesa-photos.kcdn.online/webp/c4/c497...,True
3715,209668596,https://kolesa.kz/a/show/209668596?search_id=3...,2026-06-06 20:49:03.080793+03:00,Kia,Sportage,2018 - н.в. 4 поколение рестайлинг\n,2021,"Алматы, Алматинская область",Кроссовер,бензин,...,Автомат,Полный привод,Слева,белый металлик,Да,26,11500000,209668596.webp,https://kolesa-photos.kcdn.online/webp/f0/f020...,True
3716,218447227,https://kolesa.kz/a/show/218447227?search_id=3...,2026-06-06 20:49:31.995428+03:00,Kia,Sorento,2020 - н.в. 4 поколение (MQ4/MQ4A)\n,2023,"Алматы, Алматинская область",Кроссовер,бензин,...,Автомат,Полный привод,Слева,черный металлик,Да,14,15000000,218447227.webp,https://kolesa-photos.kcdn.online/webp/4b/4b8e...,True

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3717 entries, 0 to 3716
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kolesa_id        3717 non-null   int64
 1   kolesa_url       3717 non-null   object
 2   parsed_at        3717 non-null   object
 3   brand            3717 non-null   object
 4   model            3717 non-null   object
 5   generation       3712 non-null   object
 6   year             3717 non-null   int64
 7   city             3717 non-null   object
 8   body_type        3717 non-null   object
 9   fuel_type        3717 non-null   object
 10  engine_volume    3717 non-null   float64
 11  mileage          3717 non-null   int64
 12  transmission     3717 non-null   object
 13  drive_type       3717 non-null   object
 14  steering_wheel   3717 non-null   object
 15  color            3717 non-null   object
 16  kz_registration  3717 non-null   object
 17  imgs_count       3717 non-null   int64
 18  price            3717 non-null   int64
 19  img_filename     3706 non-null   object
 20  img_url          3706 non-null   object
 21  found_img        3717 non-null   bool
dtypes: bool(1), float64(1), int64(5), object(15)
memory usage: 613.6+ KB

Отсюда сначала уберем ненужные признаки а именно: 
1. kolesa_id — просто номер объявления
2. kolesa_url — ссылка - бесполезна
3. parsed_at — дата парсинга - бесполезна
4. generation — пока можно не брать, там длинный грязный текст
5. img_filename, img_url — нужны для image модели, для таблицы не надо
6. found_img — связано с фото, нам не надо сейчас

In [4]:
df = df.drop(columns= {'kolesa_id', 'kolesa_url', 'parsed_at', 'generation', 'img_filename', 'img_url','found_img'})

df

,brand,model,year,city,body_type,fuel_type,engine_volume,mileage,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count,price
0,Kia,K5,2025,"Астана, Акмолинская область",Седан,бензин,2.0,36500,Автомат,Передний привод,Слева,черный металлик,Да,13,14100000
1,Kia,Sorento,2020,"Астана, Акмолинская область",Кроссовер,бензин,3.5,70000,Автомат,Полный привод,Слева,коричневый,Да,11,13500000
2,Kia,K7,2014,"Алматы, Алматинская область",Седан,бензин,3.0,117000,Автомат,Передний привод,Слева,черный металлик,Да,25,9500000
3,Kia,Soul,2014,"Караганда, Карагандинская область",Хэтчбек,бензин,1.6,117000,Автомат,Передний привод,Слева,красный металлик,Да,15,6300000
4,Kia,Soul,2013,"Панфилово (Талгарский р-н), Алматинская область",Хэтчбек,бензин,2.0,151000,Автомат,Передний привод,Слева,бежевый металлик,Да,13,5600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3712,Kia,Sportage,2014,"Мангистау, Мангистауская область",Кроссовер,бензин,2.0,170000,Автомат,Передний привод,Слева,unknown,Да,7,7100000
3713,Kia,Sorento,2004,"Усть-Каменогорск, Восточно-Казахстанская область",Внедорожник,газ-бензин,2.4,325000,Автомат,Полный привод,Слева,серебристый металлик,Да,8,2900000
3714,Kia,K5,2022,"Алматы, Алматинская область",Седан,бензин,2.0,38700,Автомат,Передний привод,Слева,unknown,Да,18,10800000
3715,Kia,Sportage,2021,"Алматы, Алматинская область",Кроссовер,бензин,2.0,62000,Автомат,Полный привод,Слева,белый металлик,Да,26,11500000
3716,Kia,Sorento,2023,"Алматы, Алматинская область",Кроссовер,бензин,2.5,50000,Автомат,Полный привод,Слева,черный металлик,Да,14,15000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3717 entries, 0 to 3716
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            3717 non-null   object
 1   model            3717 non-null   object
 2   year             3717 non-null   int64
 3   city             3717 non-null   object
 4   body_type        3717 non-null   object
 5   fuel_type        3717 non-null   object
 6   engine_volume    3717 non-null   float64
 7   mileage          3717 non-null   int64
 8   transmission     3717 non-null   object
 9   drive_type       3717 non-null   object
 10  steering_wheel   3717 non-null   object
 11  color            3717 non-null   object
 12  kz_registration  3717 non-null   object
 13  imgs_count       3717 non-null   int64
 14  price            3717 non-null   int64
dtypes: float64(1), int64(4), object(10)
memory usage: 435.7+ KB

In [6]:
X = df.drop(columns= {'price'})
y = df['price']

In [7]:
X

,brand,model,year,city,body_type,fuel_type,engine_volume,mileage,transmission,drive_type,steering_wheel,color,kz_registration,imgs_count
0,Kia,K5,2025,"Астана, Акмолинская область",Седан,бензин,2.0,36500,Автомат,Передний привод,Слева,черный металлик,Да,13
1,Kia,Sorento,2020,"Астана, Акмолинская область",Кроссовер,бензин,3.5,70000,Автомат,Полный привод,Слева,коричневый,Да,11
2,Kia,K7,2014,"Алматы, Алматинская область",Седан,бензин,3.0,117000,Автомат,Передний привод,Слева,черный металлик,Да,25
3,Kia,Soul,2014,"Караганда, Карагандинская область",Хэтчбек,бензин,1.6,117000,Автомат,Передний привод,Слева,красный металлик,Да,15
4,Kia,Soul,2013,"Панфилово (Талгарский р-н), Алматинская область",Хэтчбек,бензин,2.0,151000,Автомат,Передний привод,Слева,бежевый металлик,Да,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3712,Kia,Sportage,2014,"Мангистау, Мангистауская область",Кроссовер,бензин,2.0,170000,Автомат,Передний привод,Слева,unknown,Да,7
3713,Kia,Sorento,2004,"Усть-Каменогорск, Восточно-Казахстанская область",Внедорожник,газ-бензин,2.4,325000,Автомат,Полный привод,Слева,серебристый металлик,Да,8
3714,Kia,K5,2022,"Алматы, Алматинская область",Седан,бензин,2.0,38700,Автомат,Передний привод,Слева,unknown,Да,18
3715,Kia,Sportage,2021,"Алматы, Алматинская область",Кроссовер,бензин,2.0,62000,Автомат,Полный привод,Слева,белый металлик,Да,26
3716,Kia,Sorento,2023,"Алматы, Алматинская область",Кроссовер,бензин,2.5,50000,Автомат,Полный привод,Слева,черный металлик,Да,14

Следующее - закодировать категориальные признаки

In [8]:
X = pd.get_dummies(X, drop_first=True)
X.shape

(3717, 521)

С предыдущих этапов знаем, что цена варьируется примерно с 2млн до 60млн, что значительный разброс. Поэтому, применим логарифмирование, чтобы хоть как то стабилизировать дальнейшее обучение

In [9]:
y = np.log1p(y)
y

0       16.461685
1       16.418200
2       16.066802
3       15.656060
4       15.538277
          ...
3712    15.775605
3713    14.880222
3714    16.195057
3715    16.257858
3716    16.523561
Name: price, Length: 3717, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)


X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2973, 521), (744, 521), (2973,), (744,))

In [11]:
scaler = StandardScaler() #чтобы масштаб значений не мешал обучению
X_train = scaler.fit_transform(X_train) #тут фит_трансформ чтобы сначала знать среднее и станд откл выборки, а потом преобразует по ним значения
X_test = scaler.transform(X_test)

X_test

array([[-1.41406341, -0.14709709,  0.60041886, ...,  3.42127582,
        -0.34730126, -0.1334246 ],
       [ 0.23108432,  0.80712427,  0.38435988, ...,  3.42127582,
        -0.34730126, -0.1334246 ],
       [ 1.10849645, -0.14709709, -0.74647867, ..., -0.29228862,
        -0.34730126, -0.1334246 ],
       ...,
       [-0.75600432, -0.52878563, -1.38314714, ..., -0.29228862,
        -0.34730126, -0.1334246 ],
       [-0.20762174, -0.14709709,  0.0940291 , ..., -0.29228862,
        -0.34730126, -0.1334246 ],
       [-0.09794522, -0.14709709, -1.15865075, ..., -0.29228862,
        -0.34730126, -0.1334246 ]])

Теперь надо это все сохранить, поэтому по хорошему надо преобразовать это все в датафреймы, а потом сохраним

In [14]:
X_train = pd.DataFrame(X_train,columns=X.columns)
X_test = pd.DataFrame(X_test,columns=X.columns)
y_train = pd.DataFrame(y_train,columns=['price'])
y_test = pd.DataFrame(y_test,columns=['price'])

Теперь сохраним в data

In [16]:
X_train.to_csv('../data/X_train.csv', index= False)
X_test.to_csv('../data/X_test.csv', index= False)
y_train.to_csv('../data/y_train.csv', index= False)
y_test.to_csv('../data/y_test.csv', index= False)