In [1]:
import pandas as pd

results_dl_images = pd.read_csv('../data/results_dl_images.csv')
results_alexnet = pd.read_csv('../data/results_alexnet.csv')

In [2]:
results_dl_images

                   model       task  accuracy  macro_f1  weighted_f1
0            BaseLine_FC  body_type  0.547368  0.535107     0.554748
1               Base_CNN  body_type  0.642105  0.638435     0.647912
2                Reg_CNN  body_type  0.675188  0.674652     0.678088
3      ResNet18_finetune  body_type  0.893233  0.886673     0.893766
4  ResNet18_reg_finetune  body_type  0.968421  0.965803     0.968265
5            BaseLine_FC      brand  0.151880  0.150438     0.150214
6               Base_CNN      brand  0.198496  0.189036     0.187316
7                Reg_CNN      brand  0.284211  0.260676     0.259223
8      ResNet18_finetune      brand  0.581955  0.576440     0.577551
9  ResNet18_reg_finetune      brand  0.884211  0.884551     0.883427

In [3]:
results_alexnet

                     model       task  accuracy  macro_f1  weighted_f1
0         AlexNet_finetune  body_type  0.815038  0.801444     0.814959
1  AlexNet_finetune_frozen  body_type  0.780451  0.771587     0.783293
2         AlexNet_finetune      brand  0.354887  0.347004     0.349291
3  AlexNet_finetune_frozen      brand  0.341353  0.338762     0.338058

In [4]:
all_results = pd.concat([results_dl_images, results_alexnet])
all_results

                     model       task  accuracy  macro_f1  weighted_f1
0              BaseLine_FC  body_type  0.547368  0.535107     0.554748
1                 Base_CNN  body_type  0.642105  0.638435     0.647912
2                  Reg_CNN  body_type  0.675188  0.674652     0.678088
3        ResNet18_finetune  body_type  0.893233  0.886673     0.893766
4    ResNet18_reg_finetune  body_type  0.968421  0.965803     0.968265
5              BaseLine_FC      brand  0.151880  0.150438     0.150214
6                 Base_CNN      brand  0.198496  0.189036     0.187316
7                  Reg_CNN      brand  0.284211  0.260676     0.259223
8        ResNet18_finetune      brand  0.581955  0.576440     0.577551
9    ResNet18_reg_finetune      brand  0.884211  0.884551     0.883427
0         AlexNet_finetune  body_type  0.815038  0.801444     0.814959
1  AlexNet_finetune_frozen  body_type  0.780451  0.771587     0.783293
2         AlexNet_finetune      brand  0.354887  0.347004     0.349291
3  AlexNet_finetune_frozen      brand  0.341353  0.338762     0.338058

In [5]:
all_results.to_csv('../data/all_results_img.csv', index=False)