In [1]:
import os
import wandb

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score

import numpy as np
import pandas as pd
import random
from tqdm import *

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets
import torchvision.transforms as transforms

try:
    from torchinfo import summary
except:
    print("[INFO] Couldn't find torchinfo... installing it.")
    !pip install -q torchinfo
    from torchinfo import summary

from PIL import Image

import matplotlib.pyplot as plt
%matplotlib inline

### Зафиксируем seed для воспроизводимости

In [2]:
def seed_everything(seed):
    random.seed(seed) # фиксируем генератор случайных чисел
    os.environ['PYTHONHASHSEED'] = str(seed) # фиксируем заполнения хешей
    np.random.seed(seed) # фиксируем генератор случайных чисел numpy
    torch.manual_seed(seed) # фиксируем генератор случайных чисел pytorch
    torch.cuda.manual_seed(seed) # фиксируем генератор случайных чисел для GPU
    torch.backends.cudnn.deterministic = True # выбираем только детерминированные алгоритмы (для сверток)
    torch.backends.cudnn.benchmark = False # фиксируем алгоритм вычисления сверток

### Задаем параметры (конфиг)

In [3]:
all_brands = ('Audi', 'BMW', 'Chevrolet', 'Hyundai', 'Kia', 'Lexus', 'Mercedes-Benz', 'Toyota')
all_body_types = ('sedan', 'SUV')

class CFG:
  api = ""
  project = "kolesa-cars"
  entity = "armntvs-d3v-student"
  num_epochs = 10
  train_batch_size = 32
  test_batch_size = 512
  num_workers = 0
  lr = 3e-4
  seed = 42
  classes = all_body_types
  wandb = True

In [4]:
# вход в W&B (ключ спросит один раз, берём с https://wandb.ai/authorize)
wandb.login()

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/ksa/.netrc.
wandb: Currently logged in as: armntvs-d3v (armntvs-d3v-student) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [5]:
seed_everything(CFG.seed)

In [6]:
# Переведем наш класс с параметрами в словарь

def class2dict(f):
  return dict((name, getattr(f, name)) for name in dir(f) if not name.startswith('__'))

### Импортируем наш датасет с картинками

In [ ]:
try:
  from google.colab import drive
  drive.mount('/content/drive')
  !cp -r /content/drive/MyDrive/gp5_project/data /content/data

  base_dir = '/content/data'
except:
  base_dir = '../data'

from pathlib import Path

base_dir = Path(base_dir)

In [8]:
df_bt = pd.read_csv(base_dir / 'prepared_df_images.csv')
df_bt

      kolesa_id    body_type    img_filename  target
0     220599328        Седан  220599328.webp       0
1     222486528        Седан  222486528.webp       0
2     218695550  Внедорожник  218695550.webp       1
3     214781208        Седан  214781208.webp       0
4     222346737        Седан  222346737.webp       0
...         ...          ...             ...     ...
4428  222478046        Седан  222478046.webp       0
4429  222704181        Седан  222704181.webp       0
4430  220000872        Седан  220000872.webp       0
4431  222542135        Седан  222542135.webp       0
4432  220019907    Кроссовер  220019907.webp       1

[4433 rows x 4 columns]

In [9]:
df_brand = pd.read_csv(base_dir / 'brand_df_images.csv')
df_brand

      kolesa_id      brand    body_type    img_filename  target
0     220599328  Chevrolet        Седан  220599328.webp       2
1     222486528  Chevrolet        Седан  222486528.webp       2
2     218695550  Chevrolet  Внедорожник  218695550.webp       2
3     214781208  Chevrolet        Седан  214781208.webp       2
4     222346737  Chevrolet        Седан  222346737.webp       2
...         ...        ...          ...             ...     ...
4428  222478046    Hyundai        Седан  222478046.webp       3
4429  222704181    Hyundai        Седан  222704181.webp       3
4430  220000872    Hyundai        Седан  220000872.webp       3
4431  222542135    Hyundai        Седан  222542135.webp       3
4432  220019907    Hyundai    Кроссовер  220019907.webp       3

[4433 rows x 5 columns]

In [10]:
train_df_bt, test_all_df_bt = train_test_split(df_bt, test_size=0.3, stratify=df_bt['target'], random_state=CFG.seed)
val_df_bt, test_df_bt = train_test_split(test_all_df_bt, test_size=0.5, stratify=test_all_df_bt['target'], random_state=CFG.seed)

train_df_brand, test_all_df_brand = train_test_split(df_brand, test_size=0.3, stratify=df_brand['target'], random_state=CFG.seed)
val_df_brand, test_df_brand = train_test_split(test_all_df_brand, test_size=0.5, stratify=test_all_df_brand['target'], random_state=CFG.seed)

In [11]:
# https://stackoverflow.com/questions/65231299/load-csv-and-image-dataset-in-pytorch

class KolesaDataset(torch.utils.data.Dataset):
    def __init__(self, df, images_folder = base_dir / 'images', transform = None):
        # т.к. после train_test_split индексы сохряняются из исходного датасета, то мы их сбрасываем и удаляем колонку со старыми индексами для корректной работы __getitem___
        self.df = df.reset_index().drop(columns=['index'])
        self.images_folder = images_folder
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, index):
        filename = self.df.loc[index, 'img_filename']
        label = self.df.loc[index, 'target']
        image = Image.open(os.path.join(self.images_folder, filename)).convert('RGB')

        if self.transform is not None:
            image = self.transform(image)

        return image, label

### Функции обучения и инференса

In [12]:
# функция обучения
def train(model, device, train_loader, optimizer, criterion, epoch, WANDB):
    model.train()
    train_loss = 0
    correct = 0

    n_ex = len(train_loader)

    for batch_idx, (data, target) in tqdm(enumerate(train_loader), total=n_ex):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad() # обнуляем градиенты
        output = model(data)
        pred = output.argmax(dim=1, keepdim=True)
        correct += pred.eq(target.view_as(pred)).sum().item()
        train_loss = criterion(output, target) # считаем лосс
        train_loss.backward() # обратный проход
        optimizer.step() # делаем шаг оптимизатором

    tqdm.write('\nTrain set: Average loss: {:.4f}, Accuracy: {:.2f}%'.format(
        train_loss, 100. * correct / len(train_loader.dataset)))

    # логируем функцию потерь и точность
    if WANDB:
        wandb.log({'train_loss': train_loss,
                   'train_accuracy': correct / len(train_loader.dataset)})

In [13]:
# функция инференса
def test(model, device, test_loader, criterion, WANDB):
    model.eval()
    test_loss = 0
    correct = 0

    preds = []
    targets = []
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss = criterion(output, target)
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

            # https://stackoverflow.com/questions/53467215/convert-pytorch-cuda-tensor-to-numpy-array
            preds.extend(pred.cpu().numpy())
            targets.extend(target.cpu().numpy())

    # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html
    report = classification_report(targets, preds, target_names=CFG.classes)

    accuracy = correct / len(test_loader.dataset)
    macro_f1 = f1_score(targets, preds, average='macro')
    weighted_f1 = f1_score(targets, preds, average='weighted')

    tqdm.write('Test set: Accuracy: {:.2f}%'.format(100. * accuracy))

    tqdm.write('\nClassification report:\n' + report)

    if WANDB:
        wandb.log({'test_loss': accuracy, 'test_macro_f1': macro_f1, 'test_weighted_f1': weighted_f1})

    return accuracy, macro_f1, weighted_f1, report

# функция инференса
def val(model, device, val_loader, criterion, WANDB):
    model.eval()
    val_loss = 0
    correct = 0

    preds = []
    targets = []
    with torch.no_grad():
        for data, target in val_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            val_loss = criterion(output, target)
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

            preds.extend(pred.cpu().numpy())
            targets.extend(target.cpu().numpy())

    report = classification_report(targets, preds, target_names=CFG.classes)

    tqdm.write('Val set: Average loss: {:.4f}, Accuracy: {:.2f}%'.format(
        val_loss, 100. * correct / len(val_loader.dataset)))

    tqdm.write('\nClassification report:\n' + report)

    if WANDB:
        wandb.log({'val_loss': val_loss,
                   'val_accuracy': correct / len(val_loader.dataset)})

### Основная функция для прогона моделей

In [14]:
def main_kolesa(model, train_df, val_df):

    if CFG.wandb:
        wandb.init(project=CFG.project, entity=CFG.entity, reinit=True, config=class2dict(CFG))
        # логируем архитектуру модели
        # https://docs.wandb.ai/guides/track/config
        wandb.config.update({'model': str(model)})

    seed_everything(CFG.seed)
    # https://stackoverflow.com/questions/63423463/using-pytorch-cuda-on-macbook-pro
    # т.к. на macbook на их процессорах apple silicon нет cuda (только для карт nvidia), то используем альтеранативу, но если есть cuda - то используем ее
    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')

    kwargs = {'num_workers': CFG.num_workers, 'pin_memory': torch.cuda.is_available()}

    # наши картинки в исходном размере 750*470 + если домножить на число каналов (3), то получится около миллиарда параметра на вход.
    # Это довольно много так что пропорционально уменьшим размерность. У нас 750 к 470 это, можно сказать, 1.6 к 1. Уменьшим 750 до 160 => 470 -> 96.
    # будем использовать различные методы аугментации https://docs.pytorch.org/vision/0.13/transforms.html
    train_transform = transforms.Compose([
        transforms.Resize((96, 160)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.1),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    test_transform = transforms.Compose([
        transforms.Resize((96, 160)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    train_ds = KolesaDataset(train_df, transform=train_transform)
    val_ds = KolesaDataset(val_df, transform=test_transform)
    # test_ds = KolesaDataset(test_df, transform=test_transform)

    train_loader = torch.utils.data.DataLoader(train_ds, batch_size=CFG.train_batch_size, **kwargs)
    val_loader = torch.utils.data.DataLoader(val_ds, batch_size=CFG.test_batch_size, **kwargs)
    # test_loader = torch.utils.data.DataLoader(test_ds, batch_size=CFG.test_batch_size, **kwargs)

    model = model.to(device)

    if CFG.wandb:
        wandb.watch(model, log='all')

    optimizer = optim.Adam(model.parameters(),
                          lr=CFG.lr)

    criterion = nn.CrossEntropyLoss()

    for epoch in range(1, CFG.num_epochs + 1):
        print('\nEpoch:', epoch)
        train(model, device, train_loader, optimizer, criterion, epoch, CFG.wandb)
        val(model, device, val_loader, criterion, CFG.wandb)

    print('Training is ended!')

### Сохранение моделей

Чтобы у каждой модели сохранялся артефакт, добавим маленькую вспомогательную функцию. `main_kolesa` логирует loss/accuracy по эпохам в W&B сам, а эта функция дописывает в тот же запуск файл с весами.

In [15]:
def save_model_artifact(model, name):
    # сохранение модели как артефакт
    # https://docs.wandb.ai/guides/artifacts
    path = f'../data/models/{name}.pt' #путь к файлу в зависимости от имени модели (передаем в начале), .pt -расширение для объектов pytorch
    torch.save(model.state_dict(), path) #сохраняем параметры модели
    if CFG.wandb:
        wandb.run.name = name   # называем запуск как модель
        artifact = wandb.Artifact(name, type='model') #создаем артефакт-контейннер
        artifact.add_file(path) #добавляем в него файл с параметрами модели (брали выше)
        wandb.log_artifact(artifact) #загружаем артефакт и привящываем к текущему щапуску
        wandb.finish()  # закрываем текущий запуск
    print(f'[OK] модель сохранена: {path}')

In [ ]:
# данные эксперимента в W&B
# https://docs.wandb.ai/guides/artifacts
if CFG.wandb:
    wandb.init(project=CFG.project, entity=CFG.entity, reinit=True, name='dataset')
    art = wandb.Artifact('kolesa-data', type='dataset')
    art.add_file('../data/prepared_df_images.csv')
    art.add_file('../data/brand_df_images.csv')
    art.add_dir('../data/images', name='images')
    wandb.log_artifact(art)
    wandb.finish()

## Fully Connected в качестве baseline

Возьмем для примера определение весов нормальным распределением

In [16]:
# определяем полносвязанную сеть
class FC_Net(nn.Module):
    def __init__(self, task='body_type'):
        super(FC_Net, self).__init__()

        self.task = task

        self.fc1 = nn.Linear(160*96*3, 1024)
        self.fc2 = nn.Linear(1024, 512)
        self.fc3 = nn.Linear(512, 128)
        if self.task == 'body_type':
            self.fc4 = nn.Linear(128, 2)
        elif self.task == 'brand':
            self.fc4 = nn.Linear(128, 8)

        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.normal_(m.weight)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        x = x.view(-1, 160*96*3)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return x

#### Задача на тип кузова

In [17]:
model_baseline_bt = FC_Net()

In [18]:
summary(model=model_baseline_bt,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
FC_Net                                   [32, 3, 96, 160]     [32, 2]              --                   True
├─Linear: 1-1                            [32, 46080]          [32, 1024]           47,186,944           True
├─Linear: 1-2                            [32, 1024]           [32, 512]            524,800              True
├─Linear: 1-3                            [32, 512]            [32, 128]            65,664               True
├─Linear: 1-4                            [32, 128]            [32, 2]              258                  True
========================================================================================================================
Total params: 47,777,666
Trainable params: 47,777,666
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 1.53
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 0.43
Params size (MB): 191.11
Estimated Total Size (MB): 197.44
========================================================================================================================

In [19]:
main_kolesa(model_baseline_bt, train_df = train_df_bt, val_df = val_df_bt)
save_model_artifact(model_baseline_bt, 'BaseLine_FC_body_type')

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

Epoch: 1

100%|██████████| 97/97 [00:18<00:00,  5.34it/s]

Train set: Average loss: 200857.7188, Accuracy: 54.04%
Val set: Average loss: 133297.0781, Accuracy: 54.74%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.58      0.62       418
         SUV       0.41      0.50      0.45       247

    accuracy                           0.55       665
   macro avg       0.54      0.54      0.53       665
weighted avg       0.57      0.55      0.55       665


Epoch: 2

100%|██████████| 97/97 [00:17<00:00,  5.61it/s]

Train set: Average loss: 100811.0938, Accuracy: 56.91%
Val set: Average loss: 111838.9922, Accuracy: 56.24%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.63      0.64       418
         SUV       0.42      0.45      0.43       247

    accuracy                           0.56       665
   macro avg       0.54      0.54      0.54       665
weighted avg       0.57      0.56      0.57       665


Epoch: 3

100%|██████████| 97/97 [00:17<00:00,  5.67it/s]

Train set: Average loss: 76628.9297, Accuracy: 59.27%
Val set: Average loss: 116528.6562, Accuracy: 52.93%

Classification report:
              precision    recall  f1-score   support

       sedan       0.65      0.53      0.59       418
         SUV       0.40      0.52      0.45       247

    accuracy                           0.53       665
   macro avg       0.53      0.53      0.52       665
weighted avg       0.56      0.53      0.54       665


Epoch: 4

100%|██████████| 97/97 [00:17<00:00,  5.67it/s]

Train set: Average loss: 60342.1797, Accuracy: 58.94%
Val set: Average loss: 97467.9453, Accuracy: 54.29%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.56      0.61       418
         SUV       0.41      0.52      0.46       247

    accuracy                           0.54       665
   macro avg       0.54      0.54      0.53       665
weighted avg       0.57      0.54      0.55       665


Epoch: 5

100%|██████████| 97/97 [00:17<00:00,  5.70it/s]

Train set: Average loss: 78568.7891, Accuracy: 61.36%
Val set: Average loss: 95941.6484, Accuracy: 55.04%

Classification report:
              precision    recall  f1-score   support

       sedan       0.65      0.62      0.63       418
         SUV       0.40      0.43      0.42       247

    accuracy                           0.55       665
   macro avg       0.53      0.53      0.53       665
weighted avg       0.56      0.55      0.55       665


Epoch: 6

100%|██████████| 97/97 [00:16<00:00,  5.92it/s]

Train set: Average loss: 63709.2031, Accuracy: 60.81%
Val set: Average loss: 91309.3672, Accuracy: 55.64%

Classification report:
              precision    recall  f1-score   support

       sedan       0.67      0.57      0.62       418
         SUV       0.42      0.53      0.47       247

    accuracy                           0.56       665
   macro avg       0.55      0.55      0.54       665
weighted avg       0.58      0.56      0.56       665


Epoch: 7

100%|██████████| 97/97 [00:14<00:00,  6.50it/s]

Train set: Average loss: 38697.9531, Accuracy: 64.29%
Val set: Average loss: 86777.7422, Accuracy: 54.29%

Classification report:
              precision    recall  f1-score   support

       sedan       0.65      0.59      0.62       418
         SUV       0.40      0.47      0.43       247

    accuracy                           0.54       665
   macro avg       0.53      0.53      0.52       665
weighted avg       0.56      0.54      0.55       665


Epoch: 8

100%|██████████| 97/97 [00:15<00:00,  6.40it/s]

Train set: Average loss: 64285.5820, Accuracy: 62.68%
Val set: Average loss: 83032.4453, Accuracy: 55.19%

Classification report:
              precision    recall  f1-score   support

       sedan       0.65      0.61      0.63       418
         SUV       0.41      0.45      0.42       247

    accuracy                           0.55       665
   macro avg       0.53      0.53      0.53       665
weighted avg       0.56      0.55      0.56       665


Epoch: 9

100%|██████████| 97/97 [00:14<00:00,  6.56it/s]

Train set: Average loss: 49918.4648, Accuracy: 64.87%
Val set: Average loss: 75215.9766, Accuracy: 56.24%

Classification report:
              precision    recall  f1-score   support

       sedan       0.68      0.57      0.62       418
         SUV       0.43      0.55      0.48       247

    accuracy                           0.56       665
   macro avg       0.56      0.56      0.55       665
weighted avg       0.59      0.56      0.57       665


Epoch: 10

100%|██████████| 97/97 [00:14<00:00,  6.55it/s]

Train set: Average loss: 31791.6484, Accuracy: 63.87%
Val set: Average loss: 77674.0156, Accuracy: 54.74%

Classification report:
              precision    recall  f1-score   support

       sedan       0.66      0.57      0.61       418
         SUV       0.41      0.51      0.46       247

    accuracy                           0.55       665
   macro avg       0.54      0.54      0.53       665
weighted avg       0.57      0.55      0.55       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

[OK] модель сохранена: ../data/models/BaseLine_FC_body_type.pt

Качество около рандомное, то есть не сильно лучше чем просто определять на рандом с 50% вероятностью (чуть меньше чем на 10% лучше)

#### Задача на определение марки

In [18]:
CFG.classes = all_brands

model_baseline_brand = FC_Net(task='brand')

In [21]:
summary(model=model_baseline_brand,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
FC_Net                                   [32, 3, 96, 160]     [32, 8]              --                   True
├─Linear: 1-1                            [32, 46080]          [32, 1024]           47,186,944           True
├─Linear: 1-2                            [32, 1024]           [32, 512]            524,800              True
├─Linear: 1-3                            [32, 512]            [32, 128]            65,664               True
├─Linear: 1-4                            [32, 128]            [32, 8]              1,032                True
========================================================================================================================
Total params: 47,778,440
Trainable params: 47,778,440
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 1.53
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 0.43
Params size (MB): 191.11
Estimated Total Size (MB): 197.44
========================================================================================================================

In [22]:
main_kolesa(model_baseline_brand, train_df = train_df_brand, val_df = val_df_brand)
save_model_artifact(model_baseline_brand, 'BaseLine_FC_brand')

Epoch: 1

100%|██████████| 97/97 [00:15<00:00,  6.36it/s]

Train set: Average loss: 285470.5938, Accuracy: 13.89%
Val set: Average loss: 388377.4688, Accuracy: 12.18%

Classification report:
               precision    recall  f1-score   support

         Audi       0.08      0.10      0.09        73
          BMW       0.17      0.09      0.12        90
    Chevrolet       0.15      0.19      0.17        79
      Hyundai       0.11      0.13      0.12        85
          Kia       0.16      0.16      0.16        77
        Lexus       0.13      0.13      0.13        95
Mercedes-Benz       0.10      0.11      0.11        81
       Toyota       0.08      0.08      0.08        85

     accuracy                           0.12       665
    macro avg       0.12      0.12      0.12       665
 weighted avg       0.13      0.12      0.12       665


Epoch: 2

100%|██████████| 97/97 [00:14<00:00,  6.53it/s]

Train set: Average loss: 319479.6875, Accuracy: 13.63%
Val set: Average loss: 333627.9688, Accuracy: 11.28%

Classification report:
               precision    recall  f1-score   support

         Audi       0.07      0.07      0.07        73
          BMW       0.14      0.12      0.13        90
    Chevrolet       0.13      0.15      0.14        79
      Hyundai       0.11      0.12      0.12        85
          Kia       0.13      0.10      0.12        77
        Lexus       0.09      0.12      0.10        95
Mercedes-Benz       0.14      0.11      0.12        81
       Toyota       0.10      0.11      0.11        85

     accuracy                           0.11       665
    macro avg       0.11      0.11      0.11       665
 weighted avg       0.11      0.11      0.11       665


Epoch: 3

100%|██████████| 97/97 [00:15<00:00,  6.39it/s]

Train set: Average loss: 183402.8125, Accuracy: 15.53%
Val set: Average loss: 283816.7188, Accuracy: 13.83%

Classification report:
               precision    recall  f1-score   support

         Audi       0.10      0.10      0.10        73
          BMW       0.13      0.11      0.12        90
    Chevrolet       0.14      0.15      0.14        79
      Hyundai       0.13      0.12      0.12        85
          Kia       0.19      0.18      0.19        77
        Lexus       0.12      0.16      0.14        95
Mercedes-Benz       0.16      0.15      0.15        81
       Toyota       0.15      0.14      0.14        85

     accuracy                           0.14       665
    macro avg       0.14      0.14      0.14       665
 weighted avg       0.14      0.14      0.14       665


Epoch: 4

100%|██████████| 97/97 [00:14<00:00,  6.48it/s]

Train set: Average loss: 216754.2812, Accuracy: 16.56%
Val set: Average loss: 251771.5625, Accuracy: 11.58%

Classification report:
               precision    recall  f1-score   support

         Audi       0.09      0.08      0.09        73
          BMW       0.14      0.10      0.12        90
    Chevrolet       0.09      0.11      0.10        79
      Hyundai       0.05      0.04      0.04        85
          Kia       0.17      0.19      0.18        77
        Lexus       0.12      0.17      0.14        95
Mercedes-Benz       0.14      0.12      0.13        81
       Toyota       0.10      0.11      0.10        85

     accuracy                           0.12       665
    macro avg       0.11      0.12      0.11       665
 weighted avg       0.11      0.12      0.11       665


Epoch: 5

100%|██████████| 97/97 [00:15<00:00,  6.39it/s]

Train set: Average loss: 173704.8281, Accuracy: 17.14%
Val set: Average loss: 220074.8438, Accuracy: 12.18%

Classification report:
               precision    recall  f1-score   support

         Audi       0.08      0.08      0.08        73
          BMW       0.19      0.12      0.15        90
    Chevrolet       0.12      0.15      0.13        79
      Hyundai       0.05      0.05      0.05        85
          Kia       0.19      0.18      0.19        77
        Lexus       0.12      0.15      0.13        95
Mercedes-Benz       0.14      0.12      0.13        81
       Toyota       0.13      0.12      0.12        85

     accuracy                           0.12       665
    macro avg       0.13      0.12      0.12       665
 weighted avg       0.13      0.12      0.12       665


Epoch: 6

100%|██████████| 97/97 [00:15<00:00,  6.28it/s]

Train set: Average loss: 98674.2578, Accuracy: 17.98%
Val set: Average loss: 188636.0625, Accuracy: 12.33%

Classification report:
               precision    recall  f1-score   support

         Audi       0.08      0.08      0.08        73
          BMW       0.13      0.10      0.11        90
    Chevrolet       0.08      0.09      0.09        79
      Hyundai       0.07      0.07      0.07        85
          Kia       0.15      0.13      0.14        77
        Lexus       0.12      0.16      0.14        95
Mercedes-Benz       0.20      0.16      0.18        81
       Toyota       0.16      0.19      0.17        85

     accuracy                           0.12       665
    macro avg       0.12      0.12      0.12       665
 weighted avg       0.13      0.12      0.12       665


Epoch: 7

100%|██████████| 97/97 [00:14<00:00,  6.56it/s]

Train set: Average loss: 81278.4922, Accuracy: 19.05%
Val set: Average loss: 165906.7500, Accuracy: 13.83%

Classification report:
               precision    recall  f1-score   support

         Audi       0.10      0.10      0.10        73
          BMW       0.17      0.13      0.15        90
    Chevrolet       0.17      0.18      0.17        79
      Hyundai       0.06      0.06      0.06        85
          Kia       0.16      0.13      0.14        77
        Lexus       0.15      0.18      0.16        95
Mercedes-Benz       0.16      0.17      0.17        81
       Toyota       0.14      0.15      0.14        85

     accuracy                           0.14       665
    macro avg       0.14      0.14      0.14       665
 weighted avg       0.14      0.14      0.14       665


Epoch: 8

100%|██████████| 97/97 [00:15<00:00,  6.39it/s]

Train set: Average loss: 75992.9062, Accuracy: 17.95%
Val set: Average loss: 142584.7344, Accuracy: 12.78%

Classification report:
               precision    recall  f1-score   support

         Audi       0.08      0.08      0.08        73
          BMW       0.16      0.12      0.14        90
    Chevrolet       0.13      0.16      0.15        79
      Hyundai       0.06      0.06      0.06        85
          Kia       0.13      0.12      0.12        77
        Lexus       0.14      0.17      0.15        95
Mercedes-Benz       0.13      0.12      0.13        81
       Toyota       0.16      0.18      0.17        85

     accuracy                           0.13       665
    macro avg       0.13      0.13      0.13       665
 weighted avg       0.13      0.13      0.13       665


Epoch: 9

100%|██████████| 97/97 [00:14<00:00,  6.52it/s]

Train set: Average loss: 44120.2031, Accuracy: 16.89%
Val set: Average loss: 118284.6562, Accuracy: 13.68%

Classification report:
               precision    recall  f1-score   support

         Audi       0.10      0.10      0.10        73
          BMW       0.14      0.12      0.13        90
    Chevrolet       0.17      0.20      0.19        79
      Hyundai       0.08      0.07      0.08        85
          Kia       0.15      0.16      0.15        77
        Lexus       0.16      0.19      0.17        95
Mercedes-Benz       0.16      0.14      0.15        81
       Toyota       0.11      0.12      0.12        85

     accuracy                           0.14       665
    macro avg       0.13      0.14      0.13       665
 weighted avg       0.13      0.14      0.14       665


Epoch: 10

100%|██████████| 97/97 [00:15<00:00,  6.35it/s]

Train set: Average loss: 15272.5332, Accuracy: 16.79%
Val set: Average loss: 98214.9688, Accuracy: 14.14%

Classification report:
               precision    recall  f1-score   support

         Audi       0.09      0.10      0.09        73
          BMW       0.14      0.11      0.12        90
    Chevrolet       0.16      0.15      0.15        79
      Hyundai       0.11      0.11      0.11        85
          Kia       0.20      0.17      0.18        77
        Lexus       0.19      0.20      0.20        95
Mercedes-Benz       0.16      0.12      0.14        81
       Toyota       0.10      0.16      0.13        85

     accuracy                           0.14       665
    macro avg       0.14      0.14      0.14       665
 weighted avg       0.15      0.14      0.14       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

[OK] модель сохранена: ../data/models/BaseLine_FC_brand.pt

Здесь уже чуть больше чем на 10% лучше чистого рандома, где угадать марку из 8 возможных - 12.5%. Но, в любом случае, такие результаты сильно плохи.

Попробуем далее сверточные сети.

## Простой CNN

In [19]:
class CNN_Net(nn.Module):
    def __init__(self, task='body_type'):
        super(CNN_Net, self).__init__()

        self.task = task

        self.conv1 = torch.nn.Conv2d(3, 16, 3, padding=1)
        self.act1  = torch.nn.ReLU()
        self.pool1 = torch.nn.MaxPool2d(2, 2) # 48 80

        self.conv2 = torch.nn.Conv2d(16, 32, 3, padding=1)
        self.act2  = torch.nn.ReLU()
        self.pool2 = torch.nn.MaxPool2d(2, 2) # 24 40

        self.conv3 = torch.nn.Conv2d(32, 64, 3, padding=1)
        self.act3  = torch.nn.ReLU()
        self.pool3 = torch.nn.MaxPool2d(2, 2) # 12 20

        self.fc1   = torch.nn.Linear(12 * 20 * 64, 256)
        self.act4  = torch.nn.Tanh()

        self.fc2   = torch.nn.Linear(256, 64)
        self.act5  = torch.nn.Tanh()
        
        if task == 'body_type':
            self.fc3   = torch.nn.Linear(64, 2)
        elif task == 'brand':
            self.fc3   = torch.nn.Linear(64, 8)

    def forward(self, x):
        x = self.conv1(x)
        x = self.act1(x)
        x = self.pool1(x)

        x = self.conv2(x)
        x = self.act2(x)
        x = self.pool2(x)

        x = self.conv3(x)
        x = self.act3(x)
        x = self.pool3(x)

        x = x.view(x.size(0), x.size(1) * x.size(2) * x.size(3))
        x = self.fc1(x)
        x = self.act4(x)
        x = self.fc2(x)
        x = self.act5(x)
        x = self.fc3(x)

        return x

#### Задача на тип кузова

In [20]:
CFG.classes = all_body_types

model_cnn_1_bt = CNN_Net()

In [25]:
summary(model=model_cnn_1_bt,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
CNN_Net                                  [32, 3, 96, 160]     [32, 2]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 16, 96, 160]    448                  True
├─ReLU: 1-2                              [32, 16, 96, 160]    [32, 16, 96, 160]    --                   --
├─MaxPool2d: 1-3                         [32, 16, 96, 160]    [32, 16, 48, 80]     --                   --
├─Conv2d: 1-4                            [32, 16, 48, 80]     [32, 32, 48, 80]     4,640                True
├─ReLU: 1-5                              [32, 32, 48, 80]     [32, 32, 48, 80]     --                   --
├─MaxPool2d: 1-6                         [32, 32, 48, 80]     [32, 32, 24, 40]     --                   --
├─Conv2d: 1-7                            [32, 32, 24, 40]     [32, 64, 24, 40]     18,496               True
├─ReLU: 1-8                              [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─MaxPool2d: 1-9                         [32, 64, 24, 40]     [32, 64, 12, 20]     --                   --
├─Linear: 1-10                           [32, 15360]          [32, 256]            3,932,416            True
├─Tanh: 1-11                             [32, 256]            [32, 256]            --                   --
├─Linear: 1-12                           [32, 256]            [32, 64]             16,448               True
├─Tanh: 1-13                             [32, 64]             [32, 64]             --                   --
├─Linear: 1-14                           [32, 64]             [32, 2]              130                  True
========================================================================================================================
Total params: 3,972,578
Trainable params: 3,972,578
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 1.48
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 110.18
Params size (MB): 15.89
Estimated Total Size (MB): 131.97
========================================================================================================================

In [26]:
main_kolesa(model_cnn_1_bt, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_cnn_1_bt, 'Base_CNN_body_type')

Epoch: 1

100%|██████████| 97/97 [00:15<00:00,  6.46it/s]

Train set: Average loss: 0.7569, Accuracy: 62.20%
Val set: Average loss: 0.6641, Accuracy: 63.61%

Classification report:
              precision    recall  f1-score   support

       sedan       0.63      1.00      0.78       418
         SUV       1.00      0.02      0.04       247

    accuracy                           0.64       665
   macro avg       0.82      0.51      0.41       665
weighted avg       0.77      0.64      0.50       665


Epoch: 2

100%|██████████| 97/97 [00:14<00:00,  6.54it/s]

Train set: Average loss: 0.6975, Accuracy: 63.33%
Val set: Average loss: 0.6965, Accuracy: 57.29%

Classification report:
              precision    recall  f1-score   support

       sedan       0.75      0.49      0.59       418
         SUV       0.45      0.72      0.56       247

    accuracy                           0.57       665
   macro avg       0.60      0.60      0.57       665
weighted avg       0.64      0.57      0.58       665


Epoch: 3

100%|██████████| 97/97 [00:14<00:00,  6.81it/s]

Train set: Average loss: 0.6492, Accuracy: 64.32%
Val set: Average loss: 0.6578, Accuracy: 61.80%

Classification report:
              precision    recall  f1-score   support

       sedan       0.74      0.61      0.67       418
         SUV       0.49      0.63      0.55       247

    accuracy                           0.62       665
   macro avg       0.61      0.62      0.61       665
weighted avg       0.64      0.62      0.62       665


Epoch: 4

100%|██████████| 97/97 [00:13<00:00,  7.01it/s]

Train set: Average loss: 0.6694, Accuracy: 65.87%
Val set: Average loss: 0.6508, Accuracy: 63.46%

Classification report:
              precision    recall  f1-score   support

       sedan       0.76      0.61      0.68       418
         SUV       0.51      0.67      0.58       247

    accuracy                           0.63       665
   macro avg       0.63      0.64      0.63       665
weighted avg       0.67      0.63      0.64       665


Epoch: 5

100%|██████████| 97/97 [00:14<00:00,  6.93it/s]

Train set: Average loss: 0.6443, Accuracy: 66.90%
Val set: Average loss: 0.6414, Accuracy: 64.51%

Classification report:
              precision    recall  f1-score   support

       sedan       0.75      0.65      0.70       418
         SUV       0.52      0.63      0.57       247

    accuracy                           0.65       665
   macro avg       0.63      0.64      0.63       665
weighted avg       0.66      0.65      0.65       665


Epoch: 6

100%|██████████| 97/97 [00:14<00:00,  6.84it/s]

Train set: Average loss: 0.6381, Accuracy: 68.16%
Val set: Average loss: 0.6491, Accuracy: 64.36%

Classification report:
              precision    recall  f1-score   support

       sedan       0.74      0.67      0.70       418
         SUV       0.52      0.60      0.56       247

    accuracy                           0.64       665
   macro avg       0.63      0.63      0.63       665
weighted avg       0.66      0.64      0.65       665


Epoch: 7

100%|██████████| 97/97 [00:13<00:00,  6.98it/s]

Train set: Average loss: 0.5841, Accuracy: 68.68%
Val set: Average loss: 0.6449, Accuracy: 66.02%

Classification report:
              precision    recall  f1-score   support

       sedan       0.77      0.66      0.71       418
         SUV       0.53      0.67      0.59       247

    accuracy                           0.66       665
   macro avg       0.65      0.66      0.65       665
weighted avg       0.68      0.66      0.67       665


Epoch: 8

100%|██████████| 97/97 [00:15<00:00,  6.45it/s]

Train set: Average loss: 0.6351, Accuracy: 70.67%
Val set: Average loss: 0.6422, Accuracy: 65.71%

Classification report:
              precision    recall  f1-score   support

       sedan       0.74      0.70      0.72       418
         SUV       0.53      0.59      0.56       247

    accuracy                           0.66       665
   macro avg       0.64      0.64      0.64       665
weighted avg       0.67      0.66      0.66       665


Epoch: 9

100%|██████████| 97/97 [00:14<00:00,  6.52it/s]

Train set: Average loss: 0.5870, Accuracy: 71.35%
Val set: Average loss: 0.6589, Accuracy: 64.06%

Classification report:
              precision    recall  f1-score   support

       sedan       0.75      0.65      0.69       418
         SUV       0.51      0.62      0.56       247

    accuracy                           0.64       665
   macro avg       0.63      0.64      0.63       665
weighted avg       0.66      0.64      0.65       665


Epoch: 10

100%|██████████| 97/97 [00:14<00:00,  6.70it/s]

Train set: Average loss: 0.6076, Accuracy: 72.32%
Val set: Average loss: 0.6844, Accuracy: 63.61%

Classification report:
              precision    recall  f1-score   support

       sedan       0.76      0.61      0.68       418
         SUV       0.51      0.68      0.58       247

    accuracy                           0.64       665
   macro avg       0.64      0.65      0.63       665
weighted avg       0.67      0.64      0.64       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

[OK] модель сохранена: ../data/models/Base_CNN_body_type.pt

Уже получше, на +-20% лучшем чем FC, но пока что такая точность слишком низка для нашей задачи.

#### Задача на определение марки

In [21]:
CFG.classes = all_brands

model_cnn_1_brand = CNN_Net(task='brand')

In [28]:
summary(model=model_cnn_1_brand,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
CNN_Net                                  [32, 3, 96, 160]     [32, 8]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 16, 96, 160]    448                  True
├─ReLU: 1-2                              [32, 16, 96, 160]    [32, 16, 96, 160]    --                   --
├─MaxPool2d: 1-3                         [32, 16, 96, 160]    [32, 16, 48, 80]     --                   --
├─Conv2d: 1-4                            [32, 16, 48, 80]     [32, 32, 48, 80]     4,640                True
├─ReLU: 1-5                              [32, 32, 48, 80]     [32, 32, 48, 80]     --                   --
├─MaxPool2d: 1-6                         [32, 32, 48, 80]     [32, 32, 24, 40]     --                   --
├─Conv2d: 1-7                            [32, 32, 24, 40]     [32, 64, 24, 40]     18,496               True
├─ReLU: 1-8                              [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─MaxPool2d: 1-9                         [32, 64, 24, 40]     [32, 64, 12, 20]     --                   --
├─Linear: 1-10                           [32, 15360]          [32, 256]            3,932,416            True
├─Tanh: 1-11                             [32, 256]            [32, 256]            --                   --
├─Linear: 1-12                           [32, 256]            [32, 64]             16,448               True
├─Tanh: 1-13                             [32, 64]             [32, 64]             --                   --
├─Linear: 1-14                           [32, 64]             [32, 8]              520                  True
========================================================================================================================
Total params: 3,972,968
Trainable params: 3,972,968
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 1.48
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 110.18
Params size (MB): 15.89
Estimated Total Size (MB): 131.97
========================================================================================================================

In [29]:
main_kolesa(model_cnn_1_brand, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_cnn_1_brand, 'Base_CNN_brand')

Epoch: 1

100%|██████████| 97/97 [00:14<00:00,  6.65it/s]

Train set: Average loss: 2.0729, Accuracy: 14.24%

/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Val set: Average loss: 2.0768, Accuracy: 14.14%

Classification report:
               precision    recall  f1-score   support

         Audi       0.00      0.00      0.00        73
          BMW       0.11      0.33      0.17        90
    Chevrolet       0.21      0.23      0.22        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.23      0.17      0.20        77
        Lexus       0.17      0.24      0.20        95
Mercedes-Benz       0.04      0.01      0.02        81
       Toyota       0.09      0.11      0.10        85

     accuracy                           0.14       665
    macro avg       0.11      0.14      0.11       665
 weighted avg       0.11      0.14      0.11       665


Epoch: 2

100%|██████████| 97/97 [00:14<00:00,  6.91it/s]

Train set: Average loss: 2.0585, Accuracy: 17.31%

/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Val set: Average loss: 2.0692, Accuracy: 16.09%

Classification report:
               precision    recall  f1-score   support

         Audi       0.00      0.00      0.00        73
          BMW       0.14      0.58      0.22        90
    Chevrolet       0.32      0.13      0.18        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.22      0.13      0.16        77
        Lexus       0.15      0.08      0.11        95
Mercedes-Benz       0.17      0.22      0.19        81
       Toyota       0.20      0.11      0.14        85

     accuracy                           0.16       665
    macro avg       0.15      0.16      0.13       665
 weighted avg       0.15      0.16      0.13       665


Epoch: 3

100%|██████████| 97/97 [00:14<00:00,  6.78it/s]

Train set: Average loss: 2.0210, Accuracy: 18.82%

/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Val set: Average loss: 2.0707, Accuracy: 15.94%

Classification report:
               precision    recall  f1-score   support

         Audi       0.40      0.03      0.05        73
          BMW       0.13      0.60      0.22        90
    Chevrolet       0.29      0.09      0.14        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.23      0.17      0.20        77
        Lexus       0.26      0.11      0.15        95
Mercedes-Benz       0.15      0.16      0.15        81
       Toyota       0.14      0.08      0.10        85

     accuracy                           0.16       665
    macro avg       0.20      0.15      0.13       665
 weighted avg       0.20      0.16      0.13       665


Epoch: 4

100%|██████████| 97/97 [00:14<00:00,  6.91it/s]

Train set: Average loss: 2.0166, Accuracy: 21.04%
Val set: Average loss: 2.0714, Accuracy: 16.84%

Classification report:
               precision    recall  f1-score   support

         Audi       0.25      0.03      0.05        73
          BMW       0.15      0.49      0.23        90
    Chevrolet       0.31      0.13      0.18        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.21      0.17      0.19        77
        Lexus       0.20      0.11      0.14        95
Mercedes-Benz       0.16      0.30      0.21        81
       Toyota       0.15      0.11      0.12        85

     accuracy                           0.17       665
    macro avg       0.18      0.16      0.14       665
 weighted avg       0.18      0.17      0.14       665


Epoch: 5

100%|██████████| 97/97 [00:14<00:00,  6.79it/s]

Train set: Average loss: 1.9941, Accuracy: 22.08%
Val set: Average loss: 2.0593, Accuracy: 16.99%

Classification report:
               precision    recall  f1-score   support

         Audi       0.17      0.11      0.13        73
          BMW       0.14      0.41      0.21        90
    Chevrolet       0.45      0.18      0.25        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.16      0.21      0.18        77
        Lexus       0.18      0.07      0.10        95
Mercedes-Benz       0.17      0.25      0.20        81
       Toyota       0.15      0.13      0.14        85

     accuracy                           0.17       665
    macro avg       0.18      0.17      0.15       665
 weighted avg       0.18      0.17      0.15       665


Epoch: 6

100%|██████████| 97/97 [00:14<00:00,  6.71it/s]

Train set: Average loss: 1.9233, Accuracy: 24.94%
Val set: Average loss: 2.0716, Accuracy: 17.14%

Classification report:
               precision    recall  f1-score   support

         Audi       0.11      0.08      0.09        73
          BMW       0.16      0.36      0.22        90
    Chevrolet       0.47      0.10      0.17        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.18      0.19      0.19        77
        Lexus       0.21      0.14      0.17        95
Mercedes-Benz       0.17      0.36      0.23        81
       Toyota       0.15      0.13      0.14        85

     accuracy                           0.17       665
    macro avg       0.18      0.17      0.15       665
 weighted avg       0.18      0.17      0.15       665


Epoch: 7

100%|██████████| 97/97 [00:14<00:00,  6.67it/s]

Train set: Average loss: 1.8667, Accuracy: 25.91%

/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ksa/smadimo/dev_gp5/gp_5_DL/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Val set: Average loss: 2.1014, Accuracy: 17.44%

Classification report:
               precision    recall  f1-score   support

         Audi       0.13      0.14      0.13        73
          BMW       0.17      0.26      0.21        90
    Chevrolet       0.39      0.18      0.24        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.18      0.14      0.16        77
        Lexus       0.17      0.17      0.17        95
Mercedes-Benz       0.15      0.40      0.22        81
       Toyota       0.19      0.12      0.15        85

     accuracy                           0.17       665
    macro avg       0.17      0.17      0.16       665
 weighted avg       0.17      0.17      0.16       665


Epoch: 8

100%|██████████| 97/97 [00:14<00:00,  6.51it/s]

Train set: Average loss: 1.8840, Accuracy: 28.07%
Val set: Average loss: 2.1148, Accuracy: 19.40%

Classification report:
               precision    recall  f1-score   support

         Audi       0.15      0.14      0.14        73
          BMW       0.21      0.39      0.27        90
    Chevrolet       0.35      0.18      0.24        79
      Hyundai       0.12      0.01      0.02        85
          Kia       0.25      0.13      0.17        77
        Lexus       0.23      0.08      0.12        95
Mercedes-Benz       0.18      0.44      0.26        81
       Toyota       0.14      0.18      0.16        85

     accuracy                           0.19       665
    macro avg       0.20      0.19      0.17       665
 weighted avg       0.20      0.19      0.17       665


Epoch: 9

100%|██████████| 97/97 [00:15<00:00,  6.43it/s]

Train set: Average loss: 1.7233, Accuracy: 31.20%
Val set: Average loss: 2.1486, Accuracy: 18.20%

Classification report:
               precision    recall  f1-score   support

         Audi       0.12      0.12      0.12        73
          BMW       0.22      0.39      0.28        90
    Chevrolet       0.36      0.19      0.25        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.23      0.17      0.20        77
        Lexus       0.17      0.11      0.13        95
Mercedes-Benz       0.15      0.33      0.20        81
       Toyota       0.14      0.14      0.14        85

     accuracy                           0.18       665
    macro avg       0.17      0.18      0.16       665
 weighted avg       0.17      0.18      0.16       665


Epoch: 10

100%|██████████| 97/97 [00:15<00:00,  6.40it/s]

Train set: Average loss: 1.5459, Accuracy: 33.23%
Val set: Average loss: 2.1410, Accuracy: 19.10%

Classification report:
               precision    recall  f1-score   support

         Audi       0.17      0.22      0.19        73
          BMW       0.22      0.48      0.30        90
    Chevrolet       0.50      0.16      0.25        79
      Hyundai       0.10      0.01      0.02        85
          Kia       0.22      0.18      0.20        77
        Lexus       0.19      0.08      0.12        95
Mercedes-Benz       0.15      0.26      0.19        81
       Toyota       0.12      0.13      0.12        85

     accuracy                           0.19       665
    macro avg       0.21      0.19      0.17       665
 weighted avg       0.21      0.19      0.17       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: WARNING Artifact "Base_CNN_brand" already exists with the same content. No new version will be created.

[OK] модель сохранена: ../data/models/Base_CNN_brand.pt

Прирост выше, чем для задачи на кузов, уже чуть более 30%, хотя это также все еще плохо, с какими-то марками (как к примеру Hyundai, где по ней precision и recall по нулям) большие проблемы

## CNN с регуляризацией

Теперь попробуем добавить регуляризацию, а именно известные нам BatchNorm и Dropout.

Также поменяем функции активации https://deepmachinelearning.ru/docs/Neural-networks/MLP/Activation-functions. В частности попробуем LeakyReLU.

И наконец добавим побольше сверточных слоев.

In [22]:
class CNNReg_Net(nn.Module):
    def __init__(self, task='body_type'):
        super(CNNReg_Net, self).__init__()

        self.task = task

        self.conv3 = torch.nn.Conv2d(3, 32, 3, padding=1)
        self.bn3   = torch.nn.BatchNorm2d(32)
        self.act3  = torch.nn.LeakyReLU()

        self.conv4 = torch.nn.Conv2d(32, 32, 3, padding=1)
        self.bn4   = torch.nn.BatchNorm2d(32)
        self.act4  = torch.nn.LeakyReLU()
        self.pool2 = torch.nn.MaxPool2d(2, 2) # 24 40

        self.conv5 = torch.nn.Conv2d(32, 64, 3, padding=1)
        self.bn5   = torch.nn.BatchNorm2d(64)
        self.act5  = torch.nn.LeakyReLU()

        self.conv6 = torch.nn.Conv2d(64, 64, 3, padding=1)
        self.bn6   = torch.nn.BatchNorm2d(64)
        self.act6  = torch.nn.LeakyReLU()
        self.pool3 = torch.nn.MaxPool2d(2, 2) # 12 20

        self.drop1 = torch.nn.Dropout2d(0.10)

        self.conv7 = torch.nn.Conv2d(64, 128, 3, padding=1)
        self.bn7   = torch.nn.BatchNorm2d(128)
        self.act7  = torch.nn.LeakyReLU()
        self.drop2 = torch.nn.Dropout2d(0.15)

        self.conv8 = torch.nn.Conv2d(128, 128, 3, padding=1)
        self.bn8   = torch.nn.BatchNorm2d(128)
        self.act8  = torch.nn.LeakyReLU()
        self.pool4 = torch.nn.MaxPool2d(2, 2)
        self.drop3 = torch.nn.Dropout2d(0.2)

        self.conv9 = torch.nn.Conv2d(128, 256, 3, padding=1)
        self.bn9   = torch.nn.BatchNorm2d(256)
        self.act9  = torch.nn.LeakyReLU()
        self.pool5 = torch.nn.MaxPool2d(2, 2)
        self.drop4 = torch.nn.Dropout2d(0.25)

        self.fc1   = torch.nn.Linear(6 * 10 * 256, 256)
        self.bn10  = torch.nn.BatchNorm1d(256)
        self.act10 = torch.nn.LeakyReLU()
        self.drop5 = torch.nn.Dropout(0.3)

        self.fc2   = torch.nn.Linear(256, 64)
        self.act11 = torch.nn.LeakyReLU()
        self.drop6 = torch.nn.Dropout(0.2)

        if task == 'body_type':
            self.fc3 = torch.nn.Linear(64, 2)
        elif task == 'brand':
            self.fc3 = torch.nn.Linear(64, 8)
            

    def forward(self, x):
        x = self.conv3(x)
        x = self.bn3(x)
        x = self.act3(x)

        x = self.conv4(x)
        x = self.bn4(x)
        x = self.act4(x)
        x = self.pool2(x)

        x = self.conv5(x)
        x = self.bn5(x)
        x = self.act5(x)

        x = self.conv6(x)
        x = self.bn6(x)
        x = self.act6(x)
        x = self.pool3(x)
        x = self.drop1(x)

        x = self.conv7(x)
        x = self.bn7(x)
        x = self.act7(x)
        x = self.drop2(x)

        x = self.conv8(x)
        x = self.bn8(x)
        x = self.act8(x)
        x = self.pool4(x)
        x = self.drop3(x)

        x = self.conv9(x)
        x = self.bn9(x)
        x = self.act9(x)
        x = self.pool5(x)
        x = self.drop4(x)

        x = x.view(x.size(0), x.size(1) * x.size(2) * x.size(3))
        x = self.fc1(x)
        x = self.bn10(x)
        x = self.act10(x)
        x = self.drop5(x)

        x = self.fc2(x)
        x = self.act11(x)
        x = self.drop6(x)

        x = self.fc3(x)

        return x

На этой модели попробуем побольше эпох

In [23]:
CFG.num_epochs = 20

#### Задача на тип кузова

In [24]:
CFG.classes = all_body_types

model_cnn_2_bt = CNNReg_Net()

In [33]:
summary(model=model_cnn_2_bt,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
CNNReg_Net                               [32, 3, 96, 160]     [32, 2]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 32, 96, 160]    896                  True
├─BatchNorm2d: 1-2                       [32, 32, 96, 160]    [32, 32, 96, 160]    64                   True
├─LeakyReLU: 1-3                         [32, 32, 96, 160]    [32, 32, 96, 160]    --                   --
├─Conv2d: 1-4                            [32, 32, 96, 160]    [32, 32, 96, 160]    9,248                True
├─BatchNorm2d: 1-5                       [32, 32, 96, 160]    [32, 32, 96, 160]    64                   True
├─LeakyReLU: 1-6                         [32, 32, 96, 160]    [32, 32, 96, 160]    --                   --
├─MaxPool2d: 1-7                         [32, 32, 96, 160]    [32, 32, 48, 80]     --                   --
├─Conv2d: 1-8                            [32, 32, 48, 80]     [32, 64, 48, 80]     18,496               True
├─BatchNorm2d: 1-9                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─LeakyReLU: 1-10                        [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─Conv2d: 1-11                           [32, 64, 48, 80]     [32, 64, 48, 80]     36,928               True
├─BatchNorm2d: 1-12                      [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─LeakyReLU: 1-13                        [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-14                        [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Dropout2d: 1-15                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Conv2d: 1-16                           [32, 64, 24, 40]     [32, 128, 24, 40]    73,856               True
├─BatchNorm2d: 1-17                      [32, 128, 24, 40]    [32, 128, 24, 40]    256                  True
├─LeakyReLU: 1-18                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─Dropout2d: 1-19                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─Conv2d: 1-20                           [32, 128, 24, 40]    [32, 128, 24, 40]    147,584              True
├─BatchNorm2d: 1-21                      [32, 128, 24, 40]    [32, 128, 24, 40]    256                  True
├─LeakyReLU: 1-22                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─MaxPool2d: 1-23                        [32, 128, 24, 40]    [32, 128, 12, 20]    --                   --
├─Dropout2d: 1-24                        [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Conv2d: 1-25                           [32, 128, 12, 20]    [32, 256, 12, 20]    295,168              True
├─BatchNorm2d: 1-26                      [32, 256, 12, 20]    [32, 256, 12, 20]    512                  True
├─LeakyReLU: 1-27                        [32, 256, 12, 20]    [32, 256, 12, 20]    --                   --
├─MaxPool2d: 1-28                        [32, 256, 12, 20]    [32, 256, 6, 10]     --                   --
├─Dropout2d: 1-29                        [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Linear: 1-30                           [32, 15360]          [32, 256]            3,932,416            True
├─BatchNorm1d: 1-31                      [32, 256]            [32, 256]            512                  True
├─LeakyReLU: 1-32                        [32, 256]            [32, 256]            --                   --
├─Dropout: 1-33                          [32, 256]            [32, 256]            --                   --
├─Linear: 1-34                           [32, 256]            [32, 64]             16,448               True
├─LeakyReLU: 1-35                        [32, 64]             [32, 64]             --                   --
├─Dropout: 1-36                          [32, 64]             [32, 64]             --                   --
├─Linear: 1-37                           [32, 64]             [32, 2]              130                  True
========================================================================================================================
Total params: 4,533,090
Trainable params: 4,533,090
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 20.99
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 912.41
Params size (MB): 18.13
Estimated Total Size (MB): 936.44
========================================================================================================================

In [34]:
main_kolesa(model_cnn_2_bt, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_cnn_2_bt, 'Reg_CNN_body_type')

Epoch: 1

100%|██████████| 97/97 [00:18<00:00,  5.37it/s]

Train set: Average loss: 0.8177, Accuracy: 61.20%
Val set: Average loss: 0.6174, Accuracy: 65.86%

Classification report:
              precision    recall  f1-score   support

       sedan       0.67      0.92      0.77       418
         SUV       0.61      0.22      0.32       247

    accuracy                           0.66       665
   macro avg       0.64      0.57      0.55       665
weighted avg       0.65      0.66      0.60       665


Epoch: 2

100%|██████████| 97/97 [00:17<00:00,  5.50it/s]

Train set: Average loss: 0.7784, Accuracy: 63.81%
Val set: Average loss: 0.6206, Accuracy: 65.86%

Classification report:
              precision    recall  f1-score   support

       sedan       0.70      0.79      0.74       418
         SUV       0.55      0.44      0.49       247

    accuracy                           0.66       665
   macro avg       0.63      0.61      0.62       665
weighted avg       0.65      0.66      0.65       665


Epoch: 3

100%|██████████| 97/97 [00:17<00:00,  5.46it/s]

Train set: Average loss: 0.7358, Accuracy: 66.03%
Val set: Average loss: 0.5984, Accuracy: 68.12%

Classification report:
              precision    recall  f1-score   support

       sedan       0.70      0.87      0.77       418
         SUV       0.62      0.37      0.46       247

    accuracy                           0.68       665
   macro avg       0.66      0.62      0.62       665
weighted avg       0.67      0.68      0.66       665


Epoch: 4

100%|██████████| 97/97 [00:18<00:00,  5.37it/s]

Train set: Average loss: 0.7786, Accuracy: 66.87%
Val set: Average loss: 0.6243, Accuracy: 62.56%

Classification report:
              precision    recall  f1-score   support

       sedan       0.76      0.60      0.67       418
         SUV       0.50      0.68      0.57       247

    accuracy                           0.63       665
   macro avg       0.63      0.64      0.62       665
weighted avg       0.66      0.63      0.63       665


Epoch: 5

100%|██████████| 97/97 [00:17<00:00,  5.57it/s]

Train set: Average loss: 0.7299, Accuracy: 67.42%
Val set: Average loss: 0.5743, Accuracy: 69.17%

Classification report:
              precision    recall  f1-score   support

       sedan       0.70      0.88      0.78       418
         SUV       0.65      0.38      0.48       247

    accuracy                           0.69       665
   macro avg       0.68      0.63      0.63       665
weighted avg       0.68      0.69      0.67       665


Epoch: 6

100%|██████████| 97/97 [00:17<00:00,  5.58it/s]

Train set: Average loss: 0.7552, Accuracy: 69.13%
Val set: Average loss: 0.5614, Accuracy: 70.08%

Classification report:
              precision    recall  f1-score   support

       sedan       0.75      0.79      0.77       418
         SUV       0.61      0.54      0.57       247

    accuracy                           0.70       665
   macro avg       0.68      0.67      0.67       665
weighted avg       0.70      0.70      0.70       665


Epoch: 7

100%|██████████| 97/97 [00:17<00:00,  5.61it/s]

Train set: Average loss: 0.6837, Accuracy: 71.09%
Val set: Average loss: 0.5664, Accuracy: 70.08%

Classification report:
              precision    recall  f1-score   support

       sedan       0.73      0.83      0.78       418
         SUV       0.63      0.48      0.54       247

    accuracy                           0.70       665
   macro avg       0.68      0.66      0.66       665
weighted avg       0.69      0.70      0.69       665


Epoch: 8

100%|██████████| 97/97 [00:17<00:00,  5.57it/s]

Train set: Average loss: 0.6593, Accuracy: 71.19%
Val set: Average loss: 0.6563, Accuracy: 62.56%

Classification report:
              precision    recall  f1-score   support

       sedan       0.80      0.54      0.64       418
         SUV       0.50      0.77      0.61       247

    accuracy                           0.63       665
   macro avg       0.65      0.66      0.62       665
weighted avg       0.69      0.63      0.63       665


Epoch: 9

100%|██████████| 97/97 [00:17<00:00,  5.57it/s]

Train set: Average loss: 0.6846, Accuracy: 72.51%
Val set: Average loss: 0.6299, Accuracy: 66.32%

Classification report:
              precision    recall  f1-score   support

       sedan       0.80      0.61      0.70       418
         SUV       0.53      0.74      0.62       247

    accuracy                           0.66       665
   macro avg       0.67      0.68      0.66       665
weighted avg       0.70      0.66      0.67       665


Epoch: 10

100%|██████████| 97/97 [00:17<00:00,  5.57it/s]

Train set: Average loss: 0.7253, Accuracy: 73.32%
Val set: Average loss: 0.6047, Accuracy: 68.12%

Classification report:
              precision    recall  f1-score   support

       sedan       0.82      0.63      0.71       418
         SUV       0.55      0.76      0.64       247

    accuracy                           0.68       665
   macro avg       0.68      0.70      0.68       665
weighted avg       0.72      0.68      0.69       665


Epoch: 11

100%|██████████| 97/97 [00:17<00:00,  5.53it/s]

Train set: Average loss: 0.6024, Accuracy: 74.09%
Val set: Average loss: 0.5237, Accuracy: 73.23%

Classification report:
              precision    recall  f1-score   support

       sedan       0.79      0.78      0.78       418
         SUV       0.63      0.66      0.65       247

    accuracy                           0.73       665
   macro avg       0.71      0.72      0.72       665
weighted avg       0.73      0.73      0.73       665


Epoch: 12

100%|██████████| 97/97 [00:17<00:00,  5.64it/s]

Train set: Average loss: 0.6058, Accuracy: 74.86%
Val set: Average loss: 0.5638, Accuracy: 73.08%

Classification report:
              precision    recall  f1-score   support

       sedan       0.81      0.75      0.78       418
         SUV       0.62      0.70      0.66       247

    accuracy                           0.73       665
   macro avg       0.72      0.72      0.72       665
weighted avg       0.74      0.73      0.73       665


Epoch: 13

100%|██████████| 97/97 [00:22<00:00,  4.40it/s]

Train set: Average loss: 0.6263, Accuracy: 75.70%
Val set: Average loss: 0.5300, Accuracy: 73.53%

Classification report:
              precision    recall  f1-score   support

       sedan       0.79      0.78      0.79       418
         SUV       0.64      0.65      0.65       247

    accuracy                           0.74       665
   macro avg       0.72      0.72      0.72       665
weighted avg       0.74      0.74      0.74       665


Epoch: 14

100%|██████████| 97/97 [00:19<00:00,  4.87it/s]

Train set: Average loss: 0.7861, Accuracy: 76.64%
Val set: Average loss: 0.5942, Accuracy: 71.13%

Classification report:
              precision    recall  f1-score   support

       sedan       0.84      0.67      0.74       418
         SUV       0.58      0.79      0.67       247

    accuracy                           0.71       665
   macro avg       0.71      0.73      0.71       665
weighted avg       0.75      0.71      0.72       665


Epoch: 15

100%|██████████| 97/97 [00:17<00:00,  5.54it/s]

Train set: Average loss: 0.5584, Accuracy: 76.51%
Val set: Average loss: 0.6320, Accuracy: 68.42%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.61      0.71       418
         SUV       0.55      0.82      0.66       247

    accuracy                           0.68       665
   macro avg       0.70      0.71      0.68       665
weighted avg       0.74      0.68      0.69       665


Epoch: 16

100%|██████████| 97/97 [00:17<00:00,  5.60it/s]

Train set: Average loss: 0.7225, Accuracy: 76.89%
Val set: Average loss: 0.5288, Accuracy: 73.08%

Classification report:
              precision    recall  f1-score   support

       sedan       0.82      0.74      0.77       418
         SUV       0.62      0.72      0.67       247

    accuracy                           0.73       665
   macro avg       0.72      0.73      0.72       665
weighted avg       0.74      0.73      0.73       665


Epoch: 17

100%|██████████| 97/97 [00:17<00:00,  5.44it/s]

Train set: Average loss: 0.7318, Accuracy: 78.89%
Val set: Average loss: 0.6057, Accuracy: 71.28%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.66      0.74       418
         SUV       0.58      0.81      0.68       247

    accuracy                           0.71       665
   macro avg       0.72      0.73      0.71       665
weighted avg       0.75      0.71      0.72       665


Epoch: 18

100%|██████████| 97/97 [00:17<00:00,  5.58it/s]

Train set: Average loss: 0.6506, Accuracy: 79.83%
Val set: Average loss: 0.5478, Accuracy: 73.38%

Classification report:
              precision    recall  f1-score   support

       sedan       0.83      0.73      0.78       418
         SUV       0.62      0.74      0.67       247

    accuracy                           0.73       665
   macro avg       0.72      0.74      0.72       665
weighted avg       0.75      0.73      0.74       665


Epoch: 19

100%|██████████| 97/97 [00:18<00:00,  5.26it/s]

Train set: Average loss: 0.6476, Accuracy: 78.99%
Val set: Average loss: 0.6206, Accuracy: 69.47%

Classification report:
              precision    recall  f1-score   support

       sedan       0.82      0.65      0.73       418
         SUV       0.57      0.77      0.65       247

    accuracy                           0.69       665
   macro avg       0.70      0.71      0.69       665
weighted avg       0.73      0.69      0.70       665


Epoch: 20

100%|██████████| 97/97 [00:17<00:00,  5.46it/s]

Train set: Average loss: 0.4856, Accuracy: 79.28%
Val set: Average loss: 0.6110, Accuracy: 67.82%

Classification report:
              precision    recall  f1-score   support

       sedan       0.83      0.62      0.71       418
         SUV       0.55      0.78      0.64       247

    accuracy                           0.68       665
   macro avg       0.69      0.70      0.68       665
weighted avg       0.72      0.68      0.68       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

[OK] модель сохранена: ../data/models/Reg_CNN_body_type.pt

73.38% accuracy на лучшей эпохе это уже более-менее, хотя пока что с SUV, которых меньше, все еще сложнее, из-за этого доверять этой модели сложно.

#### Задача на определение марки

In [25]:
CFG.classes = all_brands

model_cnn_2_brand = CNNReg_Net(task='brand')

In [36]:
summary(model=model_cnn_2_brand,
        input_size=(32, 3, 96, 160), # входной батч
        col_names=["input_size", "output_size", "num_params", "trainable"], # что хотим посмотреть
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
CNNReg_Net                               [32, 3, 96, 160]     [32, 8]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 32, 96, 160]    896                  True
├─BatchNorm2d: 1-2                       [32, 32, 96, 160]    [32, 32, 96, 160]    64                   True
├─LeakyReLU: 1-3                         [32, 32, 96, 160]    [32, 32, 96, 160]    --                   --
├─Conv2d: 1-4                            [32, 32, 96, 160]    [32, 32, 96, 160]    9,248                True
├─BatchNorm2d: 1-5                       [32, 32, 96, 160]    [32, 32, 96, 160]    64                   True
├─LeakyReLU: 1-6                         [32, 32, 96, 160]    [32, 32, 96, 160]    --                   --
├─MaxPool2d: 1-7                         [32, 32, 96, 160]    [32, 32, 48, 80]     --                   --
├─Conv2d: 1-8                            [32, 32, 48, 80]     [32, 64, 48, 80]     18,496               True
├─BatchNorm2d: 1-9                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─LeakyReLU: 1-10                        [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─Conv2d: 1-11                           [32, 64, 48, 80]     [32, 64, 48, 80]     36,928               True
├─BatchNorm2d: 1-12                      [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─LeakyReLU: 1-13                        [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-14                        [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Dropout2d: 1-15                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Conv2d: 1-16                           [32, 64, 24, 40]     [32, 128, 24, 40]    73,856               True
├─BatchNorm2d: 1-17                      [32, 128, 24, 40]    [32, 128, 24, 40]    256                  True
├─LeakyReLU: 1-18                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─Dropout2d: 1-19                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─Conv2d: 1-20                           [32, 128, 24, 40]    [32, 128, 24, 40]    147,584              True
├─BatchNorm2d: 1-21                      [32, 128, 24, 40]    [32, 128, 24, 40]    256                  True
├─LeakyReLU: 1-22                        [32, 128, 24, 40]    [32, 128, 24, 40]    --                   --
├─MaxPool2d: 1-23                        [32, 128, 24, 40]    [32, 128, 12, 20]    --                   --
├─Dropout2d: 1-24                        [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Conv2d: 1-25                           [32, 128, 12, 20]    [32, 256, 12, 20]    295,168              True
├─BatchNorm2d: 1-26                      [32, 256, 12, 20]    [32, 256, 12, 20]    512                  True
├─LeakyReLU: 1-27                        [32, 256, 12, 20]    [32, 256, 12, 20]    --                   --
├─MaxPool2d: 1-28                        [32, 256, 12, 20]    [32, 256, 6, 10]     --                   --
├─Dropout2d: 1-29                        [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Linear: 1-30                           [32, 15360]          [32, 256]            3,932,416            True
├─BatchNorm1d: 1-31                      [32, 256]            [32, 256]            512                  True
├─LeakyReLU: 1-32                        [32, 256]            [32, 256]            --                   --
├─Dropout: 1-33                          [32, 256]            [32, 256]            --                   --
├─Linear: 1-34                           [32, 256]            [32, 64]             16,448               True
├─LeakyReLU: 1-35                        [32, 64]             [32, 64]             --                   --
├─Dropout: 1-36                          [32, 64]             [32, 64]             --                   --
├─Linear: 1-37                           [32, 64]             [32, 8]              520                  True
========================================================================================================================
Total params: 4,533,480
Trainable params: 4,533,480
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 20.99
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 912.41
Params size (MB): 18.13
Estimated Total Size (MB): 936.44
========================================================================================================================

In [37]:
main_kolesa(model_cnn_2_brand, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_cnn_2_brand, 'Reg_CNN_brand')

Epoch: 1

100%|██████████| 97/97 [00:17<00:00,  5.66it/s]

Train set: Average loss: 2.0438, Accuracy: 15.21%
Val set: Average loss: 2.0703, Accuracy: 14.74%

Classification report:
               precision    recall  f1-score   support

         Audi       0.14      0.10      0.11        73
          BMW       0.13      0.29      0.18        90
    Chevrolet       0.16      0.52      0.24        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.20      0.18      0.19        77
        Lexus       0.06      0.02      0.03        95
Mercedes-Benz       0.29      0.05      0.08        81
       Toyota       0.10      0.05      0.06        85

     accuracy                           0.15       665
    macro avg       0.13      0.15      0.11       665
 weighted avg       0.13      0.15      0.11       665


Epoch: 2

100%|██████████| 97/97 [00:17<00:00,  5.50it/s]

Train set: Average loss: 2.0708, Accuracy: 17.60%
Val set: Average loss: 2.0554, Accuracy: 16.39%

Classification report:
               precision    recall  f1-score   support

         Audi       0.00      0.00      0.00        73
          BMW       0.13      0.22      0.17        90
    Chevrolet       0.18      0.43      0.25        79
      Hyundai       0.00      0.00      0.00        85
          Kia       0.29      0.16      0.20        77
        Lexus       0.16      0.22      0.19        95
Mercedes-Benz       0.16      0.04      0.06        81
       Toyota       0.15      0.22      0.18        85

     accuracy                           0.16       665
    macro avg       0.13      0.16      0.13       665
 weighted avg       0.13      0.16      0.13       665


Epoch: 3

100%|██████████| 97/97 [00:17<00:00,  5.42it/s]

Train set: Average loss: 2.0002, Accuracy: 18.66%
Val set: Average loss: 2.0356, Accuracy: 17.44%

Classification report:
               precision    recall  f1-score   support

         Audi       0.20      0.04      0.07        73
          BMW       0.14      0.28      0.19        90
    Chevrolet       0.22      0.46      0.30        79
      Hyundai       0.15      0.05      0.07        85
          Kia       0.16      0.17      0.16        77
        Lexus       0.17      0.23      0.19        95
Mercedes-Benz       0.33      0.05      0.09        81
       Toyota       0.16      0.11      0.13        85

     accuracy                           0.17       665
    macro avg       0.19      0.17      0.15       665
 weighted avg       0.19      0.17      0.15       665


Epoch: 4

100%|██████████| 97/97 [00:17<00:00,  5.64it/s]

Train set: Average loss: 2.0069, Accuracy: 20.21%
Val set: Average loss: 2.0162, Accuracy: 19.40%

Classification report:
               precision    recall  f1-score   support

         Audi       0.21      0.14      0.17        73
          BMW       0.17      0.32      0.22        90
    Chevrolet       0.21      0.57      0.31        79
      Hyundai       0.10      0.02      0.04        85
          Kia       0.18      0.16      0.17        77
        Lexus       0.22      0.16      0.18        95
Mercedes-Benz       0.26      0.14      0.18        81
       Toyota       0.15      0.06      0.08        85

     accuracy                           0.19       665
    macro avg       0.19      0.20      0.17       665
 weighted avg       0.19      0.19      0.17       665


Epoch: 5

100%|██████████| 97/97 [00:17<00:00,  5.50it/s]

Train set: Average loss: 1.9891, Accuracy: 20.14%
Val set: Average loss: 2.0069, Accuracy: 20.75%

Classification report:
               precision    recall  f1-score   support

         Audi       0.23      0.18      0.20        73
          BMW       0.16      0.21      0.18        90
    Chevrolet       0.22      0.56      0.32        79
      Hyundai       0.13      0.04      0.06        85
          Kia       0.21      0.26      0.23        77
        Lexus       0.18      0.21      0.20        95
Mercedes-Benz       0.35      0.21      0.26        81
       Toyota       0.11      0.02      0.04        85

     accuracy                           0.21       665
    macro avg       0.20      0.21      0.19       665
 weighted avg       0.20      0.21      0.18       665


Epoch: 6

100%|██████████| 97/97 [00:17<00:00,  5.62it/s]

Train set: Average loss: 1.9502, Accuracy: 22.59%
Val set: Average loss: 1.9832, Accuracy: 19.55%

Classification report:
               precision    recall  f1-score   support

         Audi       0.23      0.21      0.22        73
          BMW       0.16      0.23      0.19        90
    Chevrolet       0.21      0.59      0.31        79
      Hyundai       0.17      0.05      0.07        85
          Kia       0.21      0.19      0.20        77
        Lexus       0.23      0.18      0.20        95
Mercedes-Benz       0.29      0.10      0.15        81
       Toyota       0.07      0.04      0.05        85

     accuracy                           0.20       665
    macro avg       0.19      0.20      0.17       665
 weighted avg       0.19      0.20      0.17       665


Epoch: 7

100%|██████████| 97/97 [00:16<00:00,  5.75it/s]

Train set: Average loss: 1.8445, Accuracy: 24.23%
Val set: Average loss: 1.9596, Accuracy: 20.45%

Classification report:
               precision    recall  f1-score   support

         Audi       0.19      0.19      0.19        73
          BMW       0.21      0.29      0.24        90
    Chevrolet       0.26      0.44      0.32        79
      Hyundai       0.15      0.05      0.07        85
          Kia       0.19      0.18      0.19        77
        Lexus       0.18      0.16      0.17        95
Mercedes-Benz       0.25      0.23      0.24        81
       Toyota       0.13      0.11      0.12        85

     accuracy                           0.20       665
    macro avg       0.19      0.21      0.19       665
 weighted avg       0.19      0.20      0.19       665


Epoch: 8

100%|██████████| 97/97 [00:17<00:00,  5.60it/s]

Train set: Average loss: 1.8529, Accuracy: 24.81%
Val set: Average loss: 1.9576, Accuracy: 20.60%

Classification report:
               precision    recall  f1-score   support

         Audi       0.19      0.11      0.14        73
          BMW       0.22      0.32      0.26        90
    Chevrolet       0.28      0.47      0.35        79
      Hyundai       0.22      0.06      0.09        85
          Kia       0.28      0.13      0.18        77
        Lexus       0.16      0.17      0.16        95
Mercedes-Benz       0.23      0.19      0.20        81
       Toyota       0.13      0.20      0.16        85

     accuracy                           0.21       665
    macro avg       0.21      0.21      0.19       665
 weighted avg       0.21      0.21      0.19       665


Epoch: 9

100%|██████████| 97/97 [00:17<00:00,  5.54it/s]

Train set: Average loss: 1.7361, Accuracy: 26.62%
Val set: Average loss: 1.9684, Accuracy: 23.61%

Classification report:
               precision    recall  f1-score   support

         Audi       0.18      0.11      0.14        73
          BMW       0.23      0.53      0.33        90
    Chevrolet       0.26      0.57      0.36        79
      Hyundai       0.50      0.06      0.11        85
          Kia       0.30      0.16      0.21        77
        Lexus       0.21      0.16      0.18        95
Mercedes-Benz       0.33      0.19      0.24        81
       Toyota       0.12      0.11      0.11        85

     accuracy                           0.24       665
    macro avg       0.27      0.23      0.21       665
 weighted avg       0.27      0.24      0.21       665


Epoch: 10

100%|██████████| 97/97 [00:17<00:00,  5.70it/s]

Train set: Average loss: 1.7634, Accuracy: 25.81%
Val set: Average loss: 1.9320, Accuracy: 26.17%

Classification report:
               precision    recall  f1-score   support

         Audi       0.24      0.22      0.23        73
          BMW       0.24      0.56      0.33        90
    Chevrolet       0.31      0.51      0.39        79
      Hyundai       0.29      0.13      0.18        85
          Kia       0.23      0.23      0.23        77
        Lexus       0.26      0.18      0.21        95
Mercedes-Benz       0.39      0.21      0.27        81
       Toyota       0.16      0.06      0.09        85

     accuracy                           0.26       665
    macro avg       0.26      0.26      0.24       665
 weighted avg       0.26      0.26      0.24       665


Epoch: 11

100%|██████████| 97/97 [00:17<00:00,  5.63it/s]

Train set: Average loss: 1.7552, Accuracy: 27.52%
Val set: Average loss: 1.9589, Accuracy: 25.11%

Classification report:
               precision    recall  f1-score   support

         Audi       0.23      0.23      0.23        73
          BMW       0.30      0.22      0.26        90
    Chevrolet       0.27      0.59      0.37        79
      Hyundai       0.33      0.18      0.23        85
          Kia       0.36      0.21      0.26        77
        Lexus       0.19      0.17      0.18        95
Mercedes-Benz       0.26      0.26      0.26        81
       Toyota       0.15      0.18      0.16        85

     accuracy                           0.25       665
    macro avg       0.26      0.25      0.24       665
 weighted avg       0.26      0.25      0.24       665


Epoch: 12

100%|██████████| 97/97 [00:17<00:00,  5.62it/s]

Train set: Average loss: 1.6503, Accuracy: 30.55%
Val set: Average loss: 1.9343, Accuracy: 24.96%

Classification report:
               precision    recall  f1-score   support

         Audi       0.30      0.16      0.21        73
          BMW       0.24      0.27      0.25        90
    Chevrolet       0.37      0.43      0.40        79
      Hyundai       0.26      0.25      0.25        85
          Kia       0.31      0.26      0.28        77
        Lexus       0.22      0.24      0.23        95
Mercedes-Benz       0.20      0.27      0.23        81
       Toyota       0.14      0.12      0.13        85

     accuracy                           0.25       665
    macro avg       0.25      0.25      0.25       665
 weighted avg       0.25      0.25      0.25       665


Epoch: 13

100%|██████████| 97/97 [00:17<00:00,  5.58it/s]

Train set: Average loss: 1.6805, Accuracy: 29.49%
Val set: Average loss: 1.9231, Accuracy: 26.77%

Classification report:
               precision    recall  f1-score   support

         Audi       0.27      0.19      0.22        73
          BMW       0.29      0.27      0.28        90
    Chevrolet       0.31      0.51      0.38        79
      Hyundai       0.27      0.24      0.25        85
          Kia       0.33      0.19      0.24        77
        Lexus       0.22      0.25      0.23        95
Mercedes-Benz       0.24      0.36      0.29        81
       Toyota       0.24      0.14      0.18        85

     accuracy                           0.27       665
    macro avg       0.27      0.27      0.26       665
 weighted avg       0.27      0.27      0.26       665


Epoch: 14

100%|██████████| 97/97 [00:17<00:00,  5.57it/s]

Train set: Average loss: 1.6383, Accuracy: 31.68%
Val set: Average loss: 1.9533, Accuracy: 25.11%

Classification report:
               precision    recall  f1-score   support

         Audi       0.26      0.22      0.24        73
          BMW       0.28      0.39      0.33        90
    Chevrolet       0.28      0.57      0.38        79
      Hyundai       0.31      0.12      0.17        85
          Kia       0.35      0.23      0.28        77
        Lexus       0.20      0.13      0.16        95
Mercedes-Benz       0.21      0.15      0.18        81
       Toyota       0.16      0.22      0.19        85

     accuracy                           0.25       665
    macro avg       0.26      0.25      0.24       665
 weighted avg       0.26      0.25      0.24       665


Epoch: 15

100%|██████████| 97/97 [00:17<00:00,  5.53it/s]

Train set: Average loss: 1.7818, Accuracy: 32.68%
Val set: Average loss: 1.9088, Accuracy: 29.17%

Classification report:
               precision    recall  f1-score   support

         Audi       0.28      0.29      0.28        73
          BMW       0.31      0.41      0.35        90
    Chevrolet       0.45      0.46      0.45        79
      Hyundai       0.30      0.26      0.28        85
          Kia       0.44      0.27      0.34        77
        Lexus       0.23      0.20      0.22        95
Mercedes-Benz       0.23      0.28      0.26        81
       Toyota       0.17      0.18      0.17        85

     accuracy                           0.29       665
    macro avg       0.30      0.29      0.29       665
 weighted avg       0.30      0.29      0.29       665


Epoch: 16

100%|██████████| 97/97 [00:17<00:00,  5.63it/s]

Train set: Average loss: 1.6809, Accuracy: 32.94%
Val set: Average loss: 1.8962, Accuracy: 28.42%

Classification report:
               precision    recall  f1-score   support

         Audi       0.29      0.32      0.30        73
          BMW       0.28      0.57      0.38        90
    Chevrolet       0.49      0.34      0.40        79
      Hyundai       0.32      0.21      0.25        85
          Kia       0.31      0.23      0.26        77
        Lexus       0.22      0.19      0.20        95
Mercedes-Benz       0.24      0.31      0.27        81
       Toyota       0.18      0.11      0.13        85

     accuracy                           0.28       665
    macro avg       0.29      0.28      0.28       665
 weighted avg       0.29      0.28      0.27       665


Epoch: 17

100%|██████████| 97/97 [00:17<00:00,  5.61it/s]

Train set: Average loss: 1.6742, Accuracy: 34.13%
Val set: Average loss: 1.9052, Accuracy: 27.97%

Classification report:
               precision    recall  f1-score   support

         Audi       0.28      0.29      0.28        73
          BMW       0.29      0.54      0.38        90
    Chevrolet       0.40      0.46      0.42        79
      Hyundai       0.29      0.08      0.13        85
          Kia       0.37      0.19      0.25        77
        Lexus       0.22      0.17      0.19        95
Mercedes-Benz       0.25      0.27      0.26        81
       Toyota       0.20      0.24      0.22        85

     accuracy                           0.28       665
    macro avg       0.29      0.28      0.27       665
 weighted avg       0.28      0.28      0.26       665


Epoch: 18

100%|██████████| 97/97 [00:17<00:00,  5.52it/s]

Train set: Average loss: 1.7176, Accuracy: 36.32%
Val set: Average loss: 1.8989, Accuracy: 27.07%

Classification report:
               precision    recall  f1-score   support

         Audi       0.28      0.30      0.29        73
          BMW       0.25      0.49      0.33        90
    Chevrolet       0.39      0.46      0.42        79
      Hyundai       0.33      0.14      0.20        85
          Kia       0.25      0.25      0.25        77
        Lexus       0.25      0.25      0.25        95
Mercedes-Benz       0.24      0.14      0.17        81
       Toyota       0.18      0.14      0.16        85

     accuracy                           0.27       665
    macro avg       0.27      0.27      0.26       665
 weighted avg       0.27      0.27      0.26       665


Epoch: 19

100%|██████████| 97/97 [00:17<00:00,  5.54it/s]

Train set: Average loss: 1.5354, Accuracy: 36.16%
Val set: Average loss: 1.9195, Accuracy: 27.67%

Classification report:
               precision    recall  f1-score   support

         Audi       0.27      0.23      0.25        73
          BMW       0.29      0.53      0.38        90
    Chevrolet       0.35      0.52      0.42        79
      Hyundai       0.41      0.20      0.27        85
          Kia       0.27      0.19      0.23        77
        Lexus       0.20      0.16      0.18        95
Mercedes-Benz       0.27      0.16      0.20        81
       Toyota       0.18      0.21      0.20        85

     accuracy                           0.28       665
    macro avg       0.28      0.28      0.26       665
 weighted avg       0.28      0.28      0.26       665


Epoch: 20

100%|██████████| 97/97 [00:17<00:00,  5.48it/s]

Train set: Average loss: 1.5164, Accuracy: 36.58%
Val set: Average loss: 1.9102, Accuracy: 28.87%

Classification report:
               precision    recall  f1-score   support

         Audi       0.26      0.26      0.26        73
          BMW       0.29      0.73      0.41        90
    Chevrolet       0.47      0.47      0.47        79
      Hyundai       0.37      0.12      0.18        85
          Kia       0.28      0.19      0.23        77
        Lexus       0.22      0.15      0.18        95
Mercedes-Benz       0.28      0.20      0.23        81
       Toyota       0.19      0.18      0.18        85

     accuracy                           0.29       665
    macro avg       0.29      0.29      0.27       665
 weighted avg       0.29      0.29      0.27       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

[OK] модель сохранена: ../data/models/Reg_CNN_brand.pt

29.17% на лучшей эпохе это уже в два раза лучше чем на baseline. Это хороший буст, но пока это все же плохо.

Вернем дефолтное количество эпох

In [26]:
CFG.num_epochs = 10

Далее мы уже будем брать за основу предобученные модели и пытаться использовать FineTuning. Посмотрим далее помогло ли это нам в наших задачах.

## FineTuned AlexNet

Далее попробуем в качестве другого подхода взять уже ранее предобученную модель. Возьмем AlexNet

Из-за проблем при запуске AlexNet с MacBook используя MPS - мы вынесли эти запуски в отдельный ноутбук `alexnet.ipynb`, где делали запуски в Colab.

## ResNet18

Возьмём более современную **ResNet18**.

Ее преимущество - остаточные связи, которые позволяют обучать глубокие сети без затухания градиента.

Дообучаем так же - через наш `main_kolesa`, заменив только финальный полносвязный слой.

In [27]:
from torchvision.models import resnet18
from torchvision.models import ResNet18_Weights

#### Задача на тип кузова

In [28]:
CFG.classes = all_body_types
num_out_features = 2

model_resnet_bt = resnet18(weights=ResNet18_Weights.DEFAULT)
model_resnet_bt.fc = torch.nn.Linear(model_resnet_bt.fc.in_features, num_out_features)

In [41]:
summary(model=model_resnet_bt,
        input_size=(32, 3, 96, 160),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
ResNet                                   [32, 3, 96, 160]     [32, 2]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 64, 48, 80]     9,408                True
├─BatchNorm2d: 1-2                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─ReLU: 1-3                              [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-4                         [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-5                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    └─BasicBlock: 2-1                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-1                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-2             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-3                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-4                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-5             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-6                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    └─BasicBlock: 2-2                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-7                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-8             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-9                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-10                 [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-11            [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-12                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-6                        [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    └─BasicBlock: 2-3                   [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-13                 [32, 64, 24, 40]     [32, 128, 12, 20]    73,728               True
│    │    └─BatchNorm2d: 3-14            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-15                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-16                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-17            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─Sequential: 3-18             [32, 64, 24, 40]     [32, 128, 12, 20]    8,448                True
│    │    └─ReLU: 3-19                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    └─BasicBlock: 2-4                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-20                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-21            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-22                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-23                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-24            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-25                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Sequential: 1-7                        [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    └─BasicBlock: 2-5                   [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-26                 [32, 128, 12, 20]    [32, 256, 6, 10]     294,912              True
│    │    └─BatchNorm2d: 3-27            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-28                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-29                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-30            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─Sequential: 3-31             [32, 128, 12, 20]    [32, 256, 6, 10]     33,280               True
│    │    └─ReLU: 3-32                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    └─BasicBlock: 2-6                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-33                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-34            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-35                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-36                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-37            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-38                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Sequential: 1-8                        [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    └─BasicBlock: 2-7                   [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-39                 [32, 256, 6, 10]     [32, 512, 3, 5]      1,179,648            True
│    │    └─BatchNorm2d: 3-40            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-41                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-42                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-43            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─Sequential: 3-44             [32, 256, 6, 10]     [32, 512, 3, 5]      132,096              True
│    │    └─ReLU: 3-45                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    └─BasicBlock: 2-8                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-46                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-47            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-48                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-49                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-50            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-51                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
├─AdaptiveAvgPool2d: 1-9                 [32, 512, 3, 5]      [32, 512, 1, 1]      --                   --
├─Linear: 1-10                           [32, 512]            [32, 2]              1,026                True
========================================================================================================================
Total params: 11,177,538
Trainable params: 11,177,538
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 17.77
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 389.28
Params size (MB): 44.71
Estimated Total Size (MB): 439.89
========================================================================================================================

In [42]:
main_kolesa(model_resnet_bt, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_resnet_bt, 'ResNet18_finetune_body_type')

Epoch: 1

100%|██████████| 97/97 [00:17<00:00,  5.58it/s]

Train set: Average loss: 0.5798, Accuracy: 72.64%
Val set: Average loss: 0.3939, Accuracy: 83.91%

Classification report:
              precision    recall  f1-score   support

       sedan       0.88      0.86      0.87       418
         SUV       0.77      0.80      0.79       247

    accuracy                           0.84       665
   macro avg       0.83      0.83      0.83       665
weighted avg       0.84      0.84      0.84       665


Epoch: 2

100%|██████████| 97/97 [00:16<00:00,  5.77it/s]

Train set: Average loss: 0.5523, Accuracy: 84.05%
Val set: Average loss: 0.3788, Accuracy: 84.21%

Classification report:
              precision    recall  f1-score   support

       sedan       0.82      0.96      0.88       418
         SUV       0.91      0.64      0.75       247

    accuracy                           0.84       665
   macro avg       0.86      0.80      0.82       665
weighted avg       0.85      0.84      0.83       665


Epoch: 3

100%|██████████| 97/97 [00:16<00:00,  5.82it/s]

Train set: Average loss: 0.3631, Accuracy: 89.30%
Val set: Average loss: 0.4002, Accuracy: 82.26%

Classification report:
              precision    recall  f1-score   support

       sedan       0.79      0.97      0.87       418
         SUV       0.93      0.57      0.70       247

    accuracy                           0.82       665
   macro avg       0.86      0.77      0.79       665
weighted avg       0.84      0.82      0.81       665


Epoch: 4

100%|██████████| 97/97 [00:16<00:00,  5.78it/s]

Train set: Average loss: 0.1659, Accuracy: 91.20%
Val set: Average loss: 0.3748, Accuracy: 86.32%

Classification report:
              precision    recall  f1-score   support

       sedan       0.86      0.94      0.90       418
         SUV       0.88      0.74      0.80       247

    accuracy                           0.86       665
   macro avg       0.87      0.84      0.85       665
weighted avg       0.86      0.86      0.86       665


Epoch: 5

100%|██████████| 97/97 [00:16<00:00,  5.86it/s]

Train set: Average loss: 0.3589, Accuracy: 93.20%
Val set: Average loss: 0.4446, Accuracy: 81.20%

Classification report:
              precision    recall  f1-score   support

       sedan       0.91      0.78      0.84       418
         SUV       0.70      0.87      0.78       247

    accuracy                           0.81       665
   macro avg       0.80      0.82      0.81       665
weighted avg       0.83      0.81      0.82       665


Epoch: 6

100%|██████████| 97/97 [00:16<00:00,  5.83it/s]

Train set: Average loss: 0.1803, Accuracy: 94.62%
Val set: Average loss: 0.3794, Accuracy: 86.02%

Classification report:
              precision    recall  f1-score   support

       sedan       0.88      0.90      0.89       418
         SUV       0.82      0.80      0.81       247

    accuracy                           0.86       665
   macro avg       0.85      0.85      0.85       665
weighted avg       0.86      0.86      0.86       665


Epoch: 7

100%|██████████| 97/97 [00:16<00:00,  5.81it/s]

Train set: Average loss: 0.2225, Accuracy: 94.68%
Val set: Average loss: 0.3620, Accuracy: 84.66%

Classification report:
              precision    recall  f1-score   support

       sedan       0.91      0.83      0.87       418
         SUV       0.76      0.87      0.81       247

    accuracy                           0.85       665
   macro avg       0.83      0.85      0.84       665
weighted avg       0.86      0.85      0.85       665


Epoch: 8

100%|██████████| 97/97 [00:16<00:00,  5.84it/s]

Train set: Average loss: 0.0546, Accuracy: 96.20%
Val set: Average loss: 0.2162, Accuracy: 88.57%

Classification report:
              precision    recall  f1-score   support

       sedan       0.88      0.95      0.91       418
         SUV       0.91      0.77      0.83       247

    accuracy                           0.89       665
   macro avg       0.89      0.86      0.87       665
weighted avg       0.89      0.89      0.88       665


Epoch: 9

100%|██████████| 97/97 [00:16<00:00,  5.85it/s]

Train set: Average loss: 0.1257, Accuracy: 96.04%
Val set: Average loss: 0.3548, Accuracy: 82.26%

Classification report:
              precision    recall  f1-score   support

       sedan       0.94      0.77      0.84       418
         SUV       0.70      0.91      0.79       247

    accuracy                           0.82       665
   macro avg       0.82      0.84      0.82       665
weighted avg       0.85      0.82      0.83       665


Epoch: 10

100%|██████████| 97/97 [00:16<00:00,  5.83it/s]

Train set: Average loss: 0.0986, Accuracy: 96.71%
Val set: Average loss: 0.2851, Accuracy: 87.52%

Classification report:
              precision    recall  f1-score   support

       sedan       0.89      0.91      0.90       418
         SUV       0.84      0.82      0.83       247

    accuracy                           0.88       665
   macro avg       0.87      0.86      0.87       665
weighted avg       0.87      0.88      0.87       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

[OK] модель сохранена: ../data/models/ResNet18_finetune_body_type.pt

88.57% accuracy на лучшей эпохе - отличный результат, относительно того, что мы видели. При этом precision для SUV даже выше, хотя recall похуже. То есть модель хорошо попадает в SUV, но меньше их распознает в датасете.

#### Задача на определение марки

In [29]:
CFG.classes = all_brands
num_out_features = 8

model_resnet_brand = resnet18(weights=ResNet18_Weights.DEFAULT)
model_resnet_brand.fc = torch.nn.Linear(model_resnet_brand.fc.in_features, num_out_features)

In [44]:
summary(model=model_resnet_brand,
        input_size=(32, 3, 96, 160),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
ResNet                                   [32, 3, 96, 160]     [32, 8]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 64, 48, 80]     9,408                True
├─BatchNorm2d: 1-2                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─ReLU: 1-3                              [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-4                         [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-5                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    └─BasicBlock: 2-1                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-1                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-2             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-3                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-4                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-5             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-6                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    └─BasicBlock: 2-2                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-7                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-8             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-9                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-10                 [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-11            [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-12                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-6                        [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    └─BasicBlock: 2-3                   [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-13                 [32, 64, 24, 40]     [32, 128, 12, 20]    73,728               True
│    │    └─BatchNorm2d: 3-14            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-15                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-16                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-17            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─Sequential: 3-18             [32, 64, 24, 40]     [32, 128, 12, 20]    8,448                True
│    │    └─ReLU: 3-19                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    └─BasicBlock: 2-4                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-20                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-21            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-22                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-23                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-24            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-25                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Sequential: 1-7                        [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    └─BasicBlock: 2-5                   [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-26                 [32, 128, 12, 20]    [32, 256, 6, 10]     294,912              True
│    │    └─BatchNorm2d: 3-27            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-28                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-29                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-30            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─Sequential: 3-31             [32, 128, 12, 20]    [32, 256, 6, 10]     33,280               True
│    │    └─ReLU: 3-32                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    └─BasicBlock: 2-6                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-33                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-34            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-35                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-36                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-37            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-38                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Sequential: 1-8                        [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    └─BasicBlock: 2-7                   [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-39                 [32, 256, 6, 10]     [32, 512, 3, 5]      1,179,648            True
│    │    └─BatchNorm2d: 3-40            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-41                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-42                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-43            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─Sequential: 3-44             [32, 256, 6, 10]     [32, 512, 3, 5]      132,096              True
│    │    └─ReLU: 3-45                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    └─BasicBlock: 2-8                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-46                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-47            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-48                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-49                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-50            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-51                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
├─AdaptiveAvgPool2d: 1-9                 [32, 512, 3, 5]      [32, 512, 1, 1]      --                   --
├─Linear: 1-10                           [32, 512]            [32, 8]              4,104                True
========================================================================================================================
Total params: 11,180,616
Trainable params: 11,180,616
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 17.77
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 389.29
Params size (MB): 44.72
Estimated Total Size (MB): 439.91
========================================================================================================================

In [45]:
main_kolesa(model_resnet_brand, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_resnet_brand, 'ResNet18_finetune_brand')

Epoch: 1

100%|██████████| 97/97 [00:17<00:00,  5.61it/s]

Train set: Average loss: 1.6750, Accuracy: 26.17%
Val set: Average loss: 1.5889, Accuracy: 38.95%

Classification report:
               precision    recall  f1-score   support

         Audi       0.87      0.36      0.50        73
          BMW       0.81      0.51      0.63        90
    Chevrolet       0.59      0.43      0.50        79
      Hyundai       0.37      0.22      0.28        85
          Kia       0.29      0.42      0.34        77
        Lexus       0.27      0.54      0.36        95
Mercedes-Benz       0.31      0.58      0.40        81
       Toyota       0.25      0.05      0.08        85

     accuracy                           0.39       665
    macro avg       0.47      0.39      0.39       665
 weighted avg       0.46      0.39      0.38       665


Epoch: 2

100%|██████████| 97/97 [00:16<00:00,  5.74it/s]

Train set: Average loss: 1.0810, Accuracy: 50.15%
Val set: Average loss: 1.5561, Accuracy: 49.62%

Classification report:
               precision    recall  f1-score   support

         Audi       0.58      0.58      0.58        73
          BMW       0.72      0.76      0.74        90
    Chevrolet       0.58      0.57      0.57        79
      Hyundai       0.39      0.38      0.38        85
          Kia       0.36      0.66      0.47        77
        Lexus       0.54      0.43      0.48        95
Mercedes-Benz       0.50      0.36      0.42        81
       Toyota       0.36      0.26      0.30        85

     accuracy                           0.50       665
    macro avg       0.50      0.50      0.49       665
 weighted avg       0.50      0.50      0.49       665


Epoch: 3

100%|██████████| 97/97 [00:16<00:00,  5.84it/s]

Train set: Average loss: 0.6397, Accuracy: 62.52%
Val set: Average loss: 1.4432, Accuracy: 52.48%

Classification report:
               precision    recall  f1-score   support

         Audi       0.48      0.67      0.56        73
          BMW       0.71      0.69      0.70        90
    Chevrolet       0.70      0.59      0.64        79
      Hyundai       0.47      0.41      0.44        85
          Kia       0.42      0.69      0.52        77
        Lexus       0.47      0.47      0.47        95
Mercedes-Benz       0.54      0.36      0.43        81
       Toyota       0.48      0.34      0.40        85

     accuracy                           0.52       665
    macro avg       0.54      0.53      0.52       665
 weighted avg       0.54      0.52      0.52       665


Epoch: 4

100%|██████████| 97/97 [00:16<00:00,  5.84it/s]

Train set: Average loss: 0.8420, Accuracy: 72.19%
Val set: Average loss: 1.7249, Accuracy: 50.83%

Classification report:
               precision    recall  f1-score   support

         Audi       0.70      0.60      0.65        73
          BMW       0.76      0.70      0.73        90
    Chevrolet       0.48      0.66      0.56        79
      Hyundai       0.56      0.45      0.50        85
          Kia       0.43      0.56      0.48        77
        Lexus       0.57      0.41      0.48        95
Mercedes-Benz       0.53      0.26      0.35        81
       Toyota       0.29      0.45      0.35        85

     accuracy                           0.51       665
    macro avg       0.54      0.51      0.51       665
 weighted avg       0.54      0.51      0.51       665


Epoch: 5

100%|██████████| 97/97 [00:16<00:00,  5.84it/s]

Train set: Average loss: 0.4227, Accuracy: 79.60%
Val set: Average loss: 1.6344, Accuracy: 56.09%

Classification report:
               precision    recall  f1-score   support

         Audi       0.52      0.64      0.58        73
          BMW       0.70      0.77      0.73        90
    Chevrolet       0.71      0.62      0.66        79
      Hyundai       0.50      0.42      0.46        85
          Kia       0.45      0.75      0.56        77
        Lexus       0.63      0.47      0.54        95
Mercedes-Benz       0.55      0.57      0.56        81
       Toyota       0.45      0.27      0.34        85

     accuracy                           0.56       665
    macro avg       0.56      0.56      0.55       665
 weighted avg       0.57      0.56      0.55       665


Epoch: 6

100%|██████████| 97/97 [00:16<00:00,  5.73it/s]

Train set: Average loss: 0.3318, Accuracy: 82.98%
Val set: Average loss: 1.8211, Accuracy: 55.34%

Classification report:
               precision    recall  f1-score   support

         Audi       0.55      0.63      0.59        73
          BMW       0.77      0.57      0.65        90
    Chevrolet       0.54      0.85      0.66        79
      Hyundai       0.49      0.54      0.51        85
          Kia       0.43      0.45      0.44        77
        Lexus       0.63      0.44      0.52        95
Mercedes-Benz       0.64      0.47      0.54        81
       Toyota       0.48      0.51      0.49        85

     accuracy                           0.55       665
    macro avg       0.57      0.56      0.55       665
 weighted avg       0.57      0.55      0.55       665


Epoch: 7

100%|██████████| 97/97 [00:17<00:00,  5.61it/s]

Train set: Average loss: 0.2173, Accuracy: 86.56%
Val set: Average loss: 1.8317, Accuracy: 53.08%

Classification report:
               precision    recall  f1-score   support

         Audi       0.57      0.66      0.61        73
          BMW       0.80      0.68      0.73        90
    Chevrolet       0.69      0.68      0.69        79
      Hyundai       0.39      0.53      0.45        85
          Kia       0.47      0.47      0.47        77
        Lexus       0.45      0.57      0.50        95
Mercedes-Benz       0.66      0.28      0.40        81
       Toyota       0.41      0.38      0.39        85

     accuracy                           0.53       665
    macro avg       0.55      0.53      0.53       665
 weighted avg       0.55      0.53      0.53       665


Epoch: 8

100%|██████████| 97/97 [00:16<00:00,  5.80it/s]

Train set: Average loss: 0.2073, Accuracy: 88.20%
Val set: Average loss: 2.0680, Accuracy: 54.29%

Classification report:
               precision    recall  f1-score   support

         Audi       0.63      0.55      0.59        73
          BMW       0.69      0.73      0.71        90
    Chevrolet       0.60      0.73      0.66        79
      Hyundai       0.46      0.49      0.48        85
          Kia       0.56      0.49      0.52        77
        Lexus       0.53      0.47      0.50        95
Mercedes-Benz       0.57      0.40      0.47        81
       Toyota       0.37      0.47      0.41        85

     accuracy                           0.54       665
    macro avg       0.55      0.54      0.54       665
 weighted avg       0.55      0.54      0.54       665


Epoch: 9

100%|██████████| 97/97 [00:17<00:00,  5.68it/s]

Train set: Average loss: 0.5183, Accuracy: 89.69%
Val set: Average loss: 1.9780, Accuracy: 57.14%

Classification report:
               precision    recall  f1-score   support

         Audi       0.71      0.56      0.63        73
          BMW       0.68      0.80      0.73        90
    Chevrolet       0.56      0.85      0.68        79
      Hyundai       0.48      0.48      0.48        85
          Kia       0.62      0.44      0.52        77
        Lexus       0.59      0.54      0.56        95
Mercedes-Benz       0.73      0.47      0.57        81
       Toyota       0.35      0.42      0.38        85

     accuracy                           0.57       665
    macro avg       0.59      0.57      0.57       665
 weighted avg       0.59      0.57      0.57       665


Epoch: 10

100%|██████████| 97/97 [00:18<00:00,  5.39it/s]

Train set: Average loss: 0.1054, Accuracy: 91.65%
Val set: Average loss: 2.0116, Accuracy: 60.90%

Classification report:
               precision    recall  f1-score   support

         Audi       0.76      0.56      0.65        73
          BMW       0.84      0.73      0.78        90
    Chevrolet       0.61      0.87      0.72        79
      Hyundai       0.44      0.65      0.52        85
          Kia       0.67      0.42      0.51        77
        Lexus       0.64      0.60      0.62        95
Mercedes-Benz       0.53      0.67      0.59        81
       Toyota       0.56      0.36      0.44        85

     accuracy                           0.61       665
    macro avg       0.63      0.61      0.60       665
 weighted avg       0.63      0.61      0.61       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

[OK] модель сохранена: ../data/models/ResNet18_finetune_brand.pt

60.90% accuracy на лучше эпохе пока лучшее, что видели. С какими-то марками, при этом, все сильно лучше, к примеру, у BMW. А вот явно хуже получается с Toyot'ой. При этом модель сильно переобучилась, а до этого модели даже на train работали плохо.

### ResNet с регуляризацией

Попробуем побороться с переобучением, за счет изменения основной main функции, добавления dropout в сам ResNet + обновим часть конфига. И попробуем взять больще эпохж

In [30]:
def main_kolesa_new(model, train_df, val_df):

    if CFG.wandb:
        wandb.init(project=CFG.project, entity=CFG.entity, reinit=True, config=class2dict(CFG))
        # логируем архитектуру модели
        # https://docs.wandb.ai/guides/track/config
        wandb.config.update({'model': str(model)})

    seed_everything(CFG.seed)

    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')

    kwargs = {'num_workers': CFG.num_workers, 'pin_memory': torch.cuda.is_available()}

    # Попробуем картинки побольше
    # будем использовать различные методы аугментации https://docs.pytorch.org/vision/0.13/transforms.html
    train_transform = transforms.Compose([
        transforms.Resize((320, 512)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.1),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    test_transform = transforms.Compose([
        transforms.Resize((320, 512)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])

    train_ds = KolesaDataset(train_df, transform=train_transform)
    val_ds = KolesaDataset(val_df, transform=test_transform)
    # test_ds = KolesaDataset(test_df, transform=test_transform)

    train_loader = torch.utils.data.DataLoader(train_ds, batch_size=CFG.train_batch_size, **kwargs)
    val_loader = torch.utils.data.DataLoader(val_ds, batch_size=CFG.test_batch_size, **kwargs)
    # test_loader = torch.utils.data.DataLoader(test_ds, batch_size=CFG.test_batch_size, **kwargs)

    model = model.to(device)

    if CFG.wandb:
        wandb.watch(model, log='all')

    # https://habr.com/ru/articles/988198/
    # добавим l2 регуляризацию (weight_decay)
    optimizer = optim.Adam(model.parameters(),
                          lr=CFG.lr, weight_decay=3e-4)

    # добавим небольшой коэф. сглаживания, что может помочь с переобучением
    criterion = nn.CrossEntropyLoss(label_smoothing=0.05)

    for epoch in range(1, CFG.num_epochs + 1):
        print('\nEpoch:', epoch)
        train(model, device, train_loader, optimizer, criterion, epoch, CFG.wandb)
        val(model, device, val_loader, criterion, CFG.wandb)

    print('Training is ended!')

Изменим learning rate и возьмем побольше эпох

In [31]:
CFG.num_epochs = 15
CFG.lr = 3e-5

### Задача на тип кузова

In [32]:
CFG.classes = all_body_types
num_out_features = 2
CFG.test_batch_size = 64 # иначе не хватает памяти с дефолтным 512

# https://discuss.pytorch.org/t/resnet-last-layer-modification/33530
model_resnet_bt_reg = resnet18(weights=ResNet18_Weights.DEFAULT)
model_resnet_bt_reg.fc = nn.Sequential(
    nn.Dropout(0.4),
    nn.Linear(model_resnet_bt_reg.fc.in_features, num_out_features)
)

In [49]:
summary(model=model_resnet_bt_reg,
        input_size=(32, 3, 320, 512),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
ResNet                                   [32, 3, 320, 512]    [32, 2]              --                   True
├─Conv2d: 1-1                            [32, 3, 320, 512]    [32, 64, 160, 256]   9,408                True
├─BatchNorm2d: 1-2                       [32, 64, 160, 256]   [32, 64, 160, 256]   128                  True
├─ReLU: 1-3                              [32, 64, 160, 256]   [32, 64, 160, 256]   --                   --
├─MaxPool2d: 1-4                         [32, 64, 160, 256]   [32, 64, 80, 128]    --                   --
├─Sequential: 1-5                        [32, 64, 80, 128]    [32, 64, 80, 128]    --                   True
│    └─BasicBlock: 2-1                   [32, 64, 80, 128]    [32, 64, 80, 128]    --                   True
│    │    └─Conv2d: 3-1                  [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-2             [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-3                    [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
│    │    └─Conv2d: 3-4                  [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-5             [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-6                    [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
│    └─BasicBlock: 2-2                   [32, 64, 80, 128]    [32, 64, 80, 128]    --                   True
│    │    └─Conv2d: 3-7                  [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-8             [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-9                    [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
│    │    └─Conv2d: 3-10                 [32, 64, 80, 128]    [32, 64, 80, 128]    36,864               True
│    │    └─BatchNorm2d: 3-11            [32, 64, 80, 128]    [32, 64, 80, 128]    128                  True
│    │    └─ReLU: 3-12                   [32, 64, 80, 128]    [32, 64, 80, 128]    --                   --
├─Sequential: 1-6                        [32, 64, 80, 128]    [32, 128, 40, 64]    --                   True
│    └─BasicBlock: 2-3                   [32, 64, 80, 128]    [32, 128, 40, 64]    --                   True
│    │    └─Conv2d: 3-13                 [32, 64, 80, 128]    [32, 128, 40, 64]    73,728               True
│    │    └─BatchNorm2d: 3-14            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─ReLU: 3-15                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
│    │    └─Conv2d: 3-16                 [32, 128, 40, 64]    [32, 128, 40, 64]    147,456              True
│    │    └─BatchNorm2d: 3-17            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─Sequential: 3-18             [32, 64, 80, 128]    [32, 128, 40, 64]    8,448                True
│    │    └─ReLU: 3-19                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
│    └─BasicBlock: 2-4                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   True
│    │    └─Conv2d: 3-20                 [32, 128, 40, 64]    [32, 128, 40, 64]    147,456              True
│    │    └─BatchNorm2d: 3-21            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─ReLU: 3-22                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
│    │    └─Conv2d: 3-23                 [32, 128, 40, 64]    [32, 128, 40, 64]    147,456              True
│    │    └─BatchNorm2d: 3-24            [32, 128, 40, 64]    [32, 128, 40, 64]    256                  True
│    │    └─ReLU: 3-25                   [32, 128, 40, 64]    [32, 128, 40, 64]    --                   --
├─Sequential: 1-7                        [32, 128, 40, 64]    [32, 256, 20, 32]    --                   True
│    └─BasicBlock: 2-5                   [32, 128, 40, 64]    [32, 256, 20, 32]    --                   True
│    │    └─Conv2d: 3-26                 [32, 128, 40, 64]    [32, 256, 20, 32]    294,912              True
│    │    └─BatchNorm2d: 3-27            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─ReLU: 3-28                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
│    │    └─Conv2d: 3-29                 [32, 256, 20, 32]    [32, 256, 20, 32]    589,824              True
│    │    └─BatchNorm2d: 3-30            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─Sequential: 3-31             [32, 128, 40, 64]    [32, 256, 20, 32]    33,280               True
│    │    └─ReLU: 3-32                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
│    └─BasicBlock: 2-6                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   True
│    │    └─Conv2d: 3-33                 [32, 256, 20, 32]    [32, 256, 20, 32]    589,824              True
│    │    └─BatchNorm2d: 3-34            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─ReLU: 3-35                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
│    │    └─Conv2d: 3-36                 [32, 256, 20, 32]    [32, 256, 20, 32]    589,824              True
│    │    └─BatchNorm2d: 3-37            [32, 256, 20, 32]    [32, 256, 20, 32]    512                  True
│    │    └─ReLU: 3-38                   [32, 256, 20, 32]    [32, 256, 20, 32]    --                   --
├─Sequential: 1-8                        [32, 256, 20, 32]    [32, 512, 10, 16]    --                   True
│    └─BasicBlock: 2-7                   [32, 256, 20, 32]    [32, 512, 10, 16]    --                   True
│    │    └─Conv2d: 3-39                 [32, 256, 20, 32]    [32, 512, 10, 16]    1,179,648            True
│    │    └─BatchNorm2d: 3-40            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─ReLU: 3-41                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
│    │    └─Conv2d: 3-42                 [32, 512, 10, 16]    [32, 512, 10, 16]    2,359,296            True
│    │    └─BatchNorm2d: 3-43            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─Sequential: 3-44             [32, 256, 20, 32]    [32, 512, 10, 16]    132,096              True
│    │    └─ReLU: 3-45                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
│    └─BasicBlock: 2-8                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   True
│    │    └─Conv2d: 3-46                 [32, 512, 10, 16]    [32, 512, 10, 16]    2,359,296            True
│    │    └─BatchNorm2d: 3-47            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─ReLU: 3-48                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
│    │    └─Conv2d: 3-49                 [32, 512, 10, 16]    [32, 512, 10, 16]    2,359,296            True
│    │    └─BatchNorm2d: 3-50            [32, 512, 10, 16]    [32, 512, 10, 16]    1,024                True
│    │    └─ReLU: 3-51                   [32, 512, 10, 16]    [32, 512, 10, 16]    --                   --
├─AdaptiveAvgPool2d: 1-9                 [32, 512, 10, 16]    [32, 512, 1, 1]      --                   --
├─Sequential: 1-10                       [32, 512]            [32, 2]              --                   True
│    └─Dropout: 2-9                      [32, 512]            [32, 512]            --                   --
│    └─Linear: 2-10                      [32, 512]            [32, 2]              1,026                True
========================================================================================================================
Total params: 11,177,538
Trainable params: 11,177,538
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 189.50
========================================================================================================================
Input size (MB): 62.91
Forward/backward pass size (MB): 4152.36
Params size (MB): 44.71
Estimated Total Size (MB): 4259.99
========================================================================================================================

In [50]:
main_kolesa_new(model_resnet_bt_reg, train_df=train_df_bt, val_df=val_df_bt)
save_model_artifact(model_resnet_bt_reg, 'ResNet18_reg_finetune_bt')

Epoch: 1

100%|██████████| 97/97 [01:07<00:00,  1.44it/s]

Train set: Average loss: 0.5697, Accuracy: 71.12%
Val set: Average loss: 0.3458, Accuracy: 85.56%

Classification report:
              precision    recall  f1-score   support

       sedan       0.85      0.94      0.89       418
         SUV       0.87      0.72      0.79       247

    accuracy                           0.86       665
   macro avg       0.86      0.83      0.84       665
weighted avg       0.86      0.86      0.85       665


Epoch: 2

100%|██████████| 97/97 [01:04<00:00,  1.50it/s]

Train set: Average loss: 0.5450, Accuracy: 86.98%
Val set: Average loss: 0.2402, Accuracy: 88.27%

Classification report:
              precision    recall  f1-score   support

       sedan       0.88      0.94      0.91       418
         SUV       0.89      0.78      0.83       247

    accuracy                           0.88       665
   macro avg       0.88      0.86      0.87       665
weighted avg       0.88      0.88      0.88       665


Epoch: 3

100%|██████████| 97/97 [01:04<00:00,  1.51it/s]

Train set: Average loss: 0.3725, Accuracy: 91.91%
Val set: Average loss: 0.2494, Accuracy: 89.47%

Classification report:
              precision    recall  f1-score   support

       sedan       0.88      0.97      0.92       418
         SUV       0.93      0.77      0.85       247

    accuracy                           0.89       665
   macro avg       0.90      0.87      0.88       665
weighted avg       0.90      0.89      0.89       665


Epoch: 4

100%|██████████| 97/97 [01:02<00:00,  1.56it/s]

Train set: Average loss: 0.3295, Accuracy: 95.46%
Val set: Average loss: 0.2161, Accuracy: 91.73%

Classification report:
              precision    recall  f1-score   support

       sedan       0.92      0.95      0.94       418
         SUV       0.91      0.86      0.89       247

    accuracy                           0.92       665
   macro avg       0.92      0.91      0.91       665
weighted avg       0.92      0.92      0.92       665


Epoch: 5

100%|██████████| 97/97 [01:01<00:00,  1.57it/s]

Train set: Average loss: 0.2714, Accuracy: 96.71%
Val set: Average loss: 0.2172, Accuracy: 91.28%

Classification report:
              precision    recall  f1-score   support

       sedan       0.91      0.95      0.93       418
         SUV       0.92      0.84      0.88       247

    accuracy                           0.91       665
   macro avg       0.91      0.90      0.90       665
weighted avg       0.91      0.91      0.91       665


Epoch: 6

100%|██████████| 97/97 [01:01<00:00,  1.57it/s]

Train set: Average loss: 0.2176, Accuracy: 98.16%
Val set: Average loss: 0.1994, Accuracy: 92.48%

Classification report:
              precision    recall  f1-score   support

       sedan       0.94      0.94      0.94       418
         SUV       0.91      0.89      0.90       247

    accuracy                           0.92       665
   macro avg       0.92      0.92      0.92       665
weighted avg       0.92      0.92      0.92       665


Epoch: 7

100%|██████████| 97/97 [01:01<00:00,  1.58it/s]

Train set: Average loss: 0.2533, Accuracy: 98.71%
Val set: Average loss: 0.2217, Accuracy: 93.08%

Classification report:
              precision    recall  f1-score   support

       sedan       0.93      0.96      0.95       418
         SUV       0.94      0.87      0.90       247

    accuracy                           0.93       665
   macro avg       0.93      0.92      0.92       665
weighted avg       0.93      0.93      0.93       665


Epoch: 8

100%|██████████| 97/97 [01:01<00:00,  1.58it/s]

Train set: Average loss: 0.2100, Accuracy: 99.13%
Val set: Average loss: 0.2003, Accuracy: 93.23%

Classification report:
              precision    recall  f1-score   support

       sedan       0.93      0.97      0.95       418
         SUV       0.94      0.87      0.91       247

    accuracy                           0.93       665
   macro avg       0.93      0.92      0.93       665
weighted avg       0.93      0.93      0.93       665


Epoch: 9

100%|██████████| 97/97 [01:01<00:00,  1.58it/s]

Train set: Average loss: 0.2090, Accuracy: 99.26%
Val set: Average loss: 0.2044, Accuracy: 93.08%

Classification report:
              precision    recall  f1-score   support

       sedan       0.93      0.96      0.95       418
         SUV       0.93      0.88      0.90       247

    accuracy                           0.93       665
   macro avg       0.93      0.92      0.93       665
weighted avg       0.93      0.93      0.93       665


Epoch: 10

100%|██████████| 97/97 [01:04<00:00,  1.51it/s]

Train set: Average loss: 0.1925, Accuracy: 99.39%
Val set: Average loss: 0.2201, Accuracy: 93.83%

Classification report:
              precision    recall  f1-score   support

       sedan       0.93      0.97      0.95       418
         SUV       0.95      0.88      0.91       247

    accuracy                           0.94       665
   macro avg       0.94      0.93      0.93       665
weighted avg       0.94      0.94      0.94       665


Epoch: 11

100%|██████████| 97/97 [01:06<00:00,  1.47it/s]

Train set: Average loss: 0.1670, Accuracy: 99.71%
Val set: Average loss: 0.2116, Accuracy: 93.98%

Classification report:
              precision    recall  f1-score   support

       sedan       0.95      0.95      0.95       418
         SUV       0.92      0.92      0.92       247

    accuracy                           0.94       665
   macro avg       0.94      0.94      0.94       665
weighted avg       0.94      0.94      0.94       665


Epoch: 12

100%|██████████| 97/97 [01:05<00:00,  1.47it/s]

Train set: Average loss: 0.1927, Accuracy: 99.65%
Val set: Average loss: 0.2546, Accuracy: 92.78%

Classification report:
              precision    recall  f1-score   support

       sedan       0.91      0.98      0.94       418
         SUV       0.96      0.84      0.90       247

    accuracy                           0.93       665
   macro avg       0.94      0.91      0.92       665
weighted avg       0.93      0.93      0.93       665


Epoch: 13

100%|██████████| 97/97 [01:03<00:00,  1.52it/s]

Train set: Average loss: 0.1737, Accuracy: 99.81%
Val set: Average loss: 0.2107, Accuracy: 94.29%

Classification report:
              precision    recall  f1-score   support

       sedan       0.94      0.97      0.96       418
         SUV       0.95      0.89      0.92       247

    accuracy                           0.94       665
   macro avg       0.95      0.93      0.94       665
weighted avg       0.94      0.94      0.94       665


Epoch: 14

100%|██████████| 97/97 [01:04<00:00,  1.51it/s]

Train set: Average loss: 0.1708, Accuracy: 99.94%
Val set: Average loss: 0.2212, Accuracy: 94.29%

Classification report:
              precision    recall  f1-score   support

       sedan       0.93      0.98      0.96       418
         SUV       0.97      0.87      0.92       247

    accuracy                           0.94       665
   macro avg       0.95      0.93      0.94       665
weighted avg       0.94      0.94      0.94       665


Epoch: 15

100%|██████████| 97/97 [01:02<00:00,  1.54it/s]

Train set: Average loss: 0.1580, Accuracy: 99.94%
Val set: Average loss: 0.2077, Accuracy: 93.68%

Classification report:
              precision    recall  f1-score   support

       sedan       0.93      0.98      0.95       418
         SUV       0.96      0.87      0.91       247

    accuracy                           0.94       665
   macro avg       0.94      0.92      0.93       665
weighted avg       0.94      0.94      0.94       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

[OK] модель сохранена: ../data/models/ResNet18_reg_finetune_bt.pt

94.29% - очень хороший результат. Все также у седанов выше recall, а у SUV precision.

### Задача на марки

In [33]:
CFG.classes = all_brands
num_out_features = 8
# https://discuss.pytorch.org/t/resnet-last-layer-modification/33530
model_resnet_brand_reg = resnet18(weights=ResNet18_Weights.DEFAULT)
model_resnet_brand_reg.fc = nn.Sequential(
    nn.Dropout(0.4),
    nn.Linear(model_resnet_brand.fc.in_features, num_out_features)
)

In [52]:
summary(model=model_resnet_brand_reg,
        input_size=(32, 3, 96, 160),
        col_names=["input_size", "output_size", "num_params", "trainable"],
        col_width=20
)

========================================================================================================================
Layer (type:depth-idx)                   Input Shape          Output Shape         Param #              Trainable
========================================================================================================================
ResNet                                   [32, 3, 96, 160]     [32, 8]              --                   True
├─Conv2d: 1-1                            [32, 3, 96, 160]     [32, 64, 48, 80]     9,408                True
├─BatchNorm2d: 1-2                       [32, 64, 48, 80]     [32, 64, 48, 80]     128                  True
├─ReLU: 1-3                              [32, 64, 48, 80]     [32, 64, 48, 80]     --                   --
├─MaxPool2d: 1-4                         [32, 64, 48, 80]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-5                        [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    └─BasicBlock: 2-1                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-1                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-2             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-3                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-4                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-5             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-6                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    └─BasicBlock: 2-2                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   True
│    │    └─Conv2d: 3-7                  [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-8             [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-9                    [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
│    │    └─Conv2d: 3-10                 [32, 64, 24, 40]     [32, 64, 24, 40]     36,864               True
│    │    └─BatchNorm2d: 3-11            [32, 64, 24, 40]     [32, 64, 24, 40]     128                  True
│    │    └─ReLU: 3-12                   [32, 64, 24, 40]     [32, 64, 24, 40]     --                   --
├─Sequential: 1-6                        [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    └─BasicBlock: 2-3                   [32, 64, 24, 40]     [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-13                 [32, 64, 24, 40]     [32, 128, 12, 20]    73,728               True
│    │    └─BatchNorm2d: 3-14            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-15                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-16                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-17            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─Sequential: 3-18             [32, 64, 24, 40]     [32, 128, 12, 20]    8,448                True
│    │    └─ReLU: 3-19                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    └─BasicBlock: 2-4                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   True
│    │    └─Conv2d: 3-20                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-21            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-22                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
│    │    └─Conv2d: 3-23                 [32, 128, 12, 20]    [32, 128, 12, 20]    147,456              True
│    │    └─BatchNorm2d: 3-24            [32, 128, 12, 20]    [32, 128, 12, 20]    256                  True
│    │    └─ReLU: 3-25                   [32, 128, 12, 20]    [32, 128, 12, 20]    --                   --
├─Sequential: 1-7                        [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    └─BasicBlock: 2-5                   [32, 128, 12, 20]    [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-26                 [32, 128, 12, 20]    [32, 256, 6, 10]     294,912              True
│    │    └─BatchNorm2d: 3-27            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-28                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-29                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-30            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─Sequential: 3-31             [32, 128, 12, 20]    [32, 256, 6, 10]     33,280               True
│    │    └─ReLU: 3-32                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    └─BasicBlock: 2-6                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   True
│    │    └─Conv2d: 3-33                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-34            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-35                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
│    │    └─Conv2d: 3-36                 [32, 256, 6, 10]     [32, 256, 6, 10]     589,824              True
│    │    └─BatchNorm2d: 3-37            [32, 256, 6, 10]     [32, 256, 6, 10]     512                  True
│    │    └─ReLU: 3-38                   [32, 256, 6, 10]     [32, 256, 6, 10]     --                   --
├─Sequential: 1-8                        [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    └─BasicBlock: 2-7                   [32, 256, 6, 10]     [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-39                 [32, 256, 6, 10]     [32, 512, 3, 5]      1,179,648            True
│    │    └─BatchNorm2d: 3-40            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-41                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-42                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-43            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─Sequential: 3-44             [32, 256, 6, 10]     [32, 512, 3, 5]      132,096              True
│    │    └─ReLU: 3-45                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    └─BasicBlock: 2-8                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   True
│    │    └─Conv2d: 3-46                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-47            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-48                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
│    │    └─Conv2d: 3-49                 [32, 512, 3, 5]      [32, 512, 3, 5]      2,359,296            True
│    │    └─BatchNorm2d: 3-50            [32, 512, 3, 5]      [32, 512, 3, 5]      1,024                True
│    │    └─ReLU: 3-51                   [32, 512, 3, 5]      [32, 512, 3, 5]      --                   --
├─AdaptiveAvgPool2d: 1-9                 [32, 512, 3, 5]      [32, 512, 1, 1]      --                   --
├─Sequential: 1-10                       [32, 512]            [32, 8]              --                   True
│    └─Dropout: 2-9                      [32, 512]            [32, 512]            --                   --
│    └─Linear: 2-10                      [32, 512]            [32, 8]              4,104                True
========================================================================================================================
Total params: 11,180,616
Trainable params: 11,180,616
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 17.77
========================================================================================================================
Input size (MB): 5.90
Forward/backward pass size (MB): 389.29
Params size (MB): 44.72
Estimated Total Size (MB): 439.91
========================================================================================================================

In [53]:
main_kolesa_new(model_resnet_brand_reg, train_df=train_df_brand, val_df=val_df_brand)
save_model_artifact(model_resnet_brand_reg, 'ResNet18_reg_finetune_brand')

Epoch: 1

100%|██████████| 97/97 [01:02<00:00,  1.54it/s]

Train set: Average loss: 1.9662, Accuracy: 20.50%
Val set: Average loss: 1.9145, Accuracy: 38.80%

Classification report:
               precision    recall  f1-score   support

         Audi       0.51      0.32      0.39        73
          BMW       0.45      0.84      0.59        90
    Chevrolet       0.33      0.71      0.45        79
      Hyundai       0.43      0.11      0.17        85
          Kia       0.46      0.14      0.22        77
        Lexus       0.33      0.40      0.36        95
Mercedes-Benz       0.38      0.51      0.44        81
       Toyota       0.27      0.05      0.08        85

     accuracy                           0.39       665
    macro avg       0.40      0.38      0.34       665
 weighted avg       0.39      0.39      0.34       665


Epoch: 2

100%|██████████| 97/97 [01:02<00:00,  1.56it/s]

Train set: Average loss: 1.4085, Accuracy: 43.06%
Val set: Average loss: 1.4325, Accuracy: 56.24%

Classification report:
               precision    recall  f1-score   support

         Audi       0.68      0.68      0.68        73
          BMW       0.76      0.82      0.79        90
    Chevrolet       0.54      0.76      0.63        79
      Hyundai       0.55      0.49      0.52        85
          Kia       0.56      0.32      0.41        77
        Lexus       0.36      0.61      0.45        95
Mercedes-Benz       0.72      0.63      0.67        81
       Toyota       0.48      0.16      0.25        85

     accuracy                           0.56       665
    macro avg       0.58      0.56      0.55       665
 weighted avg       0.58      0.56      0.55       665


Epoch: 3

100%|██████████| 97/97 [01:04<00:00,  1.50it/s]

Train set: Average loss: 1.1029, Accuracy: 60.88%
Val set: Average loss: 1.1069, Accuracy: 71.28%

Classification report:
               precision    recall  f1-score   support

         Audi       0.71      0.77      0.74        73
          BMW       0.89      0.86      0.87        90
    Chevrolet       0.65      0.89      0.75        79
      Hyundai       0.61      0.72      0.66        85
          Kia       0.72      0.60      0.65        77
        Lexus       0.62      0.64      0.63        95
Mercedes-Benz       0.88      0.73      0.80        81
       Toyota       0.71      0.52      0.60        85

     accuracy                           0.71       665
    macro avg       0.72      0.71      0.71       665
 weighted avg       0.72      0.71      0.71       665


Epoch: 4

100%|██████████| 97/97 [01:02<00:00,  1.55it/s]

Train set: Average loss: 0.8390, Accuracy: 72.90%
Val set: Average loss: 0.9678, Accuracy: 77.44%

Classification report:
               precision    recall  f1-score   support

         Audi       0.84      0.78      0.81        73
          BMW       0.88      0.90      0.89        90
    Chevrolet       0.68      0.94      0.79        79
      Hyundai       0.68      0.81      0.74        85
          Kia       0.82      0.64      0.72        77
        Lexus       0.72      0.75      0.73        95
Mercedes-Benz       0.85      0.78      0.81        81
       Toyota       0.84      0.60      0.70        85

     accuracy                           0.77       665
    macro avg       0.79      0.77      0.77       665
 weighted avg       0.79      0.77      0.77       665


Epoch: 5

100%|██████████| 97/97 [01:02<00:00,  1.54it/s]

Train set: Average loss: 0.8437, Accuracy: 80.31%
Val set: Average loss: 0.8643, Accuracy: 79.40%

Classification report:
               precision    recall  f1-score   support

         Audi       0.88      0.78      0.83        73
          BMW       0.91      0.89      0.90        90
    Chevrolet       0.68      0.94      0.79        79
      Hyundai       0.68      0.85      0.75        85
          Kia       0.88      0.69      0.77        77
        Lexus       0.74      0.77      0.75        95
Mercedes-Benz       0.87      0.81      0.84        81
       Toyota       0.85      0.62      0.72        85

     accuracy                           0.79       665
    macro avg       0.81      0.79      0.79       665
 weighted avg       0.81      0.79      0.79       665


Epoch: 6

100%|██████████| 97/97 [01:03<00:00,  1.54it/s]

Train set: Average loss: 0.5780, Accuracy: 85.24%
Val set: Average loss: 0.8098, Accuracy: 82.11%

Classification report:
               precision    recall  f1-score   support

         Audi       0.89      0.79      0.84        73
          BMW       0.90      0.90      0.90        90
    Chevrolet       0.77      0.95      0.85        79
      Hyundai       0.70      0.89      0.79        85
          Kia       0.91      0.69      0.79        77
        Lexus       0.74      0.82      0.78        95
Mercedes-Benz       0.89      0.84      0.87        81
       Toyota       0.89      0.67      0.77        85

     accuracy                           0.82       665
    macro avg       0.84      0.82      0.82       665
 weighted avg       0.83      0.82      0.82       665


Epoch: 7

100%|██████████| 97/97 [01:03<00:00,  1.54it/s]

Train set: Average loss: 0.6196, Accuracy: 88.82%
Val set: Average loss: 0.7305, Accuracy: 83.76%

Classification report:
               precision    recall  f1-score   support

         Audi       0.89      0.79      0.84        73
          BMW       0.92      0.90      0.91        90
    Chevrolet       0.79      0.97      0.87        79
      Hyundai       0.70      0.92      0.80        85
          Kia       0.90      0.78      0.83        77
        Lexus       0.79      0.80      0.80        95
Mercedes-Benz       0.90      0.85      0.87        81
       Toyota       0.92      0.68      0.78        85

     accuracy                           0.84       665
    macro avg       0.85      0.84      0.84       665
 weighted avg       0.85      0.84      0.84       665


Epoch: 8

100%|██████████| 97/97 [01:03<00:00,  1.54it/s]

Train set: Average loss: 0.4958, Accuracy: 92.07%
Val set: Average loss: 0.7159, Accuracy: 84.81%

Classification report:
               precision    recall  f1-score   support

         Audi       0.91      0.81      0.86        73
          BMW       0.88      0.91      0.90        90
    Chevrolet       0.79      0.95      0.86        79
      Hyundai       0.76      0.91      0.83        85
          Kia       0.89      0.77      0.83        77
        Lexus       0.86      0.83      0.84        95
Mercedes-Benz       0.85      0.86      0.86        81
       Toyota       0.89      0.74      0.81        85

     accuracy                           0.85       665
    macro avg       0.85      0.85      0.85       665
 weighted avg       0.85      0.85      0.85       665


Epoch: 9

100%|██████████| 97/97 [01:02<00:00,  1.54it/s]

Train set: Average loss: 0.4454, Accuracy: 92.97%
Val set: Average loss: 0.6643, Accuracy: 85.26%

Classification report:
               precision    recall  f1-score   support

         Audi       0.89      0.81      0.85        73
          BMW       0.87      0.92      0.90        90
    Chevrolet       0.77      0.97      0.86        79
      Hyundai       0.77      0.88      0.82        85
          Kia       0.94      0.81      0.87        77
        Lexus       0.86      0.80      0.83        95
Mercedes-Benz       0.85      0.88      0.86        81
       Toyota       0.93      0.75      0.83        85

     accuracy                           0.85       665
    macro avg       0.86      0.85      0.85       665
 weighted avg       0.86      0.85      0.85       665


Epoch: 10

100%|██████████| 97/97 [01:02<00:00,  1.54it/s]

Train set: Average loss: 0.4209, Accuracy: 95.55%
Val set: Average loss: 0.7055, Accuracy: 86.17%

Classification report:
               precision    recall  f1-score   support

         Audi       0.91      0.81      0.86        73
          BMW       0.87      0.92      0.90        90
    Chevrolet       0.85      0.95      0.90        79
      Hyundai       0.82      0.91      0.86        85
          Kia       0.89      0.82      0.85        77
        Lexus       0.83      0.84      0.84        95
Mercedes-Benz       0.87      0.89      0.88        81
       Toyota       0.88      0.75      0.81        85

     accuracy                           0.86       665
    macro avg       0.86      0.86      0.86       665
 weighted avg       0.86      0.86      0.86       665


Epoch: 11

100%|██████████| 97/97 [01:03<00:00,  1.52it/s]

Train set: Average loss: 0.3723, Accuracy: 96.58%
Val set: Average loss: 0.6802, Accuracy: 85.71%

Classification report:
               precision    recall  f1-score   support

         Audi       0.91      0.81      0.86        73
          BMW       0.89      0.91      0.90        90
    Chevrolet       0.80      0.96      0.87        79
      Hyundai       0.81      0.89      0.85        85
          Kia       0.95      0.82      0.88        77
        Lexus       0.85      0.81      0.83        95
Mercedes-Benz       0.79      0.90      0.84        81
       Toyota       0.91      0.75      0.83        85

     accuracy                           0.86       665
    macro avg       0.86      0.86      0.86       665
 weighted avg       0.86      0.86      0.86       665


Epoch: 12

100%|██████████| 97/97 [01:03<00:00,  1.53it/s]

Train set: Average loss: 0.4436, Accuracy: 97.52%
Val set: Average loss: 0.6595, Accuracy: 86.02%

Classification report:
               precision    recall  f1-score   support

         Audi       0.88      0.81      0.84        73
          BMW       0.88      0.91      0.90        90
    Chevrolet       0.78      0.96      0.86        79
      Hyundai       0.86      0.92      0.89        85
          Kia       0.88      0.84      0.86        77
        Lexus       0.88      0.81      0.84        95
Mercedes-Benz       0.86      0.85      0.86        81
       Toyota       0.88      0.78      0.82        85

     accuracy                           0.86       665
    macro avg       0.86      0.86      0.86       665
 weighted avg       0.86      0.86      0.86       665


Epoch: 13

100%|██████████| 97/97 [01:03<00:00,  1.53it/s]

Train set: Average loss: 0.3493, Accuracy: 98.23%
Val set: Average loss: 0.6445, Accuracy: 85.71%

Classification report:
               precision    recall  f1-score   support

         Audi       0.86      0.82      0.84        73
          BMW       0.93      0.91      0.92        90
    Chevrolet       0.82      0.95      0.88        79
      Hyundai       0.76      0.92      0.83        85
          Kia       0.91      0.79      0.85        77
        Lexus       0.89      0.77      0.82        95
Mercedes-Benz       0.86      0.89      0.87        81
       Toyota       0.87      0.81      0.84        85

     accuracy                           0.86       665
    macro avg       0.86      0.86      0.86       665
 weighted avg       0.86      0.86      0.86       665


Epoch: 14

100%|██████████| 97/97 [01:04<00:00,  1.52it/s]

Train set: Average loss: 0.3365, Accuracy: 99.00%
Val set: Average loss: 0.6190, Accuracy: 86.62%

Classification report:
               precision    recall  f1-score   support

         Audi       0.86      0.81      0.83        73
          BMW       0.90      0.91      0.91        90
    Chevrolet       0.80      0.94      0.86        79
      Hyundai       0.85      0.93      0.89        85
          Kia       0.91      0.87      0.89        77
        Lexus       0.85      0.84      0.85        95
Mercedes-Benz       0.87      0.90      0.88        81
       Toyota       0.93      0.73      0.82        85

     accuracy                           0.87       665
    macro avg       0.87      0.87      0.86       665
 weighted avg       0.87      0.87      0.87       665


Epoch: 15

100%|██████████| 97/97 [01:03<00:00,  1.53it/s]

Train set: Average loss: 0.3223, Accuracy: 99.16%
Val set: Average loss: 0.6292, Accuracy: 87.07%

Classification report:
               precision    recall  f1-score   support

         Audi       0.90      0.82      0.86        73
          BMW       0.89      0.91      0.90        90
    Chevrolet       0.84      0.94      0.89        79
      Hyundai       0.84      0.89      0.87        85
          Kia       0.93      0.87      0.90        77
        Lexus       0.86      0.83      0.84        95
Mercedes-Benz       0.84      0.91      0.88        81
       Toyota       0.88      0.79      0.83        85

     accuracy                           0.87       665
    macro avg       0.87      0.87      0.87       665
 weighted avg       0.87      0.87      0.87       665

Training is ended!

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

[OK] модель сохранена: ../data/models/ResNet18_reg_finetune_brand.pt

87.07% - догнали результат ResNet на типах кузова на задаче, где мы стартовали с 14% accuracy - это отличный прогресс для такой сложной задачи. И уже, к примеру, Toyota не выглядит такой проблемной, в целом, у всех марок примерно схожие результаты по метрикам, так что это объективная крепкая модель + показывает эту огромную разницу с полностью самостоятельными моделями. Вохможно, было бы у нас больше данных, то на начальных моделях были бы результаты лучше, но мы постарались в рамках наших ограничений выжать максимум.

## Сравнение и выводы

Теперь для всех сохраненных моделей сделаем прогоны на test и сохраним результаты. Полное сранение сделаем уже в другом ноутбуке.

Будем брать сохраненные веса с .pt файлов

In [34]:
# https://docs.pytorch.org/tutorials/beginner/saving_loading_models.html
def load_model(model, model_name):
    path = base_dir / 'models' / f'{model_name}.pt'
    model.load_state_dict(torch.load(path, weights_only=True))
    return model

model_baseline_bt = load_model(model_baseline_bt, 'BaseLine_FC_body_type')
model_cnn_1_bt = load_model(model_cnn_1_bt, 'Base_CNN_body_type')
model_cnn_2_bt = load_model(model_cnn_2_bt, 'Reg_CNN_body_type')
model_resnet_bt = load_model(model_resnet_bt, 'ResNet18_finetune_body_type')
model_resnet_bt_reg = load_model(model_resnet_bt_reg, 'ResNet18_reg_finetune_bt')

model_baseline_brand = load_model(model_baseline_brand, 'BaseLine_FC_brand')
model_cnn_1_brand = load_model(model_cnn_1_brand, 'Base_CNN_brand')
model_cnn_2_brand = load_model(model_cnn_2_brand, 'Reg_CNN_brand')
model_resnet_brand = load_model(model_resnet_brand, 'ResNet18_finetune_brand')
model_resnet_brand_reg = load_model(model_resnet_brand_reg, 'ResNet18_reg_finetune_brand')

In [35]:
def main_kolesa_test(model, test_df, img_size=(96, 160)):
    seed_everything(CFG.seed)

    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')

    kwargs = {'num_workers': CFG.num_workers, 'pin_memory': torch.cuda.is_available()}

    test_transform = transforms.Compose([
        transforms.Resize(img_size), # т.к. у нас две версии resize, то оставим как переменная
        transforms.ToTensor(),
        transforms.Normalize(
            mean=(0.485, 0.456, 0.406),
            std=(0.229, 0.224, 0.225)
        )
        ])
    
    test_ds = KolesaDataset(test_df, transform=test_transform)

    test_loader = torch.utils.data.DataLoader(test_ds, batch_size=CFG.test_batch_size, **kwargs)

    model = model.to(device)

    criterion = nn.CrossEntropyLoss()

    accuracy, macro_f1, weighted_f1, report = test(model, device, test_loader, criterion, CFG.wandb)

    return accuracy, macro_f1, weighted_f1, report

In [ ]:
CFG.wandb = False
rows = []

### Test для задачи на тип кузова

In [ ]:
CFG.classes = all_body_types
CFG.test_batch_size = 512

body_type_models = [
    ['BaseLine_FC', model_baseline_bt],
    ['Base_CNN', model_cnn_1_bt],
    ['Reg_CNN', model_cnn_2_bt],
    ['ResNet18_finetune', model_resnet_bt]
]

for model_name, model in body_type_models:
    print(model_name)
    accuracy, macro_f1, weighted_f1, report = main_kolesa_test(model, test_df_bt)

    rows.append({
        'model': model_name,
        'task': 'body_type',
        'accuracy': accuracy,
        'macro_f1': macro_f1,
        'weighted_f1': weighted_f1
    })

# отдельно reg resnet

CFG.test_batch_size = 64

print('ResNet18_reg_finetune')
accuracy, macro_f1, weighted_f1, report = main_kolesa_test(model_resnet_bt_reg, test_df_bt, img_size=(320, 512))

rows.append({
    'model': 'ResNet18_reg_finetune',
    'task': 'body_type',
    'accuracy': accuracy,
    'macro_f1': macro_f1,
    'weighted_f1': weighted_f1
})

BaseLine_FC
Test set: Accuracy: 54.74%

Classification report:
              precision    recall  f1-score   support

       sedan       0.67      0.56      0.61       419
         SUV       0.41      0.52      0.46       246

    accuracy                           0.55       665
   macro avg       0.54      0.54      0.54       665
weighted avg       0.57      0.55      0.55       665

Base_CNN
Test set: Accuracy: 64.21%

Classification report:
              precision    recall  f1-score   support

       sedan       0.79      0.59      0.67       419
         SUV       0.51      0.73      0.60       246

    accuracy                           0.64       665
   macro avg       0.65      0.66      0.64       665
weighted avg       0.69      0.64      0.65       665

Reg_CNN
Test set: Accuracy: 67.52%

Classification report:
              precision    recall  f1-score   support

       sedan       0.87      0.57      0.69       419
         SUV       0.54      0.86      0.66       246

    accuracy                           0.68       665
   macro avg       0.71      0.71      0.67       665
weighted avg       0.75      0.68      0.68       665

ResNet18_finetune
Test set: Accuracy: 89.32%

Classification report:
              precision    recall  f1-score   support

       sedan       0.93      0.90      0.91       419
         SUV       0.84      0.88      0.86       246

    accuracy                           0.89       665
   macro avg       0.88      0.89      0.89       665
weighted avg       0.90      0.89      0.89       665

ResNet18_reg_finetune
Test set: Accuracy: 96.84%

Classification report:
              precision    recall  f1-score   support

       sedan       0.96      0.99      0.98       419
         SUV       0.98      0.93      0.96       246

    accuracy                           0.97       665
   macro avg       0.97      0.96      0.97       665
weighted avg       0.97      0.97      0.97       665

### Test для задачи на марки

In [ ]:
CFG.classes = all_brands
CFG.test_batch_size = 512

brand_models = [
    ['BaseLine_FC', model_baseline_brand],
    ['Base_CNN', model_cnn_1_brand],
    ['Reg_CNN', model_cnn_2_brand],
    ['ResNet18_finetune', model_resnet_brand]
]

for model_name, model in brand_models:
    print(model_name)
    accuracy, macro_f1, weighted_f1, report = main_kolesa_test(model, test_df_brand)

    rows.append({
        'model': model_name,
        'task': 'brand',
        'accuracy': accuracy,
        'macro_f1': macro_f1,
        'weighted_f1': weighted_f1
    })

# отдельно reg resnet

CFG.test_batch_size = 64

print('ResNet18_reg_finetune')
accuracy, macro_f1, weighted_f1, report = main_kolesa_test(model_resnet_brand_reg, test_df_brand, img_size=(320, 512))

rows.append({
    'model': 'ResNet18_reg_finetune',
    'task': 'brand',
    'accuracy': accuracy,
    'macro_f1': macro_f1,
    'weighted_f1': weighted_f1
})

BaseLine_FC
Test set: Accuracy: 15.19%

Classification report:
               precision    recall  f1-score   support

         Audi       0.16      0.19      0.18        72
          BMW       0.20      0.10      0.13        90
    Chevrolet       0.16      0.15      0.16        78
      Hyundai       0.17      0.17      0.17        86
          Kia       0.12      0.10      0.11        77
        Lexus       0.15      0.15      0.15        95
Mercedes-Benz       0.15      0.13      0.14        82
       Toyota       0.13      0.21      0.16        85

     accuracy                           0.15       665
    macro avg       0.16      0.15      0.15       665
 weighted avg       0.16      0.15      0.15       665

Base_CNN
Test set: Accuracy: 19.85%

Classification report:
               precision    recall  f1-score   support

         Audi       0.24      0.32      0.28        72
          BMW       0.16      0.31      0.21        90
    Chevrolet       0.29      0.13      0.18        78
      Hyundai       0.12      0.01      0.02        86
          Kia       0.27      0.19      0.23        77
        Lexus       0.29      0.16      0.20        95
Mercedes-Benz       0.12      0.21      0.15        82
       Toyota       0.22      0.27      0.24        85

     accuracy                           0.20       665
    macro avg       0.21      0.20      0.19       665
 weighted avg       0.21      0.20      0.19       665

Reg_CNN
Test set: Accuracy: 28.42%

Classification report:
               precision    recall  f1-score   support

         Audi       0.23      0.22      0.22        72
          BMW       0.27      0.72      0.40        90
    Chevrolet       0.36      0.36      0.36        78
      Hyundai       0.25      0.06      0.09        86
          Kia       0.38      0.26      0.31        77
        Lexus       0.23      0.14      0.17        95
Mercedes-Benz       0.27      0.24      0.26        82
       Toyota       0.29      0.26      0.27        85

     accuracy                           0.28       665
    macro avg       0.28      0.28      0.26       665
 weighted avg       0.28      0.28      0.26       665

ResNet18_finetune
Test set: Accuracy: 58.20%

Classification report:
               precision    recall  f1-score   support

         Audi       0.69      0.61      0.65        72
          BMW       0.76      0.72      0.74        90
    Chevrolet       0.56      0.78      0.65        78
      Hyundai       0.42      0.49      0.45        86
          Kia       0.57      0.32      0.41        77
        Lexus       0.65      0.57      0.61        95
Mercedes-Benz       0.56      0.70      0.62        82
       Toyota       0.49      0.46      0.48        85

     accuracy                           0.58       665
    macro avg       0.59      0.58      0.58       665
 weighted avg       0.59      0.58      0.58       665

ResNet18_reg_finetune
Test set: Accuracy: 88.42%

Classification report:
               precision    recall  f1-score   support

         Audi       0.97      0.94      0.96        72
          BMW       0.93      0.98      0.95        90
    Chevrolet       0.82      0.92      0.87        78
      Hyundai       0.83      0.78      0.80        86
          Kia       0.89      0.86      0.87        77
        Lexus       0.86      0.87      0.87        95
Mercedes-Benz       0.90      0.94      0.92        82
       Toyota       0.89      0.79      0.84        85

     accuracy                           0.88       665
    macro avg       0.89      0.89      0.88       665
 weighted avg       0.88      0.88      0.88       665

In [39]:
results_dl_images = pd.DataFrame(rows)
results_dl_images

                   model       task  accuracy  macro_f1  weighted_f1
0            BaseLine_FC  body_type  0.547368  0.535107     0.554748
1               Base_CNN  body_type  0.642105  0.638435     0.647912
2                Reg_CNN  body_type  0.675188  0.674652     0.678088
3      ResNet18_finetune  body_type  0.893233  0.886673     0.893766
4  ResNet18_reg_finetune  body_type  0.968421  0.965803     0.968265
5            BaseLine_FC      brand  0.151880  0.150438     0.150214
6               Base_CNN      brand  0.198496  0.189036     0.187316
7                Reg_CNN      brand  0.284211  0.260676     0.259223
8      ResNet18_finetune      brand  0.581955  0.576440     0.577551
9  ResNet18_reg_finetune      brand  0.884211  0.884551     0.883427

In [41]:
results_dl_images.to_csv('../data/results_dl_images.csv', index=False)